### ISSUE TITLE
Maximum number of parallel submissions allowed

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#1005]
We want a configurable parameter which lets us specify, how many parallel submissions are allowed from a single user at any point of time.

For example, if we say, challenge A, has 2 allowed parallel submissions, then on every submission, we check how many submissions by this user have a state of "submitted", and if this number exceeds 2, then we throw an error with an appropriate message.

Also, marking this as high priority, as the lack of this feature is allowing some users to clog the evaluation servers with many parallel submissions at the same time.

The default value could be : 0 ; which would mean that an infinite number of parallel submissions are allowed.

**Comment by scarroll32** [comment]
https://github.com/crowdAI/crowdai/issues/1005

**Comment by scarroll32** [comment]
Implemented
