### ISSUE TITLE
Learning How To Walk challenge leaderboard is broken

### ISSUE THREAD

**Issue by marcelsalathe** [crowdAI/crowdai#102]
<img width="981" alt="screen shot 2017-05-03 at 7 42 14 am" src="https://cloud.githubusercontent.com/assets/215057/25649298/898b1e26-2fd4-11e7-8704-f51bf9567a6a.png">

**Comment by scarroll32** [comment]
Fixed https://github.com/crowdAI/crowdai/commit/4cd1d5c04bb2f7a0aa500fa1500af335e271e674
