### ISSUE TITLE
Improve jobs page

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#1021]
- [x] Allow admins to see draft and closed jobs
- [ ] bigger edit area for markdown
- [x] dropdown for status

**Comment by Sylvain-Bernard** [comment]
related to #586

**Comment by scarroll32** [comment]
This is a quick fix, but we will soon add a better editor and some type of self-service job management. The design needs a bit of a refresh also.

**Comment by scarroll32** [comment]
Implemented
