### ISSUE TITLE
Notifications on Forum posts

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#1066]
Not sending notifications on forum posts, is very strongly affecting the UX on crowdAI. We should urgently come up with a solution for this.

**Comment by scarroll32** [comment]
An email could be sent to organizers / admins every time there is a forum post, but that would get a bit annoying.

We send a daily email to challenge organizers and admins, once a day, when the last comment on a topic was not a admin or organizer ... and the last comment.

The other option is for the organizers to monitor the forums themselves, flooding the organizers with emails might lead to those emails being ignored.

Let me know which way you want to go.

**Comment by spMohanty** [comment]
@seanfcarroll : I think we should make it configurable.
I am not sure about the daily email, as I myself didnt receive any for many of the challenges. or maybe it just ends in spam ?

In any case, this should be configurable, where any user subscribed to a topic : people who posted the topic, others who commented on the topic, admins, organizers get an email based on their choice of frequency : when they are tagged, always, a summary daily, etc.

But the notifications will also act as a way to let other participants know about updates on a thread and bring them back to contribute more to the thread, and hence its not just organizer specific.

Learning from how platforms like discourse do it would be a good start.

**Comment by scarroll32** [comment]
Dependent issue https://github.com/crowdAI/crowdai/issues/1062

**Comment by scarroll32** [comment]
Closed as there is an active [upstream issue](https://github.com/AICrowd/AIcrowd/issues/75) on AIcrowd
