### ISSUE TITLE
Render meta parameters on submission page

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#1083]
It would be good to render meta parameters on the submission page, for example here : https://www.crowdai.org/challenges/spotify-sequential-skip-prediction-challenge/submissions/20442/edit

The meta parameters should be rendered for privileged users : challenge organizers, admins
And simple indendent json dump should also do the trick for now.
This will be important for keeping a track of whats happening in the spotify challenge, where we have some extra evaluation metrics exposed in the meta parameters.

**Comment by scarroll32** [comment]
Implemented 

<img width="997" alt="screen shot 2018-11-19 at 17 16 18" src="https://user-images.githubusercontent.com/11340230/48719950-efbb3e80-ec1e-11e8-8973-df6b629b0bb2.png">
