### ISSUE TITLE
Add challenge round to grader service call

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#1087]
Change [this code](https://github.com/crowdAI/crowdai/blob/master/app/services/grader_service.rb#L74) to include challenge_round_id

```
data: [{"file_key": submission_key, submission_id: @submission.id, participant_id: @submission.participant_id, round: @challenge.current_round}],
```

**Comment by scarroll32** [comment]
will be ```challenge_round_id```  @spMohanty

**Comment by spMohanty** [comment]
Thanks @seanfcarroll !

**Comment by scarroll32** [comment]
No problemo, it's implemented in production now https://github.com/crowdAI/crowdai/commit/9d59a7530aacc67d2eeb0860fbb8d91d5030b74f
