### ISSUE TITLE
Password field needs styling

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#114]
Am presently using a regular text field as the password field is not styled.
<img width="629" alt="screen shot 2017-05-25 at 21 48 08" src="https://cloud.githubusercontent.com/assets/11340230/26467666/ee747802-4193-11e7-9b22-0775f8c7c923.png">

**Comment by scarroll32** [comment]
Styles changed in multiple places https://github.com/crowdAI/crowdai/commit/e4b17aba0a26b6d69bbf8ff931d56e4564b753ba

@jsnrynlds could you please review.

**Comment by jsnrynlds** [comment]
Looks fine to me @seanfcarroll.
