### ISSUE TITLE
API Key & recycle button styling

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#115]
For Participants and Challenges. API Key has been removed from Organizer.

<img width="547" alt="screen shot 2017-05-25 at 21 55 00" src="https://cloud.githubusercontent.com/assets/11340230/26467932/e0dd3462-4194-11e7-84c7-eab3fb3829de.png">

<img width="829" alt="screen shot 2017-05-25 at 21 56 27" src="https://cloud.githubusercontent.com/assets/11340230/26467979/08d21924-4195-11e7-8085-874e49271172.png">

**Comment by scarroll32** [comment]
Have added some stopgap html to allow the v2 release. https://github.com/crowdAI/crowdai/commit/19b25b55523d8c2df88f896ca8890aebfb529629

**Comment by scarroll32** [comment]
<img width="546" alt="screen shot 2017-05-29 at 21 36 21" src="https://cloud.githubusercontent.com/assets/11340230/26560433/e328fc40-44b6-11e7-9735-cbac7035feca.png">

**Comment by scarroll32** [comment]
This needs to move to the masthead. #show view

**Comment by jsnrynlds** [comment]
You can see this in _template-user-profile-owner.html_.

**Comment by scarroll32** [comment]
Closed https://github.com/crowdAI/crowdai/commit/993cf0b6b4d6c7bed31158723244d6c4ad39f293
