### ISSUE TITLE
Buttons overlapping

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#116]
Because the Rails form builder produces the submit as an input, the styling needs a tweak.

<img width="555" alt="screen shot 2017-05-25 at 22 00 44" src="https://cloud.githubusercontent.com/assets/11340230/26468130/a118e8de-4195-11e7-8e15-aabe3a005374.png">

```html
<div class="button-group">
  <input type="submit" name="commit" value="Update Challenge" class="btn btn-primary" data-disable-with="Update Challenge">
  <a class="btn btn-secondary" href="/challenges">Cancel</a>
</div>
```

**Comment by scarroll32** [comment]
Don't worry, I found a workaround. Closed.

**Comment by scarroll32** [comment]
https://github.com/crowdAI/crowdai/commit/1156c201efb237d9e70e90d0c3c68522022b5a53

**Comment by scarroll32** [comment]
It seems the workaround is causing a different issues. 

@jsnrynlds could you please update the button-group to also accept links styled as buttons. 
cc @yannis

**Comment by jsnrynlds** [comment]
@seanfcarroll The button group already supported links styled as buttons, but the input styles were overwriting it. I've added an `!important` rule on _line 51_ of `_layout-molecules.scss` to prevent this. 

`.button-group {
  overflow: hidden;
  padding-bottom: 4px;
  .btn {
    float: left;
    margin-right: 16px !important;
    &:last-of-type {
      margin-right: 0;
    }
    @media screen and (max-width: 800px) {
      margin-right: 12px;
    }
  }
}`

Pushed.

**Comment by scarroll32** [comment]
This affects almost every form in the application, they all need to be adjusted. (look for button_to)

**Comment by scarroll32** [comment]
Implemented
