### ISSUE TITLE
crowdAI logo not appearing in mobile view

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#122]
The crowdAI head should appear in the mobile view.

**Comment by marcelsalathe** [comment]
Why was @jsnrynlds unassigned?

**Comment by scarroll32** [comment]
It is appearing on some templates ... so a coding issue.

**Comment by scarroll32** [comment]
Fixed https://github.com/crowdAI/crowdai/pull/177/commits/1b7adf1162dc4290edd2f12b8647a0d22599186f
