### ISSUE TITLE
Logo, search button and text field weird display

### ISSUE THREAD

**Issue by Boris-c** [crowdAI/crowdai#125]
Safari Mac:
<img width="207" alt="crowdaisearchissuesafarimac" src="https://cloud.githubusercontent.com/assets/7315069/26542064/c3482f9e-4458-11e7-8b2e-e1c79407ef14.png">

iPhone 6s Plus vertical (icon missing):
![img_6056](https://cloud.githubusercontent.com/assets/7315069/26542245/84a15670-4459-11e7-89b4-81a59ebe6003.PNG)

iPhone 6s Plus horizontal:
![img_6057](https://cloud.githubusercontent.com/assets/7315069/26542249/8816c330-4459-11e7-83ad-19954c98412e.PNG)

**Comment by scarroll32** [comment]
I've created a webserver to server the static designs. The issue appears to be safari-related.
<img width="910" alt="screen shot 2017-05-29 at 12 40 09" src="https://cloud.githubusercontent.com/assets/11340230/26546785/0f1e4f62-446c-11e7-85e5-a8d6bfd18aa1.png">

The webserver is at: https://limitless-island-70890.herokuapp.com/template-terms.html

**Comment by scarroll32** [comment]
Remove search icon from v2 https://github.com/crowdAI/crowdai/commit/a12139ce9af29f2b823eb0b547b9378f9d6ad822

**Comment by jsnrynlds** [comment]
I've emailed Owen (the dev who helped me with a few bits) about this. Will keep you updated.

**Comment by jsnrynlds** [comment]
Think this has been fixed although will need checking on iPhone Safari.

**Comment by scarroll32** [comment]
https://github.com/salathegroup/crowdai-templates/commit/502c152a73786bafc0c51d579799b6f56fe881aa
