### ISSUE TITLE
Handling large numbers in stats

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#126]
Go to "k" after "1.1k" after reaching 1000
<img width="1133" alt="screen shot 2017-05-29 at 11 02 46" src="https://cloud.githubusercontent.com/assets/11340230/26543506/804bf238-445e-11e7-8400-622eb78af122.png">

**Comment by scarroll32** [comment]
Move to a cell along with pluralization.

**Comment by scarroll32** [comment]
Closed https://github.com/crowdAI/crowdai/commit/ed6cc6343fd6c79acdc6620d994309d92d4bfcbc

**Comment by marcelsalathe** [comment]
I'm fine with this with two caveats:
1. Let's do that after 10,000, not after 1,000
2. Let's round to hundreds, i.e. 12,378 would then be shown as 12.4k

**Comment by scarroll32** [comment]
OK no problem

**Comment by scarroll32** [comment]
https://github.com/crowdAI/crowdai/commit/61d42a8b448be7716de2108c008861a9a0fd8f99

**Comment by scarroll32** [comment]
Closed https://github.com/crowdAI/crowdai/commit/af46b7e660956efa0ec9be068cbec770a73c3255
