### ISSUE TITLE
Images are blown up 

### ISSUE THREAD

**Issue by marcelsalathe** [crowdAI/crowdai#131]
This e.g from a challenge:

<img width="744" alt="screen shot 2017-05-29 at 6 02 31 pm" src="https://cloud.githubusercontent.com/assets/215057/26556133/142b34c0-4499-11e7-931f-e67fbe56d716.png">

**Comment by scarroll32** [comment]
Fixed with https://github.com/crowdAI/crowdai/commit/8d4b2d5d3b2914c852c6a4d7b97f235f36f9012b

@jsnrynlds Can you please review to clarify is this change is a good idea.

**Comment by jsnrynlds** [comment]
Looks good to me, thanks @seanfcarroll.
