### ISSUE TITLE
Inline error styling

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#133]
How do we want this to appear?

<img width="528" alt="screen shot 2017-05-29 at 22 58 08" src="https://cloud.githubusercontent.com/assets/11340230/26561912/66177ad6-44c2-11e7-8adf-2ab09b32d7eb.png">

**Comment by jsnrynlds** [comment]
@seanfcarroll I'll create a style for the text but think we should also highlight the relevant textbox/textarea with a red (#f0524d) border.

**Comment by scarroll32** [comment]
Works for me

**Comment by jsnrynlds** [comment]
@seanfcarroll This is what I had in mind...

![crowdai_form_error](https://user-images.githubusercontent.com/1162939/26920688-a9151836-4c31-11e7-9cf1-2c5f647d11e9.png)

**Comment by scarroll32** [comment]
I like it. @marcelsalathe ?

**Comment by scarroll32** [comment]
@jsnrynlds do you have view when we will have the CSS for this? Cheers.

**Comment by marcelsalathe** [comment]
Yes I like it too!

**Comment by jsnrynlds** [comment]
Hi @seanfcarroll – I'll set aside some time to look at crowdAI tomorrow.

**Comment by jsnrynlds** [comment]
@seanfcarroll is this simply a case of creating a class that can be applied to form elements to change the border-color as well as one for the error text? I don't have much experience with form validation, sorry.

**Comment by scarroll32** [comment]
@jsnrynlds Hi Jason yes it would just be as you described. Something similar may be found in Bootstrap eg http://getbootstrap.com/css/#forms and it looks perfect the way you have designed it.

**Comment by jsnrynlds** [comment]
Thanks @seanfcarroll – I'll push this shortly.

**Comment by jsnrynlds** [comment]
Let me know if you experience any issues with this.

**Comment by scarroll32** [comment]
![screen shot 2017-06-23 at 14 00 16](https://user-images.githubusercontent.com/11340230/27481349-703bb96a-581c-11e7-9635-4c24e31cebc8.png)

**Comment by scarroll32** [comment]
https://github.com/salathegroup/crowdai-templates/commit/a37d5043d90d1a41801f6edc7887c27192f98508

**Comment by scarroll32** [comment]
Half done ... it's on a branch & will be ready after a bit of testing.

**Comment by scarroll32** [comment]
Fixed
