### ISSUE TITLE
Sub-nav active tab not correct colour on certain pages

### ISSUE THREAD

**Issue by jsnrynlds** [crowdAI/crowdai#134]
Hi @seanfcarroll – on some pages (e.g., https://crowdai-stg.herokuapp.com/challenges) the active tab in the sub-nav is dark-grey when it should be red.

**Comment by scarroll32** [comment]
Closed https://github.com/crowdAI/crowdai/commit/114f0ea56fba700ce1cfcb79b26397edf6f62eae
