### ISSUE TITLE
Redirect in case of unauthorised users

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#137]
Accessing links which require sign in take you back to the home page, and the error message on the top is not really apparent. It took me a minute of trying to figure out before noticing the error message. 

Example link : https://www.crowdai.org/topics/thank-you-everyone-results/comments/new
(Click when you are not signed in)

Ideally I think it should redirect to the login-page.

PS: But did we not also agree on having discussion forum links publicly accessible ? 
(So that they can be indexed by search engines)

**Comment by scarroll32** [comment]
> PS: But did we not also agree on having discussion forum links publicly accessible ?
(So that they can be indexed by search engines)

Yes we did, I will check the code.

**Comment by spMohanty** [comment]
@seanfcarroll : Thanks :D

**Comment by scarroll32** [comment]
They should go directly to the sign in page, will address.

Separate issue opened for access posts etc https://github.com/crowdAI/crowdai/issues/151

**Comment by scarroll32** [comment]
Closed
