### ISSUE TITLE
UX on homepage

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#138]
building up on the dotted+netted globe that we added on the homepage, I imagined something like this : 

https://s3.amazonaws.com/salathegroup-static/misc/mohanty/crowdai-tempaltes/organism-home-hero.html

as an extension of it which _**follows**_ the mouse on the home page.
Already implemented, and need feedback and opinions if we should use it in production.

cc, @jsnrynlds @marcelsalathe 

Implemented in commit (https://github.com/spMohanty/crowdai-templates/commit/8e9c2d3cec9d26807d10f1591dbbc4c2fb294cc0)

**Comment by scarroll32** [comment]
OK with me

**Comment by marcelsalathe** [comment]
It's funny but it adds visual noise but no content. Also my CPU starts spinning. So I'd vote against it.

**Comment by scarroll32** [comment]
Closing.

**Comment by spMohanty** [comment]
👍
