### ISSUE TITLE
console error on safari 

### ISSUE THREAD

**Issue by ggrrll** [crowdAI/crowdai#139]
<img width="1440" alt="screen shot 2017-05-31 at 17 40 03" src="https://cloud.githubusercontent.com/assets/15370425/26640707/c20f4b0e-4628-11e7-939d-ebc38adb0b47.png">

**Comment by scarroll32** [comment]
I think it should be OK now. Please re-check.

**Comment by scarroll32** [comment]
Still an issue on @ggrrll 's PC (but not mine). Error is captured by Rollbar https://rollbar.com/app48624194-heroku.com/app48624194-heroku.com/items/3/

**Comment by scarroll32** [comment]
Closed.
