### ISSUE TITLE
"Sea All" button on homepage a bit misleading

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#140]
The "See All" button on the home page for the challenges is a bit misleading.
Especially because the section header is "Challenges"

When I first landed on the page, I thought there were only a total of 3 challenges. And it took me some time to notice the "See All" button too.

Moving the "See All" button to something like a "Load More" button on the Challenges page(https://www.crowdai.org/challenges) might make more sense I think ?

Also changing the title to "Featured Challenges" might be more correct ?

cc. @jsnrynlds

**Comment by marcelsalathe** [comment]
I agree with the title change to "Featured Challenges"

I also agree that "See all" functionality should be duplicated on the home page using the same mechanism as the "Load More" button on the Challenges page.

I would also prefer to hide the "Load More" Button until we have something like a min of 20 challenges.

**Comment by scarroll32** [comment]
From my side, OK with 
- featured challenges
- load more > 20 

I think the home page should have a short list of featured challenges ... currently it will be the last 3 created that are active.

Then the see all should go to the existing challenges page, as there are filters there for challenge status.
<img width="633" alt="screen shot 2017-06-01 at 18 34 42" src="https://cloud.githubusercontent.com/assets/11340230/26690298/057ab86c-46f9-11e7-9b0f-8fa8d13e7621.png">

**Comment by scarroll32** [comment]
https://github.com/crowdAI/crowdai/commit/fc8001994eace048fe8074c6a744f7e3add34001
