### ISSUE TITLE
padding in the "video" column on the leaderboard

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#141]
The padding int the video column on the leaderboard is a bit weird ?

https://www.crowdai.org/challenges/learning-how-to-walk/leaderboards

**Comment by scarroll32** [comment]
The video wasn't designed for ... I haven't yet discussed it with Jason but let's discuss it with him next week. The modal isn't yet implemented https://github.com/crowdAI/crowdai/issues/135

**Comment by jsnrynlds** [comment]
@seanfcarroll @spMohanty will videos always be a 4:3 aspect ratio? If so I'll provide a new placeholder image as these are currently square. I think we can change the padding on the the video wrapper to:
```
table td {
padding: 0 0;
}
```

**Comment by scarroll32** [comment]
I suspect so, but @spMohanty can you confirm?

**Comment by spMohanty** [comment]
At least in context of this challenge it will always be 4:3 aspect ratio.

In future challenges, we can impose the rule and stick to videos with 4:3 aspect ration.

**Comment by jsnrynlds** [comment]
@seanfcarroll Coming back to this, I don't think we should include a placeholder image for entries that don't include a video. Could we just replace this with an em dash?

**Comment by scarroll32** [comment]
Hi Jason

There will be a mix of some rows with video and some without

Eg https://www.crowdai.org/challenges/learning-how-to-walk/leaderboards

But happy to go with your suggestion.

Cheers,
Sean

**Comment by scarroll32** [comment]
@jsnrynlds What is the final decision on this?

**Comment by scarroll32** [comment]
Hi @jsnrynlds, not sure if I did this correctly, but the result is as below, so I have not added the code at this point.
<img width="722" alt="screen shot 2017-06-29 at 16 30 10" src="https://user-images.githubusercontent.com/11340230/27692940-410815be-5ce8-11e7-9708-6fdb83411b48.png">




<img width="429" alt="screen shot 2017-06-29 at 16 29 03" src="https://user-images.githubusercontent.com/11340230/27692920-32aeece0-5ce8-11e7-8374-d557ae459bd8.png">

**Comment by jsnrynlds** [comment]
@seanfcarroll Ah, okay, I think that's due to the placeholders being square previously. Think 20px padding above/below will work.

I'm really up against it today but will be in touch tomorrow.

**Comment by scarroll32** [comment]
OK no problem, cheers. 

I'm on vacation from next week.

**Comment by jsnrynlds** [comment]
@seanfcarroll When I inspect this in Chrome it's showing `padding: 23px 0;` on the td. Can we try changing this to` padding: 16px 0;`? Also, I don't think we should include placeholders if there's no image... maybe just an em dash.

**Comment by scarroll32** [comment]
Hi @jsnrynlds 

I added the styling but it didn't seem to make a difference. Not sure if I am adding it in the wrong place, but you can see the change here: https://github.com/crowdAI/crowdai/pull/234/commits/ae4913a2124493d3bff463acab7f790c02d1e1fc

I also replaced the placeholder image with a <em></em> tag https://github.com/crowdAI/crowdai/commit/df3bf0e7a7a6089a5a5b6de4e2b1bbd0205eddf5

I think the placeholder works better. 

I'll leave this issue open as the padding issues are not resolved.

**Comment by scarroll32** [comment]
Added some padding. Closed.
