### ISSUE TITLE
Admin view for leaderboards not working

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#142]
The admin view from the previous version of crowdai is not visible anymore on the leaderboard.
Something that can be used in draft-mode or starting-soon challenges to keep a track of submissions or for beta testing the grader etc.

Ex : https://www.crowdai.org/challenges/learning-how-to-walk/leaderboards

Labelling it as high priority as we need it for the NIP challenge beta testing.

**Comment by spMohanty** [comment]
Also,  cant see any submissions on the leaderboard. when the stats about the challenge say there are 22 submissions

**Comment by scarroll32** [comment]
The admin view was removed from the design... we are not initiating the grading from the Rails app anymore so do we need it?

**Comment by spMohanty** [comment]
No we dont need a separate section like in the previous design, but we will still need the functionalities, like being able to view the (beta) submissions when challenge is in draft mode, or starting-soon mode.
Also to be able to force a re-grade of a particular submission from the web interface itself.

The API for the same is not yet implemented in `crowdai-broker`. Adding an issue for the same in the relevant repository (https://github.com/spMohanty/crowdai-broker-nodejs/issues/1).

**Comment by scarroll32** [comment]
Linked issues:

https://github.com/crowdAI/crowdai/issues/141

https://github.com/crowdAI/crowdai/issues/135

**Comment by scarroll32** [comment]
OK so as discussed on Slack, we can access the submissions within Activeadmin, but we will add some more detail.

Tasks:

- Add some detail to the active admin view
- Add a admin / organizer only switch to the leaderboard (to be later styled by Jason)
- The switch will turn the leaderboard into a list of submissions, including an indicator about if this entry is on the leaderboard
- we will probably need a participant filter and paging but I'll not add it just yet

<img width="893" alt="screen shot 2017-06-01 at 15 36 18" src="https://cloud.githubusercontent.com/assets/11340230/26683828/6c221ac4-46e5-11e7-9d2e-ea81cd2240dc.png">

**Comment by scarroll32** [comment]
Added a click on number of entries for the admin or the organizer (Lukas). More work to follow on the leaderboard. https://github.com/crowdAI/crowdai/pull/167/commits/c1b729a7d47b736ef048d60f61da245d93426834
<img width="1192" alt="screen shot 2017-06-02 at 15 57 13" src="https://cloud.githubusercontent.com/assets/11340230/26728937/2ce5e60c-47ac-11e7-9dce-b052ede4d096.png">

**Comment by scarroll32** [comment]
@spMohanty let me know if that works for now.
