### ISSUE TITLE
US economic sanctions in the terms page :-?

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#144]
We have a clause in our terms of service page which says :

_09. US Economic Sanctions
You expressly represent and warrant that your use of our Services and or associated services and products is not contrary to applicable U.S. Sanctions. Such use is prohibited, and crowdAI reserve the right to terminate accounts or access of those in the event of a breach of this condition._

Link : https://www.crowdAI.org/pages/terms

Is this intentional :-? ?

**Comment by scarroll32** [comment]
yes

**Comment by scarroll32** [comment]
Sorry closed by accident

The terms were taken from some service ... not the legal dept.

**Comment by marcelsalathe** [comment]
I agree, let's remove this

**Comment by scarroll32** [comment]
Closed https://github.com/crowdAI/crowdai/commit/3eecdddd06c53e7c7bed507321a7681e15a2208e
