### ISSUE TITLE
Getting Heroku error when trying to updated image and bio on account page

### ISSUE THREAD

**Issue by marcelsalathe** [crowdAI/crowdai#145]
<img width="820" alt="screen shot 2017-05-31 at 6 08 22 pm" src="https://cloud.githubusercontent.com/assets/215057/26642116/e2819bb8-462c-11e7-8a37-9bfef53139fe.png">

**Comment by scarroll32** [comment]
Couldn't replicate this. Will check again tomorrow.

**Comment by scarroll32** [comment]
OK I've replicated it. Working in it as first priority.

**Comment by scarroll32** [comment]
Closed https://github.com/crowdAI/crowdai/commit/72adaf7d0783967c515d1521dd348c588da31606
