### ISSUE TITLE
Heroku Maintenance page

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#152]
<img width="1199" alt="screen shot 2017-06-01 at 12 51 16" src="https://cloud.githubusercontent.com/assets/11340230/26676674/0fc245f4-46c9-11e7-8437-9666e0731182.png">

**Comment by scarroll32** [comment]
Closed https://github.com/crowdAI/crowdai/commit/dda7062383353cb37351c13557b9358208e4f628

**Comment by seanfcarroll** [comment]
https://github.com/crowdAI/crowdai/commit/dda7062383353cb37351c13557b9358208e4f628
