### ISSUE TITLE
There needs to be space above the footer

### ISSUE THREAD

**Issue by marcelsalathe** [crowdAI/crowdai#156]
this is a problem on all pages, which means that we simply have to add some top-padding to the footer:

<img width="451" alt="screen shot 2017-06-01 at 2 15 38 pm" src="https://cloud.githubusercontent.com/assets/215057/26679335/e6f9002a-46d4-11e7-87ab-675aedf9bdd9.png">

**Comment by scarroll32** [comment]
Related issue https://github.com/crowdAI/crowdai/issues/124

**Comment by scarroll32** [comment]
Templates with 'no-margin-top'

```
organism-footer-no-margin-top.html
template-account-settings-email-notifications.html
template-account-settings.html
template-challenges-edit-challenge-evaluation.html
template-challenges.html
template-hosts-edit-host.html
template-knowledge-base-edit-tutorial-content.html
template-knowledge-base-edit-tutorial.html
template-login-account-locked.html
template-login-resend-account-confirmation.html
template-login-unlock-account.html
template-login.html
template-sign-up.html
```

**Comment by scarroll32** [comment]
Bit of an issue with the load more bar. 

With 'no-margin-top' and paging (not OK):
<img width="1224" alt="screen shot 2017-06-01 at 15 27 58" src="https://cloud.githubusercontent.com/assets/11340230/26681909/015cc172-46df-11e7-9f05-7d2b06413db0.png">

When there is no paging bar: (OK)
<img width="1200" alt="screen shot 2017-06-01 at 15 29 20" src="https://cloud.githubusercontent.com/assets/11340230/26681971/2aeaef0a-46df-11e7-8248-d77c167eaca0.png">

If the no-margin-top is removed (not OK):
<img width="1148" alt="screen shot 2017-06-01 at 15 31 16" src="https://cloud.githubusercontent.com/assets/11340230/26682044/62eb255a-46df-11e7-9736-0821febfb41c.png">

**Comment by marcelsalathe** [comment]
I this case I think we can live without the no-margin-top, independent of whether there is a loading bar or not.

**Comment by scarroll32** [comment]
It is needed on the registration / account pages and I think some of the edit pages and is also creates a blank space between the loading bar and the footer. I have partially implemented a page-based solution for the first case but it won't work for the paging.

The easiest solution is to add a negative margin to the paging bar.

**Comment by scarroll32** [comment]
Closed https://github.com/crowdAI/crowdai/commit/030022d43811f51e9c0940dd67edc8a234b77c51
