### ISSUE TITLE
Mobile homepage rendering errors

### ISSUE THREAD

**Issue by marcelsalathe** [crowdAI/crowdai#157]
Two problems: 

1. Something is wrong with the text alignment

2. Sometimes, the font is rendered as too large.

<img width="441" alt="screen shot 2017-06-01 at 2 29 34 pm" src="https://cloud.githubusercontent.com/assets/215057/26679763/c5a269be-46d6-11e7-9692-41c0424f52d9.png">

<img width="443" alt="screen shot 2017-06-01 at 2 29 20 pm" src="https://cloud.githubusercontent.com/assets/215057/26679766/c7e61298-46d6-11e7-8149-a38a1b7c5c9f.png">

**Comment by jsnrynlds** [comment]
This is essentially the same issue as https://github.com/crowdAI/crowdai/issues/113. (Aside from the challenge headings sometimes appearing too large... I've not been able to replicate that on any browser or on my mobile.)

Looking into this.

**Comment by scarroll32** [comment]
Has been fixed & looks OK on my phone. @marcelsalathe can you confirm.
