### ISSUE TITLE
Sort Challenges by completion date 

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#160]
It would be good to sort challenges by completion date on the Challenges page.
I am not sure about the current order of rendering. But in some cases, the learning to walk challenge was not visible.

**Comment by scarroll32** [comment]
This is the sort order, based on status. I'll add in a secondary sort on created date, descending within a status.

```
default_scope { order("CASE status_cd
                          WHEN 'running' THEN 1
                          WHEN 'starting_soon' THEN 2
                          WHEN 'completed' THEN 3
                          WHEN 'cancelled' THEN 4
                          WHEN 'draft' THEN 5
                          ELSE 6
                        END, updated_at DESC") }
```

**Comment by spMohanty** [comment]
:+1:

**Comment by scarroll32** [comment]
Closed https://github.com/crowdAI/crowdai/commit/43d6a25655412ba0cd995f6e443f6c4a52c0d39e
