### ISSUE TITLE
Wrong author name on discussion forum posts

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#164]
I just noticed that in one of the posts I had made in the discussion forum, the shown author is different.

Link : https://www.crowdai.org/topics/approximate-starting-date/comments/new

<img width="1245" alt="screen shot 2017-06-01 at 20 24 34" src="https://cloud.githubusercontent.com/assets/1581312/26694651/742ee0d0-4708-11e7-8030-c1c08c32d629.png">

**Comment by scarroll32** [comment]
Closed https://github.com/crowdAI/crowdai/commit/ece68bc73b5ba1453329462b985441e1690418a9
