### ISSUE TITLE
Add support for image resizing in markdown editor ??

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#172]
Images included using markdown have pretty big and weird sizes. Ex. : https://www.crowdai.org/challenges/nips-2017-learning-to-run
(Look at the institutional logos)

Can we try to add support for `width=` or `height=` params in our markdown (like a few extended markdown flavours), or simply let atleast the admins include pure HTML ?

**Comment by scarroll32** [comment]
Any examples of a markdown flavor with something like this implemented? We can use one with the markdown renderer.

**Comment by scarroll32** [comment]
https://github.com/vmg/redcarpet/issues/487

**Comment by scarroll32** [comment]
Added, format is as below:

```
![2 steps](http://kidzinski.com/out.gif){:height="100px" width="100px"}
```

**Comment by marcelsalathe** [comment]
Does not work
<img width="611" alt="screen shot 2017-06-19 at 4 57 44 pm" src="https://user-images.githubusercontent.com/215057/27291430-7a91d8a4-5510-11e7-9c5d-8d50f3636aa1.png">

<img width="281" alt="screen shot 2017-06-19 at 4 57 28 pm" src="https://user-images.githubusercontent.com/215057/27291427-771b095c-5510-11e7-9961-00a291f5db82.png">

**Comment by scarroll32** [comment]
It's not deployed yet :-)

**Comment by scarroll32** [comment]
Closed https://github.com/crowdAI/crowdai/commit/af46b7e660956efa0ec9be068cbec770a73c3255
