### ISSUE TITLE
Challenge stats dont match

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#173]
The challenge stat says 22 submissions, but the leaderboard shows I have already made 40 entries. Shouldnt the challemnge stats reflect the sum of all the entries on the leaderboard ? (41) ?

<img width="1222" alt="screen shot 2017-06-06 at 10 11 16" src="https://cloud.githubusercontent.com/assets/1581312/26819774/a84013a8-4aa0-11e7-8f7f-3d630612d67b.png">

**Comment by scarroll32** [comment]
Stats job was disabled. Fixed https://github.com/crowdAI/crowdai/commit/bf083937281b8973a487dda9dc595ad7a0b0b2b7
