### ISSUE TITLE
Challenge Timeline in Draft Mode ?

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#185]
<img width="1268" alt="screen shot 2017-06-15 at 22 26 51" src="https://user-images.githubusercontent.com/1581312/27200402-d7903716-5219-11e7-90fb-c39f6fe6db2e.png">

I see this on the NIPS Learning to Run challenge at the moment.
Should the 20 days left part be there in the 1`starting soon` mode ?

**Comment by scarroll32** [comment]
I've changed the start / end dates to today (June 16) and ending at 17:30 on September 23rd (a Friday), as discussed. We can modify later if needed.
