### ISSUE TITLE
Prizes can't be edited

### ISSUE THREAD

**Issue by marcelsalathe** [crowdAI/crowdai#189]
Shows up empty in admin mode, even though there is content in public view mode:

<img width="705" alt="screen shot 2017-06-19 at 7 36 30 am" src="https://user-images.githubusercontent.com/215057/27270968-2dcd7986-54c2-11e7-9664-342f4f2bbf50.png">

**Comment by scarroll32** [comment]
Closed https://github.com/crowdAI/crowdai/commit/06b9bdf880aaf99a8171cb3e9a2cc77dd129035c
