### ISSUE TITLE
Session expires *really* soon ?

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#194]
:'(
I have been getting a lot of these session expired error messages, which forces me to sign in again.

**Comment by scarroll32** [comment]
I think the default is 15 mins...

As discussed it will be set to 24 hrs.

**Comment by scarroll32** [comment]
Not yet pushed, but done: https://github.com/crowdAI/crowdai/commit/e44c25d8f6bf71b68f5259b8acdd3af32fef9b42

**Comment by scarroll32** [comment]
Deployed

**Comment by scarroll32** [comment]
Duplicate https://github.com/crowdAI/crowdai/issues/246
