### ISSUE TITLE
Cannot unheart challenge

### ISSUE THREAD

**Issue by marcelsalathe** [crowdAI/crowdai#197]
Once I've hearted the challenge, I cannot undo it

**Comment by scarroll32** [comment]
Yes that's the intended behaviour. Do you want to change it?

**Comment by scarroll32** [comment]
yes

**Comment by scarroll32** [comment]
https://github.com/crowdAI/crowdai/commit/55a1c60fc666cd91ef9c41464cd2df6f9a95ad97

**Comment by scarroll32** [comment]
Fixed
