### ISSUE TITLE
Buttons on the forums don't seem to have the proper classes

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#20]
As you can see in this image, the buttons are not visually distinguishable from the rest of the text in the forum posts.
I think it should look more like the red button (that I created by simply modifying the markup to add `btn btn-primary` as classes) to make it more intuitive to use.
![screen shot 2016-11-07 at 1 22 16 am](https://cloud.githubusercontent.com/assets/1581312/20043198/f8922f26-a488-11e6-82fc-49d716176112.png)

**Comment by scarroll32** [comment]
That was intentional, but of course they can be changed (it does go red on a hover). I think we should do (or ask a designer) to do a full design review as there are many parts that need some more thought. Then the whole site can be updated in one go.

**Comment by scarroll32** [comment]
Closed https://github.com/crowdAI/crowdai/pull/22
