### ISSUE TITLE
TOS has wrong numbering

### ISSUE THREAD

**Issue by marcelsalathe** [crowdAI/crowdai#201]
<img width="721" alt="screen shot 2017-06-20 at 10 26 21 am" src="https://user-images.githubusercontent.com/215057/27323750-f8323046-55a2-11e7-90b5-df04ec7b3902.png">

**Comment by scarroll32** [comment]
Fixed(not deployed) https://github.com/crowdAI/crowdai/pull/204/commits/4a1f28695b2e41c8e8c1c9f05393e877767ae244

**Comment by scarroll32** [comment]
Closed
