### ISSUE TITLE
(Social) media links don't work

### ISSUE THREAD

**Issue by marcelsalathe** [crowdAI/crowdai#202]
All (social) media links here (Twitter, GitHub, etc.) go nowhere.

<img width="533" alt="screen shot 2017-06-20 at 10 49 15 am" src="https://user-images.githubusercontent.com/215057/27324703-539f43da-55a6-11e7-9a8e-0417e67cc9c2.png">

**Comment by marcelsalathe** [comment]
Looking at spMohanty's data, I can see that he didn't add any links at all - so why are they shown? I also noticed, when filing issue #203, that when I add one URL (e.g. for GitHub), suddenly all icons are shown, even though the others go nowhere...

**Comment by scarroll32** [comment]
Fixed (not deployed) https://github.com/crowdAI/crowdai/commit/3fb922a9272e03dadc61dc91515895544f6c6838

**Comment by scarroll32** [comment]
Closed
