### ISSUE TITLE
We suggest invalid URLs

### ISSUE THREAD

**Issue by marcelsalathe** [crowdAI/crowdai#203]
What we show in the form:

<img width="423" alt="screen shot 2017-06-20 at 10 54 15 am" src="https://user-images.githubusercontent.com/215057/27324863-d8f6cd0a-55a6-11e7-8441-ee6be6aabc76.png">

(Btw, this is wrong, since the .com is missing. For the argument, I assume the .com is there, but please fix)

What happens when I add such a URL:

<img width="526" alt="screen shot 2017-06-20 at 10 53 05 am" src="https://user-images.githubusercontent.com/215057/27324837-bd65c17c-55a6-11e7-8176-6f62a7e77213.png">

If we require http:// or https://, we should correspondingly show it in the form fields (or alternatively add it automatically if it is not here, which would be my suggested solution).

Also, the ugly styling of error message needs to be fixed (I think Jason provided us with a styling for error messages?)

**Comment by seanfcarroll** [comment]
https://github.com/crowdAI/crowdai/issues/150

**Comment by scarroll32** [comment]
Related issue https://github.com/crowdAI/crowdai/issues/150

**Comment by scarroll32** [comment]
> Also, the ugly styling of error message needs to be fixed (I think Jason provided us with a styling for error messages?)

The mockup was produced but we are waiting for the actual css. I'll follow up.

**Comment by scarroll32** [comment]
Styling issue https://github.com/crowdAI/crowdai/issues/133

**Comment by scarroll32** [comment]
Fixes missing .com (not deployed) https://github.com/crowdAI/crowdai/pull/204/commits/c12fa1b143fc5d2d023df7a303f1e1ae4f607928

**Comment by scarroll32** [comment]
Fixed https://github.com/crowdAI/crowdai/pull/204/commits/1116c15be3fc1997549adfdd219ad7b40d4123ab

**Comment by scarroll32** [comment]
Closed
