### ISSUE TITLE
Submission rendering on the leaderboard

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#215]
If I click on the number of entries to expand the number of entries. It correctly shows details about both the submissions.
But if I continue clicking (or maybe double clicking) then it keeps adding more copies of the same entries over and over again.

<img width="1293" alt="screen shot 2017-06-22 at 18 09 02" src="https://user-images.githubusercontent.com/1581312/27444260-122701be-5776-11e7-874e-c718b803c594.png">

**Comment by scarroll32** [comment]
Fixed via a page reload. Additions mean the leaderboard component needs refactoring which will be done at some future date.

**Comment by scarroll32** [comment]
https://github.com/crowdAI/crowdai/commit/9f6c9cfd0402c32b9fdd9e34bfc34718f094000c
