### ISSUE TITLE
Video doesnt show in potrait view on mobile phones

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#217]
Turning the phone by 90 degrees makes the video visible again. But its not really intuitive for someone to try to turn their phone by 90degrees to know about the presence of the video.

**Comment by scarroll32** [comment]
@marcelsalathe What are your thoughts on this?

**Comment by scarroll32** [comment]
An alternative would be to have a scrollable view

**Comment by scarroll32** [comment]
@jsnrynlds  what are your thoughts on this?

**Comment by scarroll32** [comment]
Perhaps add a small play icon

**Comment by scarroll32** [comment]
Moved to the main leaderboard issue.
