### ISSUE TITLE
Display distribution of scores across the three simulations for the NIPS challenge

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#218]
the score right now is a cumulative of three different simulations.
I have a total score of 2179, but about 1100 is just from the first simulation, and I think about 600 from he second and 500 from the 3rd experiment.

I was wondering how important is it for us to be able to show for every submission the distribution of scores across all the three simulations.

A good model is the one which performs similarly across all three experiments.

I was imagining small bar charts in the modal window, showing the score distribution as a bar chart.
Do you think showing this distribution is important ? or it is unnecessary ?

**Comment by scarroll32** [comment]
Marked as high priority assuming we will do this in the next few days. Let's confirm direction asap.

**Comment by spMohanty** [comment]
Changing this to low priority as we agreed for now we can display all the three simulations gifs instead.

**Comment by scarroll32** [comment]
@spMohanty Is this still required?

**Comment by scarroll32** [comment]
Closed.
