### ISSUE TITLE
Accept animated GIFs as image uploads for challenges

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#219]
Required for OpenSNP

**Comment by spMohanty** [comment]
The uploads for the animated GIF does go through (with an Application error in the end).
But a very distorted version of the GIF turns up as the challenge image in a few seconds.

PS: If this is too much work, then we can make it a low priority issue. As I can use a static image for the Challenge picture also.

**Comment by scarroll32** [comment]
Let's go with the static for now.

**Comment by scarroll32** [comment]
@spMohanty do we still need this?

**Comment by scarroll32** [comment]
Closed.
