### ISSUE TITLE
NIPS videos don't work in modal

### ISSUE THREAD

**Issue by marcelsalathe** [crowdAI/crowdai#221]
Just a static image (Chrome)

**Comment by marcelsalathe** [comment]
Probably related to issue #216

**Comment by scarroll32** [comment]
Fixed

**Comment by spMohanty** [comment]
@seanfcarroll : Reopening this issue as it doesnt seem to have been solved.
It doesnt autoplay on my chrome on mac osx (in some/most of the times I refresh the page).

Also does not work on @ mar-muel 's chrome+osx setup.

**Comment by scarroll32** [comment]
Strange. It works on Chrome, Safari & Firefox on my laptop.

There is a short delay before it starts 1-2 seconds.

**Comment by scarroll32** [comment]
Still OK for me, but I have added some additional js to force start it when the modal is opened.

https://github.com/crowdAI/crowdai/commit/fdcd44f3caed7b22b746b5e74febc3926c0766b0

Please confirm it is working and then close this issue. @spMohanty

**Comment by spMohanty** [comment]
Works for me now. Thanks.
