### ISSUE TITLE
Dataset upload page broken

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#224]
I tried uploading a dataset file for opensnp,
and now the dataset page seems to be broken : https://www.crowdai.org/challenges/opensnp/dataset_files

Also bumping the dataset file size to 2gb will help.

**Comment by scarroll32** [comment]
There is a limit of 650MB

**Comment by scarroll32** [comment]
Limit removed. Closed. https://github.com/crowdAI/crowdai/commit/b28b32c827db69106154074213394aed14bcc91c
