### ISSUE TITLE
Better 404 pages ?

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#228]
The 404 pages are still the default rails 404 pages.

For example if you go to this link when you are not signed in as an admin : https://www.crowdai.org/admin/challenges/nips-2017-learning-to-run/submissions

Would be great to theme them too.

**Comment by scarroll32** [comment]
@marcelsalathe can ask Jason for a designed 404 page?

**Comment by marcelsalathe** [comment]
Yes, please do. @jsnrynlds could design something funny, perhaps involving the crowdAI samurAI. Some inspiration: http://www.creativebloq.com/web-design/best-404-pages-812505

**Comment by jsnrynlds** [comment]
@marcelsalathe @spMohanty @seanfcarroll 

How about something like this?
 
![crowdai_404_desktop_v1 1](https://user-images.githubusercontent.com/1162939/29517677-098000c0-866e-11e7-9731-3d3edc1742d9.png)

**Comment by spMohanty** [comment]
@jsnrynlds : ❤️ it !!!!!!!!!!!!!!!!!!!!

**Comment by scarroll32** [comment]
Perfect!!!!

**Comment by jsnrynlds** [comment]
Hi @seanfcarroll, this is built now. Can you check it works okay with the logomark SVG that's currently being used? If not I'll send over another one.

HTML:
```
<div class="center-content">
  <div class="item">
    <div style="display: flex; justify-content: center;">
      <span class="xl">4</span>
      <div class="logomark"></div>
      <span class="xl">4</span>
    </div>
    <div>
      <p class="light">Oh dear. The page you were looking for doesn’t exist.<br><br></p>
      <a class="btn btn-secondary btn-large" href="#">View challenges</a>
    </div>
  </div>
</div>
```

SCSS
```
/* 404 */

.center-content {
	display: flex;
	align-items: center;
	justify-content: center;
	height: 100vh;
	.item {
		text-align: center;
	}
	.xl {
		font-size: 240px;
		@media screen and (max-width: 768px) {
			font-size: 180px;
		}
		@media screen and (max-width: 640px) {
			font-size: 140px;
		}
		@media screen and (max-width: 480px) {
			font-size: 130px;
		}
	}
	.logomark {
		display: block;
		background: url(../img/misc/crowdai-logomark.svg) no-repeat left center;
		background-size: 256px 238px;
		width: 256px;
		height: 238px;
		margin: 0 40px;
		@media screen and (max-width: 768px) {
			width: 193px;
			height: 180px;
			background-size: 193px 180px;
			margin: 0 30px;
		}
		@media screen and (max-width: 640px) {
			width: 150px;
			height: 140px;
			background-size: 150px 140px;
			margin: 0 30px;
		}
		@media screen and (max-width: 480px) {
			width: 129px;
			height: 120px;
			background-size: 129px 120px;
			margin: 0 20px;
		}
	}
	p {
		font-size: 20px;
		margin: 3em 1em 0 1em;
		@media screen and (max-width: 768px) {
			font-size: 18px;
			margin-top: 2em;
		}
		@media screen and (max-width: 480px) {
				margin-top: 1em;
		}
	}
	.btn {
		margin-top: 10px;
		width: 240px;
	}
}
```

**Comment by jsnrynlds** [comment]
I can push this to Git if you'd prefer but guessing this is probably simpler for you.

**Comment by scarroll32** [comment]
That's great Jason, thank you very much! It should be fine like this.

**Comment by scarroll32** [comment]
Implemented, thanks @jsnrynlds !

https://github.com/crowdAI/crowdai/commit/2b5a71f376eb5d2a6acfffe366668f5fafa44255

**Comment by scarroll32** [comment]
https://www.crowdai.org/500    
https://www.crowdai.org/404    
https://www.crowdai.org/422
