### ISSUE TITLE
A "Featured Challenge" flag to have finegrained control over which challenges are displayed on front page

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#230]

**Comment by scarroll32** [comment]
I propose we add an optional "sequence" field. At present a maximum of 5 challenges are displayed on the landing page.

If this field is populated, these challenges will sort ascending by whatever is in this field.

Any other challenges will sort by the existing sort order:

```
  default_scope { order("CASE status_cd
                          WHEN 'running' THEN 1
                          WHEN 'starting_soon' THEN 2
                          WHEN 'completed' THEN 3
                          WHEN 'cancelled' THEN 4
                          WHEN 'draft' THEN 5
                          ELSE 6
                        END, created_at DESC") }
```

@spMohanty your thoughts?

**Comment by spMohanty** [comment]
Sounds great to me !!

**Comment by scarroll32** [comment]
Implemented https://github.com/crowdAI/crowdai/commit/124da205279721e5686fa4bf6f943d34ea1b437c

**Comment by scarroll32** [comment]
Added. The Featured Sequence is a higher level sort, and defaults to zero. The higher the number the higher the challenge in the list.

<img width="511" alt="screen shot 2017-07-31 at 15 49 30" src="https://user-images.githubusercontent.com/11340230/28780684-f42aeb70-7607-11e7-9846-738227cd8506.png">
