### ISSUE TITLE
Log in form - "Remember me" checkbox partly hidden on iOS 

### ISSUE THREAD

**Issue by Boris-c** [crowdAI/crowdai#231]
![img_6304](https://user-images.githubusercontent.com/7315069/27688370-a0e791b6-5cda-11e7-96a6-ba743dd73066.PNG)

**Comment by scarroll32** [comment]
Jason, could you please review this. @jsnrynlds

**Comment by jsnrynlds** [comment]
Hi @seanfcarroll – is this only happening to the checkbox on the login page?

**Comment by scarroll32** [comment]
@jsnrynlds it seems to be happening in other places, see the attached screenshot from the challenges edit page (on iOS).
![img_6964](https://user-images.githubusercontent.com/11340230/27734551-8a0edfdc-5d9b-11e7-9c39-35b65b21b2d4.PNG)

**Comment by jsnrynlds** [comment]
Not ignoring this, just struggling to find what's causing it...

**Comment by marcelsalathe** [comment]
Why don't we copy the CSS properties from openfood.ch where we have the same checkbox on the login page, and where we don't seem to have that problem?

**Comment by scarroll32** [comment]
The issue only appears on a physical device, not in Safari or Chrome dev tools

<img width="305" alt="screen shot 2017-09-18 at 11 41 50" src="https://user-images.githubusercontent.com/11340230/30536570-99f6fdd0-9c66-11e7-8a9f-0eb2e85fffa9.png">

<img width="421" alt="screen shot 2017-09-18 at 11 43 49" src="https://user-images.githubusercontent.com/11340230/30536584-aac59892-9c66-11e7-98bb-5bf790fb4a46.png">

**Comment by jsnrynlds** [comment]
I wonder if this may be caused by `@include scale(1.3848);`. I'll look into this at some point this week.

**Comment by jsnrynlds** [comment]
@seanfcarroll Is this still occurring in iOS? I think we previously removed `transform: scale(1.3848)` and it's fine on Android now.

**Comment by scarroll32** [comment]
Looking good. Thanks Jason.
