### ISSUE TITLE
Open links in rendered markdown in a new tab

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#235]

**Comment by scarroll32** [comment]
https://www.thesitewizard.com/html-tutorial/open-links-in-new-window-or-tab.shtml

**Comment by scarroll32** [comment]
This is probably best applied on a per link basis. It has now been implemented via the link button, and may also be manually entered like this:

```
[ Google ](https://www.google.com){:target='_blank'}
```

It won't be applied to existing links.

**Comment by scarroll32** [comment]
Always open links in a new tab
