### ISSUE TITLE
Render comments associated with a submission

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#238]
Corresponding issue in the python client : https://github.com/crowdAI/crowdai-client-py/issues/14

**Comment by scarroll32** [comment]
Needs some more detail. Let's discuss.

**Comment by scarroll32** [comment]
Added on the video modal under the video.
<img width="1004" alt="screen shot 2017-08-15 at 12 22 11" src="https://user-images.githubusercontent.com/11340230/29312213-a8480f86-81b4-11e7-8368-853f0d8dee27.png">


Note that there are some records with broken markdown.

We need to circle back at some point and do some replanning on the leaderboard enhancements, perhaps in conjunction with the API cleanup after NIPS.

**Comment by scarroll32** [comment]
https://github.com/crowdAI/crowdai/commit/7076496bf8e8a561c3254ee21acae3eb4ddca99c
