### ISSUE TITLE
Leaderboard videos not rendering in Learning to Walk challenge

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#239]
Link : https://www.crowdai.org/challenges/learning-how-to-walk/leaderboards

Update: Maybe the videos just all load after a long delay. But this still needs to be investigated.

**Comment by AdamStelmaszczyk** [comment]
+1, they load after a very long delay.

It's because these are MP4 files, sometimes even bigger than 1 MB.

![requests](http://i.imgur.com/gLaId04.png)

To make it faster, one could use e.g. much smaller GIF files instead.

**Comment by scarroll32** [comment]
Thank you for the insight @AdamStelmaszczyk 

@spMohanty can we scale these down some more?

**Comment by marcelsalathe** [comment]
They do indeed take forever. As the leaderboards are growing rapidly now, we should probably start showing just the top X (say 20), and load more on demand (i.e. using the show more button we have on the homepage).

**Comment by scarroll32** [comment]
@spMohanty FYI on the more link for the Leaderboard.

**Comment by scarroll32** [comment]
https://github.com/embedly/player.js

http://playerjs.io/scroll.html

**Comment by ctmakro** [comment]
GIF's are smaller. There's another problem playing MP4s, that my videocard will start to burn whenever I load the leaderboard page. 

A solution would be to load the videos(or GIFs) on-demand, i.e. page should not start download unless user scroll down to see it.

**Comment by ctmakro** [comment]
might also consider: https://appelsiini.net/projects/lazyload/
```html
<script src="jquery.js"></script>
<script src="jquery.lazyload.js"></script>
<img class="lazy" data-original="img/example.jpg" width="640" height="480">
```
```js
$(function() {
    $("img.lazy").lazyload();
});
```
should apply to more than images.

**Comment by AdamStelmaszczyk** [comment]
A quick and easy win would be to not display videos, but links to download them.

I believe now lots of people (including me) sees something similar to:

![image](https://user-images.githubusercontent.com/733573/29498824-d6125360-8603-11e7-9d75-4e53f460806a.png)

**Comment by scarroll32** [comment]
Leaderboard paging has been implemented (25 entries) and the videos are not playing on the leaderboard for now. They still play on the modal window.

**Comment by spMohanty** [comment]
@seanfcarroll : Depending on the performance, I would like to have at least the videos from say the top-5 submissions running on page load. 

It is easy to miss that these are videos, and also, given a broad overview of (at least) a few good different policies learn by just loading the leaderboard, was something both participants and externals have loved about the Learning to Walk and the Learning to Run challenge.

@marcelsalathe @seanfcarroll : What do you think ?

**Comment by scarroll32** [comment]
Yes definitely, the previous code for running the videos based on what was viewable had problems and has been inactived, but I will shortly implement a new solution using a different library.

**Comment by scarroll32** [comment]
Reactivated.

I think the original problems are offset by the paging. Many of the videos are still close to 1MB.

<img width="1190" alt="screen shot 2017-08-25 at 20 45 56" src="https://user-images.githubusercontent.com/11340230/29728041-a09313f6-89d6-11e7-9fe4-f5122b9fb6e7.png">


Pull requests welcome.

@spMohanty let's work on this together.
