### ISSUE TITLE
Automated triggering of grading upon submission

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#24]
I think it would really be convenient for participants if the grading of their submission is automatically triggered upon submission. Given how much work goes into a particular submission, its a pain to wait for a manual trigger :'(

**Comment by scarroll32** [comment]
There is already a checkbox at the challenge level, and this was previously running, but I commented it out for some reason. I'll check into it.

**Comment by scarroll32** [comment]
Closed https://github.com/crowdAI/crowdai/pull/32
