### ISSUE TITLE
Devise forms looking weird

### ISSUE THREAD

**Issue by yannis** [crowdAI/crowdai#242]
Good example is this one: https://www.crowdai.org/participants/password/new
Same for this: https://www.crowdai.org/participants/password/edit

![image](https://user-images.githubusercontent.com/30563/27829206-a098720e-60c0-11e7-9185-c6776c54e716.png)

**Comment by scarroll32** [comment]
Looks like there were no templates in the design, but I'll adapt some of the other forms.

**Comment by scarroll32** [comment]
<img width="781" alt="screen shot 2017-07-31 at 09 42 27" src="https://user-images.githubusercontent.com/11340230/28767591-971e0cec-75d4-11e7-9f07-89195b7af41f.png">

**Comment by scarroll32** [comment]
<img width="664" alt="screen shot 2017-07-31 at 10 00 41" src="https://user-images.githubusercontent.com/11340230/28768231-233836ce-75d7-11e7-9a1a-9e82cdab800f.png">
<img width="653" alt="screen shot 2017-07-31 at 10 00 34" src="https://user-images.githubusercontent.com/11340230/28768230-233821b6-75d7-11e7-92fd-c2cf96de5261.png">

**Comment by scarroll32** [comment]
Fixed https://github.com/crowdAI/crowdai/commit/c43f4aac24e83715b89add9c167e2b756044ab6a
