### ISSUE TITLE
500 after middle button clicking on a video in leaderboard

### ISSUE THREAD

**Issue by AdamStelmaszczyk** [crowdAI/crowdai#243]
After middle button clicking (which opens a link in a new tab) on any video image on [leaderboard page](https://www.crowdai.org/challenges/nips-2017-learning-to-run/leaderboards), 500 "We're sorry, but something went wrong" page always comes up, [example](https://www.crowdai.org/challenges/nips-2017-learning-to-run/leaderboards/video_modal?submission_id=493).

Left button clicking works (because it only opens the modal window, no URL change).

**Comment by marcelsalathe** [comment]
Is this still an issue? Which middle button do you mean?

**Comment by AdamStelmaszczyk** [comment]
I just tried middle button clicking on video, yes, it's still an issue.

With mouses with roll and 2 buttons, pressing the roll acts as a middle button click: 
https://teamlife.byu.edu/Portals/41/images/tips/mouse-middle-click.png

**Comment by scarroll32** [comment]
The middle button opens the link in a new tab. This doesn't really work for a modal, which should be attached the to parent. New behaviour: middle button opens the leaderboard in a new tab. Existing right click on the video opens the modal.

Thanks for the contribution @AdamStelmaszczyk
