### ISSUE TITLE
URIs for participants should include slugs instead of record ids.

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#245]
A current participant profile page url looks like : https://www.crowdai.org/participants/7

When ideally it should look like : https://www.crowdai.org/participants/spmohanty

**Comment by scarroll32** [comment]
Implemented but cannot push to production due to Heroku issue (logged).

https://status.heroku.com/incidents/1236

https://github.com/crowdAI/crowdai/commit/ad811c58aae9c462618b1e7ea03bf7d73dbc05e8

**Comment by scarroll32** [comment]
Closed
