### ISSUE TITLE
CrowdAI Session expires too soon

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#246]
The CrowdAI session expires really soon in case of inactivity, forcing the users to sign in again.
I would guess it expires in about 20-30mins of inactivity.

We should allow logins to persist for at least 24 hours of inactivity.

**Comment by scarroll32** [comment]
Related https://github.com/crowdAI/crowdai/commit/dc219c912d735b4fb24bde8e10e5041c33a467be

**Comment by scarroll32** [comment]
Released https://github.com/crowdAI/crowdai/commit/a41d80ee3725ec6cf359f88d91e8760277adb18f

**Comment by scarroll32** [comment]
Try it out now & close this if OK. Cheers from down under.
