### ISSUE TITLE
Text change on "Host Challenge" page

### ISSUE THREAD

**Issue by marcelsalathe** [crowdAI/crowdai#248]
> We work with organizations with open data, sets including educational institutions, NGOs and private companies.

needs to be 

> We work with organizations with open data sets including educational institutions, NGOs and private companies.

Also, I suggest changing

> A not-for-profit entity, crowdAI is part of EPFL, one of the world’s leading technical universities.

to

> A not-for-profit entity, crowdAI is developed at EPFL, one of the world’s leading technical universities.

**Comment by scarroll32** [comment]
Deployed https://github.com/crowdAI/crowdai/commit/b0e84cb906c515a1574d26d95176c0eb08922555
