### ISSUE TITLE
Can't start a new topic on the forum

### ISSUE THREAD

**Issue by AdamStelmaszczyk** [crowdAI/crowdai#249]
I'm logged in. In the `Discussion` tab, I click `NEW TOPIC` button:

![screen](https://user-images.githubusercontent.com/733573/28442314-04c8a05e-6db0-11e7-80c9-e82cd43f4305.png)

Page reloads with error "You are not authorised to access this page" on the top:

![error](https://user-images.githubusercontent.com/733573/28442378-54ba8276-6db0-11e7-9229-37c03bd1fae7.png)

I'm not the only one with this issue, [here](https://www.crowdai.org/topics/observation-vector-4bb70152-97dd-4565-9f25-89a18b05e92e/comments/new#vote-link-comment-202) another user states that he also doesn't have permissions to create a topic.

cc @kidzik

**Comment by scarroll32** [comment]
Looks good.

**Comment by scarroll32** [comment]
This is deployed now https://github.com/crowdAI/crowdai/commit/29c0272edac0eb6d696a1d8e911c697f8b3b0b33

@AdamStelmaszczyk Please try again and close this issue if it is working for you.

@bkDJ Thanks for your help.

**Comment by AdamStelmaszczyk** [comment]
Thank you, works now.
