### ISSUE TITLE
Cannot find API key

### ISSUE THREAD

**Issue by ShangtongZhang** [crowdAI/crowdai#251]
How can I find my API key?
I went to the profile page, then it asks me to edit my profile. There is not API key generator in that edit page. Then after saving, there is `API key` under my name, but it's empty? Did I miss something?

**Comment by scarroll32** [comment]
Hi Shangtong Zhang,

There is a **cyclic arrow symbol** next to the API key field, which you can press to regen your key. I have regenerated it for you already, but feel free to try it out. Please close this issue if it is now solved and good luck on your challenge submissions!

Regards,
Sean

<img width="607" alt="screen shot 2017-07-22 at 09 26 53" src="https://user-images.githubusercontent.com/11340230/28485877-1e4b353a-6ec0-11e7-8aca-de267268557e.png">

**Comment by ShangtongZhang** [comment]
Thanks for your help with this! It works now. I got the API key. But I believe there may be some bug, because I never see the recycle arrow in any page, even now.
