### ISSUE TITLE
Trying to perform an action that requires an account should redirect to sign-in page

### ISSUE THREAD

**Issue by bkDJ** [crowdAI/crowdai#252]
Example: When "New Topic" is clicked in the "Discussion" tab of an ongoing challenge, it redirects to the home page with a "You are not authorised to access this page." flash. Instead, it should redirect to the sign-in page with a "Please sign in to continue" flash.

**Comment by scarroll32** [comment]
Fixed by https://github.com/crowdAI/crowdai/commit/342ddb78cd4083cf369127bdbdfc2b1f02551035

**Comment by scarroll32** [comment]
Closed
