### ISSUE TITLE
I'd like to be able to heart a conversation in mobile

### ISSUE THREAD

**Issue by marcelsalathe** [crowdAI/crowdai#257]
I can't at the moment (I can heart challenges, but I think hearting conversations is more important). May need some design help from @jsnrynlds 

Desktop:
<img width="884" alt="screen shot 2017-07-31 at 2 41 46 pm" src="https://user-images.githubusercontent.com/215057/28778152-6e740448-75fe-11e7-9bda-336cb82c14ab.png">

mobile:
<img width="395" alt="screen shot 2017-07-31 at 2 41 32 pm" src="https://user-images.githubusercontent.com/215057/28778160-729385ee-75fe-11e7-9983-05ef90080c39.png">

**Comment by scarroll32** [comment]
The heart disappears from the template (template-challenge-discussion-topic.html) when viewed as mobile. @jsnrynlds let's discuss when you have time.

<img width="397" alt="screen shot 2017-07-31 at 15 55 26" src="https://user-images.githubusercontent.com/11340230/28780992-e523a2c4-7608-11e7-90e4-be2088346a25.png">

**Comment by jsnrynlds** [comment]
@seanfcarroll @marcelsalathe is it possible to move the position of the button within the HTML so it's after the `.comment` div? If so, then we can replace the `.discussion-topic, .discussion-comment` classes with the following (and the button will appear after the comment):
```

.discussion-topic,
.discussion-comment {
	display: block;
	width: 100%;
	padding: 36px 0 30px 0;
	border-bottom: 1px solid $color-grey-10;
	&:last-of-type {
		border-bottom: none;
	}
	@media screen and (max-width: 640px) {
		padding: 28px 0 24px 0;
	}
	@media screen and (max-width: 480px) {
		padding: 28px 0 20px 0;
	}	
	.pic {
		float: left;
		height: 80px;
		width: 80px;
		margin-right: 20px;
		@media screen and (max-width: 800px) {
			height: 60px;
			width: 60px;
			margin-right: 16px;
		}
		@media screen and (max-width: 640px) {
			height: 48px;
			width: 48px;
			margin-right: 16px;
		}
		@media screen and (max-width: 480px) {
			height: 36px;
			width: 36px;
			margin-right: 12px;
		}
		img {
			@include border-radius(2px);
		}
	}
	.topic-content,
	form.add-comment {
		position: relative;
		float: left;
		width: calc(100% - 100px);
		@media screen and (max-width: 800px) {
			width: calc(100% - 76px);
		}
		@media screen and (max-width: 640px) {
			width: calc(100% - 64px);
		}
		@media screen and (max-width: 480px) {
			width: calc(100% - 48px);
		}
		.details {
			color: $color-grey-54;
			font-size: 14px;
			margin-top: 4px;
		}
		.comment p {
			font-size: 16px;
			line-height: 22px;
			max-width: 600px;
			margin-top: 14px;
			overflow: hidden;

			@media screen and (max-width: 640px) {
				font-size: 15px;
				line-height: 20px;
			}
		}
		.btn {
			position: absolute;
			top: 0;
			right: 0;
			@media screen and (max-width: 800px) {
				position: relative;
				margin-top: 12px;
			}
		}
	}
	&:after {
      clear: both;
      display: table;
      content: " ";
    }
}
```

**Comment by jsnrynlds** [comment]
The only additional code here is within `.btn`:
```
@media screen and (max-width: 800px) {
	position: relative;
	margin-top: 12px;
}
```

**Comment by scarroll32** [comment]
Implemented https://github.com/crowdAI/crowdai/commit/97711c8753a9c3e9126dba1f603687c7723c8ea5

**Comment by scarroll32** [comment]
This is how it looks on my phone (iphone 6)

![img_7755](https://user-images.githubusercontent.com/11340230/29526023-c145f6e4-8694-11e7-8462-f5fbb5a93379.PNG)

**Comment by jsnrynlds** [comment]
@seanfcarroll Hmmm, that's not what I was seeing. Did you change the HTML, moving the button so it's after the `.comment` div?

**Comment by scarroll32** [comment]
Not intentionally ... let's discuss tomorrow
