### ISSUE TITLE
Participants who Heart challenges to be added to participant count

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#259]
The participant_count is based on the **participant_challenges** count view, which does not include participants who have hearted the challenge but not otherwise contributed to it.

- Add hearting participants to the count

In effect, Heart can be treated as "follows"

**Comment by scarroll32** [comment]
An opt-out of emails for a hearted challenge will need to be separately developed.

**Comment by scarroll32** [comment]
**Update**

- Participants = people who participate
- Followers = participants + anyone else who is interest to follow the challenge (by hearting it)
- Emails go to followers

**Comment by marcelsalathe** [comment]
I would not treat the hearts as participants. Yes, I agree a heart means to follow, but participants are those who want to participate (by downloading the data or other files), while someone who hearts a challenge simply says "I like this, keep me in the loop"). 

i.e. 
participants = people who participate
followers = participants + anyone else who is interested to follow the challenge (by hearting it)

And emails go to followers, as per issue https://github.com/crowdAI/crowdai/issues/75#issuecomment-285308833

so no separate opt out is needed

**Comment by scarroll32** [comment]
Proposed changes

- participants: users who download files, made comments or submitted
- follows: participants + users who 'heart' the challenge or any topics/ comments. Can be opted out.

**Changes**
- Heart at challenge level to be replaced by another symbol ("following")
- Heart at Topic, Comment and Tutorial level remains the same but doesn't affect emails
- Any participant (downloaded files, made comment or submitted) will automatically follow the challenge
- Any user who hearts a comment or topic in the forums also becomes a follower
- Follower button can be toggled off, and user will no longer receive emails for this challenge


This is different to:
> followers = participants + anyone else who is interested to follow the challenge (by hearting it)

As it allows participants to opt out of emails from the challenge

@marcelsalathe  your thoughts?

**Comment by seanfcarroll** [comment]
Refer https://github.com/crowdAI/crowdai/issues/75

**Comment by scarroll32** [comment]
Covered by https://github.com/crowdAI/crowdai/issues/75
