### ISSUE TITLE
Long text breaks formatting in discussions

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#277]
There are 2 places it is broken in:

- long participant name combined with "About 10 hours ago" text
- long discussion topic

<img width="1287" alt="screen shot 2017-08-14 at 10 14 56" src="https://user-images.githubusercontent.com/11340230/29263572-bcd042f6-80d9-11e7-81a6-302069963dea.png">

**Comment by jsnrynlds** [comment]
@seanfcarroll I managed to fix this with flex, unfortunately the changes are having undesirable effects elsewhere. Instead, if you apply `max-width: 60%` to `.details` in `.list-topics` that should work.

```
.list-topics {
	margin-top: 16px;

	li {
		&:first-of-type {
			border-top: 1px solid $color-grey-10;
		}

		.like-count {
			margin-right: 9px;

			@media screen and (max-width: 800px) {
				margin-right: 5px;
			}
		}

		.pic {
			height: 48px;
			width: 48px;
			margin-right: 16px;

			@media screen and (max-width: 640px) {
				height: 36px;
				width: 36px;
				margin-right: 12px;
			}
		}

		.details {
			max-width: 60%;
			.user {
				color: $color-grey-54;
				font-size: 14px;
				margin-top: 2px;
			}
		}

		.stats {
			width: 300px;
			margin-top: 1px;

			a {
				color: $color-accent-dark;
				&:hover {
					border-bottom: 1px solid $color-accent;
				}
			}

			@media screen and (max-width: 1024px) {
				display: none;
			}	
		}
	}
}
```

**Comment by scarroll32** [comment]
Implemented https://github.com/crowdAI/crowdai/commit/a0906c6834d1f0cf4ea74f80f30bb91971d583ec

**Comment by scarroll32** [comment]
Closed
