### ISSUE TITLE
Discussions read indicator

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#278]
An indicator should be present on the discussions pages to show if the currently logged in user has already read the discussion topic. To be discussed with Jason.

**Comment by jsnrynlds** [comment]
@seanfcarroll I wonder if rather than add anything here, we simply unbolden the title for discussions that have been read (as is common in email apps)?

**Comment by scarroll32** [comment]
Sounds reasonable to me. @spMohanty @marcelsalathe your thoughts?

**Comment by scarroll32** [comment]
Will require persisting which posts a user has viewed.

**Comment by scarroll32** [comment]
@jsnrynlds I wonder if the simplest way to to do this is to use the visited attribute in css. Of course if the browser cache is deleted it with be lost, but I think that is OK. I'll do a PR on the templates repo

**Comment by jsnrynlds** [comment]
Hi @seanfcarroll, that sounds like a nice, simple solution. I've added this to `_typography.scss`:

```
.list-topics h5 {
  &:visited {
    font-weight: 400;
  }
}
```

**Comment by scarroll32** [comment]
Implemented.
