### ISSUE TITLE
Comments missing from consolidated emails

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#288]
Also add the link to change subscription options.

**Comment by marcelsalathe** [comment]
I would also change the submission links - at the moment, I am getting an email that says multiple times "NIPS 2017: Learning to Run by eatnow. " But all the links go to the same page. So perhaps, what I would do instead is to just write:

**Submissions Summary**
The challenge NIPS 2017: Learning to Run has received 13 new submissions. 
The challenge OpenSNP Height Prediction has received 1 new submission.

Then, for the discussion summary, I would do something like this (this is how Basecamp does it):
<img width="612" alt="screen shot 2017-08-19 at 10 54 14 am" src="https://user-images.githubusercontent.com/215057/29485120-cc30dd22-84cc-11e7-8439-f8493411d86f.png">

**Comment by scarroll32** [comment]
The basecamp approach looks good, but there are a couple of considerations for crowdAI.

- It is possible to print the comment content in the email, but the comments are often very long. To truncate them is also possible, but as they are rendered html generated from markdown, truncating would require either finding the body text within a markdown tag, then re-rendering, or parsing the rendered html to remove some content but still keep a valid closing tag. Neither approach would be trivial to implement.

- An alternative would be to simple print the comment topic, which is plain text. Code could be implemented to summarise all comments against the topic, with the comment topic and participant names as links, as below:

### Comments Summary

Comments were made on the  **how to manage free text quiz submissions?** discussion topic by **bill**, **user99** and **another user**.

A Comment was made on the  **a different topic** discussion topic by **bill**.

**Comment by marcelsalathe** [comment]
How about we render the HTML, strip the rags using https://apidock.com/rails/ActionView/Helpers/SanitizeHelper/strip_tags and then truncate?

**Comment by scarroll32** [comment]
I believe this approach will lead to very long emails, as well as broken-looking text when mixed formatting elements are used. But OK, will implement.

**Comment by marcelsalathe** [comment]
I think if we limit ourselves to less text than the Basecamp example, we should be fine. How about we implement a first version and then review before pushing live?

**Comment by scarroll32** [comment]
Yes no problem. (Need to also add the "change email settings" link)

**Comment by scarroll32** [comment]
Implemented.
