### ISSUE TITLE
Quotes not rendering correctly in discussion forum

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#289]

**Comment by scarroll32** [comment]
Hi Jason,

We need to have some way to represent quoted text. Could you produce some css for the ```<blockquote>``` tag?

For a live example, see the last comment made here (by me) https://www.crowdai.org/topics/is-the-deadline-august-13th-or-september-21st/comments/new

It has rendered the original comment with a blockquote, but it is not obvious. eg:

```
<div class="comment comment" id="comment_352">      <p></p><blockquote>
  <p>Hi @gershom,
Indeed the deadline for the challenge is in 43 days on Sept 21st.</p>
</blockquote>

<p>But August 13th is the date when the AWS credits will be given away to the top 100 participants on the leaderboard (excluding the Admin submissions)</p>

<p>Cheers,
Mohanty</p>

<p>Thank you Mohanty.</p>
<p></p>
    </div>
```

**Comment by jsnrynlds** [comment]
Hi @seanfcarroll  – here you go:
```
blockquote {
	margin-top: 14px;
	color: $color-grey-54;
	font-style: italic;	
}
```

It looks like there's an additional margin being added to .comment... this should be smaller but not sure what's causing it. I think it's maybe being added on by:
```
p {
    display: block;
    -webkit-margin-before: 1em;
    -webkit-margin-after: 1em;
    -webkit-margin-start: 0px;
    -webkit-margin-end: 0px;
}
```
... but don't want to break anything else by resetting this.

**Comment by scarroll32** [comment]
Hi Jason, that's great, thanks for that.  

Perhaps we can at some point do a review of the various hacks that have been added to the css, and maybe redesign some of them?

**Comment by jsnrynlds** [comment]
Yeah, that would be good. I despair at some of the CSS now, looking back at it!

**Comment by scarroll32** [comment]
Cool ... I'd like to have a mini-planning session for new features for crowdAI very soon. Perhaps we can involve you also. I also [added](https://github.com/crowdAI/crowdai/tree/master/app/assets/stylesheets) some bits and pieces to the css, mostly kept separated in from the site.scss file. 

Would be good to refactor a little, but with the new features incorporated.

**Comment by jsnrynlds** [comment]
Sure. I think one thing it would be helpful to do (if possible) is modularise it. Bit of a nightmare going through an SCSS file that's thousands of lines long :)

**Comment by scarroll32** [comment]
Implemented. Thanks @jsnrynlds !
