### ISSUE TITLE
Styling for Media Modal 

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#292]
<img width="972" alt="screen shot 2017-08-21 at 13 34 08" src="https://user-images.githubusercontent.com/1581312/29517449-7f5c3aa0-8675-11e7-9660-62d0fb3d6cae.png">

The media modal requires styling. It can be accessed by going to [this link](https://www.crowdai.org/challenges/nips-2017-learning-to-run/leaderboards#) and cliking on one of the videos.

The features we want there are : 
* Buttons to Share the media to various social networking sites.
* Button to Download the media.
[:Edited:]
* Submission Description
* Submission Score(s)
* Other submission related metadata

cc. @jsnrynlds

**Comment by scarroll32** [comment]
Also need to consider the placement of the submission comments text, and perhaps some other submission information (score, timestamp, error messages).

**Comment by scarroll32** [comment]
Closed by #324
