### ISSUE TITLE
Add a storage layer to remove the strong dependency on S3

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#294]
An abstract storage layer will remove the strong dependency on Amazon S3 that we have right now. And also allow us to flexibly move to other storage services if required in the future.
Plus it will also help developers get started more easily, (by implementation of a configurable local storage options)

**Comment by scarroll32** [comment]
Related https://github.com/crowdAI/crowdai/issues/293

**Comment by scarroll32** [comment]
Probably best to stay with the real S3 in production, but can use something like this in the prebuilt dev env https://github.com/jubos/fake-s3

**Comment by scarroll32** [comment]
On second thoughts I think this is a bad idea ... we will potentially end up chasing differences in dev & prod environments if using a fake and it adds an new dependency.
