### ISSUE TITLE
Phantom margin above footer

### ISSUE THREAD

**Issue by jsnrynlds** [crowdAI/crowdai#295]
@seanfcarroll I've noticed in a couple of places we have whitespace appearing above the `<footer>`. If I remember correctly we had a class called `.no-margin-top` applied to the `<footer>` to avoid this on certain pages.

<img width="1886" alt="screen shot 2017-08-21 at 12 54 21" src="https://user-images.githubusercontent.com/1162939/29518079-ec815526-866f-11e7-9619-c46f6fd85621.png">

**Comment by scarroll32** [comment]
Yes I think it is a HTML issue rather than styling. I will hunt it down.

**Comment by scarroll32** [comment]
Fixed https://github.com/crowdAI/crowdai/commit/4e74852b488c0456d2af256ee3590917dde2bf09

**Comment by scarroll32** [comment]
Closed
