### ISSUE TITLE
Load more button on the leaderboard

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#296]
<img width="1474" alt="screen shot 2017-08-21 at 13 58 49" src="https://user-images.githubusercontent.com/1581312/29518280-f6782d94-8678-11e7-967d-2660161757a0.png">

The load more button on [the leaderboard](https://www.crowdai.org/challenges/nips-2017-learning-to-run/leaderboards) somehow seems a bit off to me, cant say exactly why. 

It could just be overthinking :D, but anyway wanted to pass it by @jsnrynlds just to be sure.

**Comment by scarroll32** [comment]
It's because the text "load more" is centered ... but the video thumbnail is not

**Comment by scarroll32** [comment]
I think we need a planning session ... esp on the leaderboard.

**Comment by scarroll32** [comment]
Related 

- https://github.com/crowdAI/crowdai/issues/286  
- https://github.com/crowdAI/crowdai/issues/292

**Comment by scarroll32** [comment]
@jsnrynlds What are your thoughts on this? The columns in the leaderboard will change depending on the challenge.

**Comment by scarroll32** [comment]
Closed by #324
