### ISSUE TITLE
Weird heart placement on forum (mobile)

### ISSUE THREAD

**Issue by marcelsalathe** [crowdAI/crowdai#298]
Probably a CSS issue
![img_2276](https://user-images.githubusercontent.com/215057/29759948-3e6f8fb0-8bc0-11e7-913c-e08bce20b102.PNG)

**Comment by jsnrynlds** [comment]
This is actually a HTML issue. The heart button needs to be moved to under `<div class="comment">`. I think that should fix it whilst retaining it's position at higher resolutions.

**Comment by scarroll32** [comment]
Fixed https://github.com/crowdAI/crowdai/commit/3df0ef13709848a87d7570aa499a8803fb1def55
