### ISSUE TITLE
User needs to be able to find his / her own posts

### ISSUE THREAD

**Issue by marcelsalathe** [crowdAI/crowdai#305]
probably on the profile

**Comment by marcelsalathe** [comment]
@jsnrynlds can you make a design suggestion? I think it should go between challenges and tutorials.
<img width="557" alt="screen shot 2017-09-04 at 10 19 55 am" src="https://user-images.githubusercontent.com/215057/30017744-a5bca136-915a-11e7-80f0-5304512c5847.png">

**Comment by jsnrynlds** [comment]
I think that's the perfect place for it.

**Comment by scarroll32** [comment]
Implemented https://github.com/crowdAI/crowdai/pull/308/commits/826cfade9646dacec8f8016e9905651213bf1cd4
