### ISSUE TITLE
Email preferences / email broken

### ISSUE THREAD

**Issue by marcelsalathe** [crowdAI/crowdai#314]
When I click on Email Preferences link in crowdAI digest email, I first get the message the email preferences link is invalid.
<img width="266" alt="screen shot 2017-09-20 at 6 34 22 am" src="https://user-images.githubusercontent.com/215057/30626970-c5d6fe6a-9dcd-11e7-9fb8-76fa5ee08010.png">

Then, once I log in, I get a "too many redirects" error.
<img width="416" alt="screen shot 2017-09-20 at 6 35 46 am" src="https://user-images.githubusercontent.com/215057/30627016-fcff9604-9dcd-11e7-912f-92dd6ab9143b.png">

If I manually go to the email preferences, then I cannot change them - if I save, I get an error, which itself looks like an error:
<img width="683" alt="screen shot 2017-09-20 at 6 43 05 am" src="https://user-images.githubusercontent.com/215057/30627203-21fd9e8c-9dcf-11e7-9935-b28d6b5a071e.png">

This was originally reported by an understandably frustrated user who wrote:

>Hey,
>
> The email preferences link in your daily digest isn't working. It gives a "TOO MANY REDIRECTS" error in 2 different browsers.
> 
> The "save button" on your website's email preferences directs to an error webpage (code 5 0?!)
> 
> I love what you do, but that situation is  on the ridiculous side. I recommend you sort it out before everyone reports your emails as spam :/
> 
> Have a good day!

**Comment by scarroll32** [comment]
Link issue is fixed, the 505 issue is still open. Additional tests to be written before this ticket is closed.

Strange url generated on error

<img width="1042" alt="screen shot 2017-09-20 at 08 19 16" src="https://user-images.githubusercontent.com/11340230/30629502-7bf15eda-9ddc-11e7-82a3-819e9ff80451.png">

**Comment by scarroll32** [comment]
505 issue is fixed.

**Comment by scarroll32** [comment]
Closed
