### ISSUE TITLE
crowdAI emails design request

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#319]
Have the various crowdAI emails which are sent as Mailchimp templates professionally designed. Details to be discussed with Jason.

**Comment by scarroll32** [comment]
Sean to split a crowdAI Mailchimp account off from the main account, and give Jason access.

**Comment by jsnrynlds** [comment]
Hi @seanfcarroll – do I have access to the Mailchimp account for this yet?

**Comment by scarroll32** [comment]
Hi Jason I've split the accounts, but let's have a call to discuss this at some point.

**Comment by jsnrynlds** [comment]
Thanks Sean. Can Skype tomorrow if that's good for you?

**Comment by scarroll32** [comment]
There are also some other templates that need a bit of design work (already in the Mailchimp account).

<img width="833" alt="screen shot 2018-01-11 at 15 15 36" src="https://user-images.githubusercontent.com/11340230/34829882-66a3ea8e-f6e2-11e7-9250-62c06e083307.png">

**Comment by jsnrynlds** [comment]
Hi @seanfcarroll – I finally got round to looking at these. May potentially want to look at styles when digest text is added but all-in-all think these are looking a lot tidier now. 

<img width="730" alt="screen shot 2018-01-24 at 18 13 41" src="https://user-images.githubusercontent.com/1162939/35349380-a8f02dbc-0132-11e8-958d-66d4fa148cf3.png">
