### ISSUE TITLE
Show the "N-days left" message in a more granular way when the challenge end is near 

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#320]

**Comment by scarroll32** [comment]
It currently shows in increments of hours when there is less than a day left.

I think we need to display the challenge end time somewhere

**Comment by scarroll32** [comment]
We could add the end date on the index page: instead of 2 days left we could add 'Finishing on eptember 28th 17:00 GMT", once into the last week. 

<img width="719" alt="screen shot 2017-09-26 at 12 57 49" src="https://user-images.githubusercontent.com/11340230/30856980-66f10110-a2ba-11e7-9729-34ca17fc5f30.png">

**Comment by scarroll32** [comment]
Closed 

<img width="751" alt="screen shot 2017-09-27 at 09 52 19" src="https://user-images.githubusercontent.com/11340230/30901832-9810ab60-a369-11e7-8d9c-a3180080329f.png">

**Comment by spMohanty** [comment]
Hi @seanfcarroll,

I think the ending time information would better go on the challenge page instead of the homepage.

For example here : 
<img width="1351" alt="screen shot 2017-09-27 at 10 22 22" src="https://user-images.githubusercontent.com/1581312/30903072-cb27b350-a36d-11e7-8229-c35e6e7ebff1.png">

rather than here : 
<img width="708" alt="screen shot 2017-09-27 at 10 23 19" src="https://user-images.githubusercontent.com/1581312/30903111-e9817106-a36d-11e7-8fd1-53f367b8bafa.png">

**Comment by scarroll32** [comment]
It appears there when < 1 day

Otherwise the design needs to change

**Comment by scarroll32** [comment]
<img width="872" alt="screen shot 2017-09-28 at 11 08 03" src="https://user-images.githubusercontent.com/11340230/30958463-8485305a-a43d-11e7-86b7-48ea8fe160da.png">
