### ISSUE TITLE
1 Days

### ISSUE THREAD

**Issue by marcelsalathe** [crowdAI/crowdai#323]
Thanks for fixing today. Small detail but sends subtle signals about committment to quality.
http://api.rubyonrails.org/classes/ActionView/Helpers/TextHelper.html#method-i-pluralize

<img width="206" alt="screen shot 2017-09-27 at 6 31 47 am" src="https://user-images.githubusercontent.com/215057/30895921-af955586-a34d-11e7-94a7-064d470e72c9.png">

<img width="199" alt="screen shot 2017-09-27 at 6 31 53 am" src="https://user-images.githubusercontent.com/215057/30895923-b4372ba0-a34d-11e7-9088-5f4986cd3969.png">

**Comment by scarroll32** [comment]
Fixed
