### ISSUE TITLE
Leaderboard V2

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#324]
The crowdAI leaderboard will be redesigned and rebuilt. Changes are:

- Leaderboard changes from being a modal to a full page with a shortened url and buttons to share on Facebook and Twitter
- Comments and likes are available on this full page
- Closing the page returns to the leaderboard
- A challenge-level configuration setting (eg: 1 day) tracks leaderboard rankings and shows up and down arrows on the leaderboard. eg: https://github.com/crowdAI/crowdai/issues/287
- If the logged in participant is on the leaderboard, but not in the top 10, the leaderboard will hide the intervening rows, so that the participant can see their submission without scrolling the entire leaderboard. Pressing the load more button reverts to the original leaderboard.

This issue closes the following tickets (reference for more details): 

https://github.com/crowdAI/crowdai/issues/321

https://github.com/crowdAI/crowdai/issues/322

https://github.com/crowdAI/crowdai/issues/303  

https://github.com/crowdAI/crowdai/issues/296

https://github.com/crowdAI/crowdai/issues/292

https://github.com/crowdAI/crowdai/issues/287

https://github.com/crowdAI/crowdai/issues/286

![image uploaded from ios 1](https://user-images.githubusercontent.com/11340230/30956404-815045a6-a437-11e7-8513-ab7e22488885.jpg)

![image uploaded from ios 2](https://user-images.githubusercontent.com/11340230/30956433-9ba654b8-a437-11e7-9979-f9f7271078a5.jpg)

**Comment by spMohanty** [comment]
Covers everything we discussed. 
(And I love my drawings :')) )
Lets go for it. But in any case, I think this will need some inputs from @jsnrynlds in terms of design related issues (structuring of the modals, how the arrows on the leaderboard looks like, etc)

The issue of leaderboards with no scores, and rendering by first come first serve, needs a little bit more of thought I think. I will chew upon it, and get back if I have some more insights into that.

**Comment by scarroll32** [comment]
The leaderboard with no scores - would be happy to kill this. It was discussed for the MS challenge.

**Comment by spMohanty** [comment]
@seanfcarroll : No I just meant, that the idea wasnt mature yet. It still needs some thought. But we will actually need it for both the Music challenge, and in some way for the second NIPS challenge.

**Comment by scarroll32** [comment]
@spMohanty Can we decide by Monday, as I'll be talking to Jason then. If possible I'd like to handle all the leaderboard changes together.

**Comment by scarroll32** [comment]
Will be useful https://github.com/jpmcgrath/shortener

**Comment by scarroll32** [comment]
Leaderboard with no scores removed.

**Comment by scarroll32** [comment]
This ticket should also incorporate the issue of video on mobile phones. Moved from here: https://github.com/crowdAI/crowdai/issues/217

**Comment by scarroll32** [comment]
Shortener gem is not up to date for v5 ... possible alternative method https://medium.com/@noestauffert/building-a-url-shortener-with-rails-5-ece84f59b6a3

**Comment by scarroll32** [comment]
https://github.com/nicolasbeauvais/vue-social-sharing

**Comment by spMohanty** [comment]
Thanks @seanfcarroll for pushing the Social Share features.
Heres somethings I noticed : 
* ~~The facebook share isnt working for me. This is what I see :~~
<img width="931" alt="screen shot 2018-02-20 at 16 50 46" src="https://user-images.githubusercontent.com/1581312/36434002-3ee4ae20-165e-11e8-86ef-5d3ac9286416.png">
* The `Get Link` is a bit confusing. Especially because I wasnt sure what to expect. And I kept clicking it and nothing happened. Then when I tried pasting the contents, it had indeed copied the shortened url into my clipboard. 
Maybe just renaming it to "Copy URL" like in most cases would make it more intuitive; and/or adding a small tooltip saying "Link Copied !" ?
@jsnrynlds

**Comment by scarroll32** [comment]
Facebook link is OK now.
Copy URL text changed.

I suggest we do something visual with the button when copying, and perhaps also the tooltip.

**Comment by scarroll32** [comment]
Add difference in rank from previous:

<img width="669" alt="screen shot 2018-02-20 at 17 42 45" src="https://user-images.githubusercontent.com/11340230/36436762-832450e8-1665-11e8-8dcf-dd4bde25ee75.png">

**Comment by scarroll32** [comment]
Add a configurable setting for the comparison distance

**Comment by scarroll32** [comment]
...almost!

**Comment by scarroll32** [comment]
Implemented https://github.com/crowdAI/crowdai/commit/a648d7f8673c3b0fc3e5c9358ae7e74454faf366
