### ISSUE TITLE
new time thing looks ugly on mobile

### ISSUE THREAD

**Issue by marcelsalathe** [crowdAI/crowdai#326]
<img width="394" alt="screen shot 2017-09-28 at 12 09 01 pm" src="https://user-images.githubusercontent.com/215057/30961268-ec9195dc-a445-11e7-8ad4-6931266026a9.png">

**Comment by scarroll32** [comment]
I've changed this 3 times now :-)

I'll discuss with Jason

**Comment by scarroll32** [comment]
https://github.com/crowdAI/crowdai/issues/320

**Comment by jsnrynlds** [comment]
I think we decided to change the top line to just 'Ending', then below show '6 hours left (17:00 UTC)'.

> Ending
> 6 hours left (17:00 UTC)

Can we remove the final two digits from the time so it's just XX:XX (as opposed to XX:XX:XX)?

**Comment by jsnrynlds** [comment]
I will recreate this using flexbox when I get a chance.

**Comment by scarroll32** [comment]
![screen shot 2
![screen shot 2017-10-30 at 11 44 52](https://user-images.githubusercontent.com/11340230/32166966-c6bfa0ac-bd67-11e7-8d5d-c0af8d9743a0.png)
017-10-30 at 11 38 00](https://user-images.githubusercontent.com/11340230/32166659-d9894720-bd66-11e7-9e03-77c198219c7a.png)
![screen shot 2017-10-30 at 11 39 53](https://user-images.githubusercontent.com/11340230/32166741-13cc6ab6-bd67-11e7-9e31-9ee82db24238.png)
![screen shot 2017-10-30 at 11 43 03](https://user-images.githubusercontent.com/11340230/32166884-85be7f6a-bd67-11e7-9a5c-c1fc8775f68e.png)
![screen shot 2017-10-30 at 11 44 05](https://user-images.githubusercontent.com/11340230/32166936-aabfa30c-bd67-11e7-8eb0-c8d95839264f.png)
![screen shot 2017-10-30 at 11 44 52](https://user-images.githubusercontent.com/11340230/32166983-da3691fe-bd67-11e7-9b73-ed6a82b1eb75.png)

**Comment by scarroll32** [comment]
Implemented
