### ISSUE TITLE
CSS issues in forum

### ISSUE THREAD

**Issue by marcelsalathe** [crowdAI/crowdai#328]
<img width="321" alt="screen shot 2017-09-28 at 8 10 10 pm" src="https://user-images.githubusercontent.com/215057/30982892-146a2d6a-a489-11e7-8f4e-20e803123790.png">

**Comment by scarroll32** [comment]
Can you add a link to the forum post?

**Comment by marcelsalathe** [comment]
https://www.crowdai.org/challenges/opensnp-height-prediction/topics

**Comment by scarroll32** [comment]
Related issue https://github.com/crowdAI/crowdai/issues/277

**Comment by marcelsalathe** [comment]
Yes, let's escalate to high priority, as a user with a long name is really breaking parts of the website.

**Comment by jsnrynlds** [comment]
I can't get this issue to replicate on Chrome or Safari on my Mac :/

I will rebuild this using flexbox, but think it looks a bit odd due to the length of some of the _last comment_ info. Wondering if we really need the username and could just keep the time/date.

**Comment by scarroll32** [comment]
What about putting the username on it's own line?

Otherwise I am OK with it. @marcelsalathe ?

**Comment by jsnrynlds** [comment]
> This needs to have a fixed width so that the columns lines-up but because of the length of some names, even if I rebuild it, we'll have to increase its width. An alternative to this could be to '...' a username after say 8 characters or so.

**Comment by jsnrynlds** [comment]
@seanfcarroll I'd avoid putting it on another line as it'll look a bit messy.

**Comment by scarroll32** [comment]
Name removed in new design.

**Comment by scarroll32** [comment]
Fixed
