### ISSUE TITLE
I can't edit my own posts

### ISSUE THREAD

**Issue by marcelsalathe** [crowdAI/crowdai#330]
<img width="790" alt="screen shot 2017-09-29 at 7 31 59 am" src="https://user-images.githubusercontent.com/215057/31002033-55aad5b8-a4e8-11e7-9bba-d4709509c823.png">

**Comment by scarroll32** [comment]
As an admin you should be able to edit any post, this is not currently extended to participants.

Original feature: https://github.com/crowdAI/crowdai/issues/205

In this case, it is the discussion Topic that needs editing, not the Comment itself. The Topic doesn't have edit capability as the comments are based on this original content, and then the following comments may not make sense. 

The admin only presently has the ability to edit or delete a comment. When a comment is deleted, it still appears in the list, but the text is changed to "This comment has been redacted by the administrator"


### Proposed changes:

- admins can edit and delete a topic, if there are any comments then they will all be deleted if the topic is deleted or edited (completely, not redacted).
- participants have the ability to delete their own comment, in which case the comment will stay in the chain, but appear as ""This comment has been redacted by the participant"
- participants can modify their own comment, but some indicator should be present that it has changed. We should discuss how this would appear with Jason.

@marcelsalathe your thoughts?

**Comment by marcelsalathe** [comment]
Admins should definitely be able to edit / delete topics, not at least to manage abusive posts. I would implement this ASAP, and then we can talk with Jason about how any edits should look like later.

**Comment by scarroll32** [comment]
OK. A delete will delete any comments associated with the Topic.

**Comment by scarroll32** [comment]
Ready but waiting for upsteam code.

**Comment by scarroll32** [comment]
Implemented.
