### ISSUE TITLE
Post challenge flag is set for create only

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#332]
The post challenge flag should only be set when a submission is created, not when it is later updated for a regrade.

https://github.com/crowdAI/crowdai/blob/master/app/models/submission.rb

**Comment by spMohanty** [comment]
Also, we need to rethink how to visually show post-challenge submissions.
I will add this to the discussion on Monday with Jason, if we have some extra time at the end.

OpenSNP challenge will continue accepting submissions starting tomorrow (30th September)

**Comment by scarroll32** [comment]
Have implemented this assuming post challenges are also limited by the same number of submissions. If this is not required for a specific challenge, then the limit can be removed after the end of the challenge (by setting it to zero).

**Comment by scarroll32** [comment]
Incorporated into #327
