### ISSUE TITLE
Include images side by side using Kramdown ?

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#337]
The section below takes a lot of vertical space, while wasting a lot of horizontal space.
It would be great if there is an easy way to place images side by side.

We will run into this particular issue multiple times over many challenges in the future when we have to put down logos in the partner section.

<img width="393" alt="screen shot 2017-10-04 at 13 57 53" src="https://user-images.githubusercontent.com/1581312/31174541-214207ec-a90c-11e7-9797-dd894baaad33.png">

**Comment by scarroll32** [comment]
Actually Jason also mentioned this issue. We had discussed having a special partners section which would have a regular file upload and then place the resized images in a grid. We could also have some mouse over CSS effects like with the sponsors on [AMLD](https://www.appliedmldays.org/).

This would be a bit tricky with Kramdown though ... unless you have any ideas on how to do it @spMohanty  ?

**Comment by bkDJ** [comment]
Since kramdown allows attribute lists, why not take advantage of that? Add some css to the app and use the appropriate class when preparing the challenge kramdown.

![](https://user-images.githubusercontent.com/6138914/31284457-e22a5862-aab8-11e7-9dd0-d2582edcdf56.png 'Crude example')

**Comment by scarroll32** [comment]
They now wrap, you just need to add the class {:class='img-logo'} in the markdown.
