### ISSUE TITLE
Dynamic visualisations on leaderboard detail page

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#345]
On a per-challenge basis, crowdAI will be able to display dynamic visualisations on the leaderboard detail page (which is under development https://github.com/crowdAI/crowdai/issues/324). These visualisations will be challenge-specific D3 code.

## Modifications needed

- [ ] Modify the API to accept a json hash
- [ ] Store the json in a new jsonb field against the submission
- [ ] Add the D3 library to crowdAI
- [ ] Add a Dynamic D3 box to the challenge definition
- [ ] Inject the D3 code + json into the leaderboard detail page

**Comment by scarroll32** [comment]
@spMohanty please review

**Comment by spMohanty** [comment]
Looks great. Thanks @seanfcarroll !

**Comment by scarroll32** [comment]
Has been superceeded by React component approach. Closed.
