### ISSUE TITLE
A winners tab on challenge page 

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#346]
We should have a winners tab on every challenge page, which can be filled in markdown by the admins (or challenge organisers) after the said challenge ended.

**Comment by scarroll32** [comment]
@spMohanty, so would this work?

- [x] Add markdown editor field in challenge definition  - "winner_description"
- [x] If the "winner_description" is completed AND the challenged has ended, display the rendered markdown as the last tab in the challenge, with a title "Winner"

**Comment by spMohanty** [comment]
@seanfcarroll : Perfect ! 😄 Once this is implemented, I will fill in the winners for the previous challenges.

**Comment by scarroll32** [comment]
https://github.com/crowdAI/crowdai/commit/9af01669123d071abc81600ed8f6bee943321c96

**Comment by scarroll32** [comment]
Implemented.
