### ISSUE TITLE
Links to posts on discussion forum end with `new`

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#347]
The URL for a particular post on a discussion forum is currently of the form `https://www.crowdai.org/topics/new-1-5-model/comments/new`

the `/comments/new` part is redundant, and we should try to get rid of it  ?

**Comment by marcelsalathe** [comment]
Agree - it's especially awkward when trying to share the link. Since it's very easy to do and is an inhibitor to growth, I'll move this up to high priority.

**Comment by scarroll32** [comment]
How about:

`https://www.crowdai.org/topics/new-1-5-model/discussion`

?

**Comment by spMohanty** [comment]
@seanfcarroll : Ideally we should have something like ``https://www.crowdai.org/topics/new-1-5-model`. But I remember it was a bit of extra work because of the embedded form. So if there has to be something after the slug of the topic, I think `https://www.crowdai.org/topics/new-1-5-model/comments` should be more relevant I think ?

In any case, I just had the issue with the `/new` at the end, which was misleading.

**Comment by scarroll32** [comment]
It's just that ```https://www.crowdai.org/topics/new-1-5-model/comments``` is already a rails route. The ```new``` is there as it is a form (this is standard Rails).

We can override this of course, but probably best to override to something that is not meaningful to Rails, hence ```discussion```

**Comment by scarroll32** [comment]
Actually with a bit more hacking we can go with ```comments``` I think. Will try it out.

**Comment by scarroll32** [comment]
In the end went with discussion, as overriding rails defaults with different meanings feels like asking for trouble...

**Comment by scarroll32** [comment]
Implemented
