### ISSUE TITLE
Site not recognising previous hearts

### ISSUE THREAD

**Issue by marcelsalathe** [crowdAI/crowdai#351]
I'm logged in and go to the openSNP challenge, and it doesn't show the correct heart - it shows the inactive one, even though I hearted it quite some time ago.

<img width="396" alt="screen shot 2017-10-13 at 15 24 04" src="https://user-images.githubusercontent.com/215057/31548362-d634081a-b02a-11e7-8ce3-b19196713c69.png">

When I try to hear it, it redirects me to the homepage, and gives me an "already signed in" alert, which makes no sense.
<img width="208" alt="screen shot 2017-10-13 at 15 24 10" src="https://user-images.githubusercontent.com/215057/31548387-e98a861e-b02a-11e7-973f-90217b7dfe26.png">

I'm labeling this as high priority because I want to make sure this is "just" a UI bug, but even if, it's an important one.

**Comment by scarroll32** [comment]
Fixed
