### ISSUE TITLE
Jobs

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#352]
Add a simple jobs view

## Job Attributes

- Job Title
- Organisation
- Contact Name (optional)
- Contact Email / Phone (optional)
- Posted Date
- Closing Date (optional)
- Status - (active / inactive)
- Job Description (markdown)
- Remote (boolean)
- Location (city / country)

Added components

- [x]  "Jobs" link on the main navbar 
- [x]  Jobs button on the landing page
- [x] Admin interface to manage jobs
- [x] List view with the standard list header ("Jobs" and a sentence or 2)
- [x] Detail page with a simple header of all fields except markdown body
- [x] Markdown body in the page body
- [x] View count for the job
- [x] A deactivate option to remove the jobs view completely (if there are no jobs)

**Comment by marcelsalathe** [comment]
Description should be title 

Should have country field

A Boolean field remote (yes / no)

**Comment by scarroll32** [comment]
Changed "Company" to "Organisation"

**Comment by scarroll32** [comment]
Available in Staging for review

https://crowdai-stg.herokuapp.com/job_postings

Jobs can be turned completely on or off via settings in ActiveAdmin.

Individual jobs will appear only if in a status of 'open'

<img width="1027" alt="screen shot 2017-10-20 at 11 18 07" src="https://user-images.githubusercontent.com/11340230/31813940-5fe29182-b588-11e7-8216-0ae97c3e40e1.png">

**Comment by scarroll32** [comment]
Implemented.

**Comment by spMohanty** [comment]
Shouldnt people be able to interact with Job Postings at https://www.crowdai.org/job_postings ?
Like heart them, hopefully in the future, respond to them ;) etc ?
