### ISSUE TITLE
Addition of a 'Participants' tab to the challenge

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#358]
Add a new tab called 'Participants' to the challenge view. This will be populated from the ParticipantChallenge model (SQL view), and will require a new controller called ParticipantChallengeController.

A later version of this function will require uploading documents and approval step for ImageCLEF participants, so the ParticipantChallenge will probably need to be converted from a SQL view into a table. This will be addressed in a separate issue. 

<img width="994" alt="screen shot 2017-10-19 at 10 33 49" src="https://user-images.githubusercontent.com/11340230/31761677-09a4b5d6-b4b9-11e7-98be-71f658e11751.png">

The list will possibly be quite long, so will require paging with a 'Load More' button, as has been used on other pages, for example:

<img width="1253" alt="screen shot 2017-10-19 at 10 37 43" src="https://user-images.githubusercontent.com/11340230/31761824-9ab0a9b8-b4b9-11e7-9634-5f0d97cf7132.png">

**Comment by ieggel** [comment]
@seanfcarroll 
I guess this tab should only be visible for admins and organizers. Can you confirm?
