### ISSUE TITLE
Flags for jobs

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#369]
In the jobs design, we need to have a flag for the country in which the job is located. We will also need some other symbol to nominate a remote job.

**Comment by jsnrynlds** [comment]
Hi @seanfcarroll – I think the location (or remote status) needs to go on the Jobs index page, too. You okay with that?

**Comment by jsnrynlds** [comment]
@seanfcarroll @marcelsalathe – We could use something [like this](https://github.com/7kfpun/flag-css) for the flags, although I'm not sure what the default size is.

Alternatively, we could allow companies/organisations to upload a logo instead? It would be a bit simpler (I think) but would still add some visual interest.

**Comment by marcelsalathe** [comment]
Agree it should be on index page. If I'm in Germany, I don't care too much about jobs in France, US, etc...  it doesn't need to be prominent, but should be clear nonetheless. Would actually also be nice eventually if one could filter by country...

Logo upload - maybe in a further stage, if this is of interest to companies. For now this adds too much complexity.

**Comment by jsnrynlds** [comment]
@seanfcarroll Added flags to the job board. I've used https://github.com/7kfpun/flag-css which seems to work well. 

Also, made some changes to the structure of template-job-board.html

Pushed to https://github.com/salathegroup/crowdai-templates

**Comment by scarroll32** [comment]
Implemented
