### ISSUE TITLE
Autoplay of (thumbnail) videos on the leaderboard starts after way too long

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#371]
It took approximately 12 seconds before the thumbnail videos started playing. It was much faster before the leaderboard redesign I guess ?

**Comment by scarroll32** [comment]
OK now I'm getting errors also

<img width="816" alt="screen shot 2017-10-27 at 14 54 46" src="https://user-images.githubusercontent.com/11340230/32104926-d9bdaaf2-bb26-11e7-86fa-24aee9d36017.png">

**Comment by scarroll32** [comment]
Will drop the html5 video element and instead try this React component https://github.com/video-react/video-react

**Comment by scarroll32** [comment]
Fixed
