### ISSUE TITLE
Logos in the challenge overview page are too large

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#375]
https://www.crowdai.org/challenges/nips-2017-learning-to-run

<img width="1920" alt="screen shot 2017-10-28 at 13 52 52" src="https://user-images.githubusercontent.com/1581312/32134159-56304070-bbe7-11e7-98b6-b35eb189005a.png">

**Comment by marcelsalathe** [comment]
Ugh - what happened? They used to be properly sized.

**Comment by spMohanty** [comment]
I think we should fix this one properly this time.
Even when they are properly sized, they take up way too much vertical space. And you have to scroll a lot before you can reach the next section.

When adding images, we do want to be able to decide if they should be inline or not, and also preferrably select the size we want them to be rendered as.

**Comment by marcelsalathe** [comment]
Agree - I think we can use the grid solution that we developed for Applied Machine Learning Days (2018) website - what do you think, @seanfcarroll?

**Comment by scarroll32** [comment]
@marcelsalathe we can do something like the ALMD approach; to do so we will need to capture logo images specifically. Currently they are embedded into the markdown.

I'm not sure what happened exactly. The images are marked with a width of 200px but it doesn't seem to be applying. I've added a new style which is working to solve the immediate problem, but will leave this ticket open to implement a grid. 

The temporary image class is: 'img-logo', so the markdown needs to be altered (I will do it) to:
```
![stanford](https://s3.amazonaws.com/salathegroup-static/nips/logos/Stanford.png){:class='img-logo'}
```


https://github.com/crowdAI/crowdai/commit/4f70e86285292fb8eecf9d1434db723257ca4e10

**Comment by scarroll32** [comment]
Design available in template-challenge.html

**Comment by scarroll32** [comment]
Can now add logos along with a link, in the challenge setup.
