### ISSUE TITLE
CSS issue on profile page

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#385]
Observed on firefox.
The numbers next to the tabs are placed in a weird way.
<img width="1071" alt="screen shot 2017-11-02 at 13 23 59" src="https://user-images.githubusercontent.com/1581312/32325918-3c816eae-bfd1-11e7-9fde-b5b02db86dd9.png">

**Comment by marcelsalathe** [comment]
can confirm, I'm on latest version of firefox and have the same.

**Comment by jsnrynlds** [comment]
Duplicate issue: https://github.com/crowdAI/crowdai/issues/431
