### ISSUE TITLE
Feature requests for submissions page

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#406]
- [x] Color code the grading status : orange for "submitted", red for "failed", "green" for graded
- [x] pagination
- [x] filtering
- [x] Turn on submissions page optionally by challenge
- [x] Refactor code

**Comment by scarroll32** [comment]
Also added score if there is no message.

**Comment by scarroll32** [comment]
@jsnrynlds This page wasn't really designed ... and it shows :-)

Not super urgent, but if you have time to clean it up it would be appreciated. Here's an example: https://www.crowdai.org/challenges/www-2018-challenge-learning-to-recognize-musical-genre/submissions

The grading status is text at present, but it might make sense for it to be some type of badge (https://github.com/crowdAI/crowdai/issues/349) and the request is for it to be color coded.

**Comment by scarroll32** [comment]
Hi @jsnrynlds most of this is now implemented ... would ask you for help on:

- colour codes for statuses : [:ready, :submitted, :graded, :failed, :initiated]
- filtering (perhaps a simple global filter box?)

**Comment by jsnrynlds** [comment]
@seanfcarroll @spMohanty I've created some badges for challenge status on homepage, so I guess it would make sense to use these here, too (?).

![featured challenges](https://user-images.githubusercontent.com/1162939/37643530-b9e2e072-2c18-11e8-966e-38ad56811801.png)

**Comment by scarroll32** [comment]
Definitely!

**Comment by scarroll32** [comment]
Hey @jsnrynlds this would be nice to have on the platform.

**Comment by rapsli** [comment]
We currently have the following issue:
- People are submitting the sample solution, which results in them appearing on the high score possibly even in front of those who have actually submitted real solutions.

With the filtering certain submissions based on some given criteria. Would be great if this could be implemented.

**Comment by scarroll32** [comment]
Will look at adding filtering and sorting asap. Upgraded to high.

**Comment by scarroll32** [comment]
Implemented

**Comment by rapsli** [comment]
@seanfcarroll can you please let me know how we can make use of the filtering?

**Comment by scarroll32** [comment]
There is a filtering icon on the submissions page, click it and the filter is revealed. 
<img width="1205" alt="screen shot 2018-09-11 at 16 19 42" src="https://user-images.githubusercontent.com/11340230/45367698-230b9c80-b5e2-11e8-8424-8f44d3478c3b.png">
<img width="1209" alt="screen shot 2018-09-11 at 16 19 36" src="https://user-images.githubusercontent.com/11340230/45367699-230b9c80-b5e2-11e8-8a71-222fb6e38636.png">
