### ISSUE TITLE
Ranks in round-2 leaderboard show the general rank

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#415]
<img width="1465" alt="screen shot 2017-11-11 at 21 58 21" src="https://user-images.githubusercontent.com/1581312/32693466-8abb7f54-c72b-11e7-9ac5-4b1ac79bdaa0.png">

Ideal behaviour should be to show the rank only in the entries in round-2

**Comment by scarroll32** [comment]
Will check into it today

**Comment by scarroll32** [comment]
Fixed
