### ISSUE TITLE
Better syntax highlighting in Kramdown

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#424]
<img width="744" alt="screen shot 2017-11-14 at 21 50 24" src="https://user-images.githubusercontent.com/1581312/32804031-e4664596-c985-11e7-8bb5-50a31a184017.png">

We definitely need to have better syntax highlighting in the forum posts on crowdAI.

**Comment by marcelsalathe** [comment]
I agree. If we're at it, we should also see how we can better distinguish code from links. In the screenshot below, it's hard to see which ones are links and which ones are code style:

<img width="725" alt="screen shot 2017-11-26 at 12 07 59" src="https://user-images.githubusercontent.com/215057/33239457-a713a910-d2a2-11e7-96d4-b6d4136d0814.png">

I'm bringing in @jsnrynlds to help us with this. I'm also removing the low priority label since I think it's actually quite important!

**Comment by jsnrynlds** [comment]
@spMohanty @marcelsalathe I can see how this could be confusing.

Maybe something like one of the attached...

<img width="743" alt="screen shot 2017-11-29 at 13 26 55" src="https://user-images.githubusercontent.com/1162939/33377457-71396654-d509-11e7-98b2-81fabc4f26d2.png">
<img width="733" alt="screen shot 2017-11-29 at 13 28 49" src="https://user-images.githubusercontent.com/1162939/33377458-714fa0f4-d509-11e7-8296-53dd03e2904a.png">

**Comment by jsnrynlds** [comment]
The text-colour probably needs to be a bit darker on that second example...

**Comment by marcelsalathe** [comment]
Thanks @jsnrynlds - the first one is better, more neutral. It's also what GitHub uses:
`hello I'm a codeblock`
The only thing I would do is follow GitHub's lead and make the text on the gray background fully black so it truly stands out. It's what millions of developers are used to now.

**Comment by spMohanty** [comment]
Just adding that, apart from this, Kramdown also supports syntax for code blocks in python, ruby, etc, out of the box.
https://kramdown.gettalong.org/syntax_highlighter/rouge.html

@sean : I dont think this is enabled on crowdAI ?

**Comment by jsnrynlds** [comment]
I can't use GitHub desktop today for some reason, but have just changed the `<code>` CSS in __typography.scss_ to:

```
code {
  font-family: Menlo, Monaco, Consolas, "Courier New", monospace;
  font-size: 14px;
  padding: 2px 4px;
  color: $color-grey-87;
  background: $color-grey-03;
  border-radius: 3px;
}
```

**Comment by scarroll32** [comment]
We can use http://codemirror.net/

**Comment by scarroll32** [comment]
Assigned to @MasterScrat , please discuss implementation with @spMohanty

**Comment by scarroll32** [comment]
GitLab also use Kramdown and have a [great user guide](https://docs.gitlab.com/ee/user/markdown.html). Will investigate how they have set it up and possibly follow their lead.

**Comment by scarroll32** [comment]
It looks like we have a double syntax highlighting going on. 

<img width="584" alt="screen shot 2018-06-29 at 09 01 27" src="https://user-images.githubusercontent.com/11340230/42077998-22b91a1a-7b7b-11e8-990a-6cc329c924bc.png">
<img width="472" alt="screen shot 2018-06-29 at 09 01 20" src="https://user-images.githubusercontent.com/11340230/42077999-22d276e0-7b7b-11e8-8066-fd8fbc5784c0.png">

**Comment by scarroll32** [comment]
Patched for now, but the markdown editor needs [a refresh](https://github.com/crowdAI/crowdai/issues/874)
