### ISSUE TITLE
kramdown branding

### ISSUE THREAD

**Issue by bkDJ** [crowdAI/crowdai#426]
According to [kramdown's official website](https://kramdown.gettalong.org/):
> **kramdown** (sic, not Kramdown or KramDown, just kramdown) is a *free* MIT-licensed Ruby library for parsing and converting a superset of Markdown.

However, the crowdAI website has a few spots where kramdown is allowed in text boxes, but is mentioned with improper case or not at all.

<i>Example 1:  Adding a comment to a discussion. https://www.crowdai.org/topics/format-of-the-predictions/discussion </i>
![image](https://user-images.githubusercontent.com/6138914/32887371-fc517254-cac3-11e7-99d6-1e97573d5223.png)

<i>Example 2: Creating a new topic for a challenge </i>
![image](https://user-images.githubusercontent.com/6138914/32887458-44551d94-cac4-11e7-8ff0-92cae4d8337e.png)

There may be other places as well.

**Comment by scarroll32** [comment]
Implemented
