### ISSUE TITLE
ImageCLEF pre launch items

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#428]
- "Complete the EAU"
- "EAU approval pending

**Comment by scarroll32** [comment]
Remove add file button

<img width="245" alt="screen shot 2017-11-16 at 15 50 22" src="https://user-images.githubusercontent.com/11340230/32897456-ec5f782e-cae5-11e7-9fec-3bee58fbc496.png">

**Comment by ieggel** [comment]
@seanfcarroll 
Just discovered a problem on the task pages (organizers/imageclef/clef_tasks/***)  in the staging environment:
- Can't access the tasks' already uploaded EUA,
- Can't add dataset files,
- Can't see existing dataset files,
- This happens when logged in as an ImageCLEF as well as a LifeCLEF organizer

**Comment by scarroll32** [comment]
Thanks @ieggel I think it is a security issue. I will look into it.

**Comment by ieggel** [comment]
@seanfcarroll 

In the LifeCLEF challenge dataset tab I'm asked to provide an EUA. This should not happen for LifeCLEF tasks, as they do not require an EUA. Maybe a good way would be to simply check if the task has an EUA uploaded, and only then require it for participants

**Comment by ieggel** [comment]
@seanfcarroll 

the profile_incomplete status does not show up in the dataset tab if my profile is not complete. The following fields should be filled in:
 - firstname
 - lastname
 - afiiliatiom
 - address
 - city
 - country

**Comment by ieggel** [comment]
@seanfcarroll 

The requested status (if participant downloaded EUA) message does not show up in the dataset tab. Instead the unregistered status message is shown.

**Comment by ieggel** [comment]
@seanfcarroll 

There is no possibily to replace (reupload) the EUA in the dataset tab if the status is submitted. It would be good to for a participant to replace the uploaded EUA as often they do some mistakes when filling  it out.

**Comment by ieggel** [comment]
@seanfcarroll 

I cannot upload any dataset files in the staging env. Probably an S3 issue?

**Comment by scarroll32** [comment]
All these issues are now fixed. A new release will be produced shortly.

**Comment by ieggel** [comment]
@seanfcarroll 

For LifeCLEF: if i have access to the LifeCLEF challenge dataset i get  this message "Your signed EUA has been approved ...". Would it be possible to show the message without the EUA part, since the LifeCLEF participants do not have to upload an EUA.

**Comment by ieggel** [comment]
@seanfcarroll 

Error 500 if i want to add a dataset file on the task page. This happened being a LifeCLEF organizer
Same thing is happening as an ImageCLEF organizer.

**Comment by ieggel** [comment]
@seanfcarroll 
Error 500 if i click on participants tab of challenge. Was logged in as an organizer.
