### ISSUE TITLE
Suffixes on Firefox

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#431]
<img width="707" alt="screen shot 2017-11-17 at 12 49 18" src="https://user-images.githubusercontent.com/11340230/32945972-e27e8ff6-cb95-11e7-95c1-7b5f3b24fa35.png">

**Comment by jsnrynlds** [comment]
@seanfcarroll This was a bit tricky as it affected the red border below the active item. Changed the SCSS for `<sup>` and the way line-height works in `.sub-nav`. Seems to work fine in Firefox, Chrome & Safari now. Pushed to: https://github.com/salathegroup/crowdai-templates

**Comment by scarroll32** [comment]
@jsnrynlds yes that did it. Thanks.
