### ISSUE TITLE
Email notification for EUA upload for ImageCLEF challenges

### ISSUE THREAD

**Issue by ieggel** [crowdAI/crowdai#435]
ImageCLEF organizers should be notified as soon as a participant has uploaded an EUA

**Comment by scarroll32** [comment]
@ieggel Can you provide some copy text for the email?

**Comment by ieggel** [comment]
SUBJECT: [ImageCLEF CrowdAI] - New EUA upload for {task name}

Dear {organizer participant name},

{participant name}has uploaded an End User Agreement (EUA) for task {task name} on CrowdAI. If your are responsible for this task, please check the participant's EUA. If the form is compliant, you can approve it by clicking on the approve button next to the participant's name. In case the EUA is faulty or incomplete the participant can re-upload a new EUA.

You can approve the participant's EUA <a href="link to one of the task's challenges participants tab">here</a>.

Best regards,
The CrowdAI team

**Comment by scarroll32** [comment]
- [x] add a checkbox to receive email
- [x] create a background job to send emails when the EUA is uploaded
- [x] Create a mailer

**Comment by scarroll32** [comment]
Implemented
