### ISSUE TITLE
rendering issues in music challenge

### ISSUE THREAD

**Issue by marcelsalathe** [crowdAI/crowdai#448]
This looks wrong:

<img width="708" alt="screen shot 2017-11-26 at 12 02 43" src="https://user-images.githubusercontent.com/215057/33239399-d1d7e98c-d2a1-11e7-832a-29c58c4ee724.png">

**Comment by spMohanty** [comment]
The correct syntax should be : `$ \mu $` but when I do it, I do not see anything at all.
Could be a CSS issue of how mathjax blocks are rendered ?

**Comment by scarroll32** [comment]
I think it is Turbolinks related, refreshing fixes it. I will look at this after the single sign on

<img width="620" alt="screen shot 2017-11-27 at 13 52 48" src="https://user-images.githubusercontent.com/11340230/33267601-65d1f5a0-d37a-11e7-9626-c8456da89238.png">
<img width="687" alt="screen shot 2017-11-27 at 13 52 32" src="https://user-images.githubusercontent.com/11340230/33267602-65f6ee1e-d37a-11e7-83af-f1e5ca849ba3.png">

**Comment by spMohanty** [comment]
Okay, turns out, its probably an issue with the `Preview` tab.
I was using it to check how it will appear, and now when I updated the content disregarding the `Preview` output, it renders correctly on the main page.

**Comment by spMohanty** [comment]
The leaderboard headers do not render properly though.
Check the parts where usually we have "Score" and the "Secondary Score" headers.

**Comment by scarroll32** [comment]
They need to be added in the config. I can do it: are we just going with score & secondary score or something else?

<img width="829" alt="screen shot 2017-11-27 at 14 25 46" src="https://user-images.githubusercontent.com/11340230/33268848-f76f3f50-d37e-11e7-87dd-969f37809bc5.png">

**Comment by scarroll32** [comment]
And sort order?

**Comment by spMohanty** [comment]
<img width="917" alt="screen shot 2017-11-27 at 14 43 35" src="https://user-images.githubusercontent.com/1581312/33269545-633bbe96-d381-11e7-939f-de374c76ea97.png">

I have this already configured :-?

**Comment by scarroll32** [comment]
Mathjax in the table headers!

Cool - it is all working now.
