### ISSUE TITLE
REST Service for CLEF Registrations

### ISSUE THREAD

**Issue by ieggel** [crowdAI/crowdai#455]
Create a REST service that provides returns registered CLEF participants including the tasks they are registered for.

**Comment by scarroll32** [comment]
No problem. 

Please nominate which fields should be visible.

Is this a read-only service?

**Comment by ieggel** [comment]
Yes this should be a readonly service.

Maybe it would be best to have a service that returns participants of a certain task

For participants the following fields should be provided:
- name
- first name
- last name
- email
- affiliation
- address
- city
- country

Maybe we should also include a parameter "status" with the following possible values:
- <empty>  => return participants regardless of the status_cd associated with the task
- registered => returns participants that have "registered" as status_cd associated with the task
- submitted =>  returns participants that have "submitted" as status_cd associated with the task
- requested =>  returns participants that have "requested" as status_cd associated with the task(s)

@seanfcarroll

**Comment by scarroll32** [comment]
Example starter code with a working endpoint and tests here: https://github.com/crowdAI/crowdai/pull/524/commits/d43144d883e404655f987a85d25a4acc28de8d55

@ieggel  This will be merged to master so as not to get too far behind the trunk, but can be extended at anytime by yourself.
