### ISSUE TITLE
Email unsubscribe not working

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#456]
One of the participants reported this in the gitter channel : 

<img width="1229" alt="screen shot 2017-11-29 at 04 51 42" src="https://user-images.githubusercontent.com/1581312/33357191-1552076c-d4c1-11e7-9f32-71fd291fb03e.png">

**Comment by spMohanty** [comment]
As an admin user I can see some extra options : 
<img width="595" alt="screen shot 2017-11-29 at 04 53 54" src="https://user-images.githubusercontent.com/1581312/33357324-c5dd4916-d4c1-11e7-800d-20a86c5d7ed6.png">

**Comment by LiberiFatali** [comment]
Sorry, I may create misunderstanding. I do have those extra options. 
However, I thought that I would have received the email once a week if I checked the last frequency option. I have got digest email everyday instead.

**Comment by scarroll32** [comment]
Dear @LiberiFatali thank you for your contribution. In fact the UI had a small bug which is then misinterpreted by the mail program. The first set of boxes determine what emails are sent, and the second set which frequency. I have corrected your record to weekly, and I think it will be OK now.
