### ISSUE TITLE
checkboxes in email settings have different style

### ISSUE THREAD

**Issue by marcelsalathe** [crowdAI/crowdai#467]
<img width="520" alt="screen shot 2017-12-04 at 11 25 00" src="https://user-images.githubusercontent.com/215057/33547925-dd0765b8-d8e5-11e7-99a7-7defa80656cf.png">

Not sure why - in fact that one at the bottom looks inactive.

**Comment by jsnrynlds** [comment]
I'm not sure this is a CSS issue, but as the user can only select one of those three options we should probably be using radio buttons instead.

**Comment by scarroll32** [comment]
I agree with radio buttons. Will implement.

**Comment by scarroll32** [comment]
Done
