### ISSUE TITLE
Submissions Page layout

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#472]
The layout gets very weird in case of long messages. 
<img width="1178" alt="screen shot 2017-12-06 at 11 25 03" src="https://user-images.githubusercontent.com/1581312/33681023-3a4b1fce-da78-11e7-918e-0ecbffeeda39.png">

**Comment by scarroll32** [comment]
It needs to be styled. Will work with Jason.

**Comment by jsnrynlds** [comment]
Sorted this. Can we remove the avatars as they don't seem necessary here.

HTML changed in _organism-table-submissions.html_; SCSS in __tables.scss_.

**Comment by scarroll32** [comment]
Implemented.

I left in the badges (they were not in the new design).

Related issue opened here to reduce size of scores 
https://github.com/crowdAI/AIGeneratedMusicChallenge_job_factory/issues/2

**Comment by scarroll32** [comment]
https://github.com/crowdAI/crowdai/pull/537
