### ISSUE TITLE
Submission page not showing all entries

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#473]
In the AI generated music challenge, my user account is on the leaderboard, but there is no corresponding entry on the submissions page :-?

**Comment by scarroll32** [comment]
I can see you there.

There were some changes made to the leaderboard but they shouldn't have affected the submission view. 

<img width="1183" alt="screen shot 2017-12-07 at 09 51 30" src="https://user-images.githubusercontent.com/11340230/33706402-574f88dc-db34-11e7-9448-150f97fbee1c.png">
