### ISSUE TITLE
Markdown on dataset page

### ISSUE THREAD

**Issue by mdeff** [crowdAI/crowdai#479]
When the data is hosted outside crowdAI, it would be nice to be able to write instructions directly on the dataset page instead of having to upload a PDF with them. See for example the [musical genre recognition challenge](https://www.crowdai.org/challenges/www-2018-challenge-learning-to-recognize-musical-genre/dataset_files), where training and test data are hosted on SWITCH.

An alternative would be to allow arbitrary links. But we would still need some free-text to write instructions, tips, etc.

**Comment by scarroll32** [comment]
External files can now be uploaded.
