### ISSUE TITLE
Spinner/Loader for when media is loading

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#484]
For example if you go here : https://www.crowdai.org/challenges/8/leaderboards/3452

and the media is not already loaded, then for sometime, it seems like nothing is happenning !! 
Would be good to render a spinner while the data is loading

**Comment by scarroll32** [comment]
I plan to rewrite the leaderboard as a React component over the Christmas period ... will incorporate this feature.

**Comment by scarroll32** [comment]
Jason will design a full page spinner. @jsnrynlds

**Comment by jsnrynlds** [comment]
Added full-page loader: https://github.com/salathegroup/crowdai-templates

`template-loader.html`

**Comment by scarroll32** [comment]
Implemented
