### ISSUE TITLE
Editing a user post by an admin changes the user

### ISSUE THREAD

**Issue by marcelsalathe** [crowdAI/crowdai#500]
I was editing a user post in the forum (excessive use of question marks), and it changed the posting user to me:

<img width="510" alt="screen shot 2018-01-03 at 18 37 17" src="https://user-images.githubusercontent.com/215057/34532487-94dfa0c8-f0b6-11e7-9b36-63ea295ef7b6.png">

**Comment by scarroll32** [comment]
Fixed
