### ISSUE TITLE
Number of Page Views ?

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#501]
the page views of a challenge doesnt seem to increase if a user just goes to the evaluation page (or the leaderboard etc), and only increases on the main overview page

Not sure if this is by design or if its a bug

**Comment by scarroll32** [comment]
The counter only fires on the challenge home page.

It wasn't added to the other pages, as we will then effectively be double counting, as the stat is displayed as 'views'. 

<img width="269" alt="screen shot 2018-01-04 at 14 55 05" src="https://user-images.githubusercontent.com/11340230/34566559-4a0d5b72-f15f-11e7-92d6-af96f818e043.png">


If we consider it 'page views' then no problem ... can be added easily.

**Comment by spMohanty** [comment]
No I pointed it out, because we recently had a large number of users who visited just the evaluation page (and not the main overview page).

Given that they didnot visit the challenge overview page, the counter didnt increase; but the numbers were reflected in google analytics. 

Just putting it out here for future reference.
We can leave it as it is for now, and discuss in detail what the stats mean, when we meet.

**Comment by scarroll32** [comment]
No problem, but also easy to add.

**Comment by scarroll32** [comment]
Closed
