### ISSUE TITLE
Cannot see more than 30 participants on the leaderboard ?

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#513]
https://www.crowdai.org/challenges/nips-2017-learning-to-run/leaderboards

**Comment by scarroll32** [comment]
Hi @jsnrynlds apparently the pills for round 2 are causing some confusion. Let's discuss options at some point when you have time

Low priority.

![screen shot 2018-01-26 at 14 15 08](https://user-images.githubusercontent.com/11340230/35441326-6b6b8762-02a3-11e8-884b-3912e320fcbd.png)

**Comment by scarroll32** [comment]
@spMohanty can this be closed?
