### ISSUE TITLE
Music challenge

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#515]
1) Remove ID
2) Make sure 2 sides are different
<img width="1140" alt="screen shot 2018-01-30 at 15 04 37" src="https://user-images.githubusercontent.com/11340230/35570343-3961284c-05cf-11e8-8e99-6e29674dabf1.png">

**Comment by spMohanty** [comment]
These issues have been addressed. 
A more comprehensive list of tasks :  
(submitted by @FlorianColombo )
- [x] Clear the log and submission (start from fresh)
- [x] Remove identifiers from evaluation page. 
- [x] Make sure a submission cannot be evaluated against itself 
- [ ] Implement a manual filter of submissions. By that I mean, there should be a human listening to each new submission. If we are sure that it is piano recorded or the submission is e.g. only some weird recognizable patterns, we could filter it out even before entering the challenge. Sean was mentioning a checkbox for admin to fill in before each submissions. 
- [ ] Specify the role of evaluators on the evaluation page. e.g. To participate in the evaluation, you should listen to the two following extracts. If you prefer one over the other, press on the like button of this extract. If you really do not have any preference between the two examples, you can reload the page to get new extracts. Once you selected one extract, two others will load. New examples will keep appearing until you decide to stop.  
- [x] Impose a maximum rate of submissions. 
- [ ]  Maybe set a threshold for too bad submissions to be less likely to be selected for rating (this can be actually an automated way for 4). Doing that, the crowd will focus on rating the one they like and the challenge will be more interesting for them (VS last time where a lot of bad data was present and people complained about that)

**Comment by scarroll32** [comment]
Needs a face to face discussion - seems like a major piece of work.

**Comment by scarroll32** [comment]
@spMohanty what are your thoughts on the open checkbox items in this issue?

**Comment by FlorianColombo** [comment]
There seems to be a problem with the display (on Chrome), which was not there previously (see screenshot)
<img width="1221" alt="screen shot 2018-03-12 at 3 22 27 pm" src="https://user-images.githubusercontent.com/22098979/37289262-917661fa-2609-11e8-8055-ed8ec2cdc5c1.png">

**Comment by scarroll32** [comment]
Closed
