### ISSUE TITLE
Plots for per-challenge statistics

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#523]
One page for every challenge where participants can get a birds eye view of the participant in the challenge. Here are some plots we generated for the Learning2Run challenge : 
* Score Distribution

![histogram](https://user-images.githubusercontent.com/1581312/35745401-7c50538c-0843-11e8-85b5-502173f546ff.png)

* Progression of Score over Time
![score progression](https://user-images.githubusercontent.com/1581312/35745335-37891298-0843-11e8-8a99-a6def1c55af6.png)

We can think of more creative ways to visually depict participant interactions with the challenge

**Comment by scarroll32** [comment]
Is that matplotlib? Is this view public or for the admin only?

**Comment by spMohanty** [comment]
Yeah these plots are done using matplotlib and tsplot. But ideally we should try something like plotly for these plots. Lets discuss more on this soon. 

And yeah, these should ideally be public for all challenges. Because the information used to make these plots is anyway present on the leaderboard, this just presents all that information in a more easily digestible way.

**Comment by scarroll32** [comment]
Needs a design session.

**Comment by spMohanty** [comment]
Related to : https://github.com/crowdAI/crowdai/issues/262

**Comment by scarroll32** [comment]
To be done in Grafana
