### ISSUE TITLE
Disappearing discussion comments

### ISSUE THREAD

**Issue by mdeff** [crowdAI/crowdai#529]
It happened that the first comment I wrote on a discussion disappeared:

![2018-02-07-15 01 13](https://user-images.githubusercontent.com/6806065/35920406-13e6a67e-0c18-11e8-89bc-a0ea3389133d.png)

Though I can see there should be 3 comments:

![2018-02-07-15 01 25](https://user-images.githubusercontent.com/6806065/35920412-1d9a2592-0c18-11e8-8a71-11f724c9a936.png)

These are two discussions for which it happened:
* <https://www.crowdai.org/topics/paper-submission/discussion>
* <https://www.crowdai.org/topics/paper-submission-deadline-extended/discussion>

**Comment by scarroll32** [comment]
Hi @mdeff did the comment text that you wrote disappear or is the count misleading?

**Comment by mdeff** [comment]
Hi, the text disappeared. The count is right.

**Comment by scarroll32** [comment]
Thanks, I will look into it.

**Comment by spMohanty** [comment]
Can confirm this.
The text content added when creating the a new "topic" in the discussion form is not rendered.

**Comment by marcelsalathe** [comment]
Wow, this needs super high priority attention!

**Comment by scarroll32** [comment]
Fixed
