### ISSUE TITLE
LifeClef participants bug

### ISSUE THREAD

**Issue by ieggel** [crowdAI/crowdai#533]
It seems that if a participant downloads a LifeClef dataset file, no entry is created in the participant_clef_tasks table. 
A LifeCLEF participant should be considered as registered as soon as he/she downloads a dataset file. This has actually worked before. 
@seanfcarroll  have you changed anything regarding this?

**Comment by scarroll32** [comment]
@ieggel I haven't directly touched that code.

**Comment by ieggel** [comment]
@seanfcarroll 
I found the bug. Actually the lifeclef participants are never stored in the participant_clef_task db table. Also, the wrong view is shown in the participants tab for the challenge, so there must have been some other criteria (probably the same as for the ordinary challenges) on when to consider a participant as registered.
I will fix the bug ASAP.

**Comment by ieggel** [comment]
@seanfcarroll 
PR #546

![lifeclef](https://user-images.githubusercontent.com/9192090/36539342-cd5ef9fc-17d6-11e8-891f-b1343cd6f14a.png)

Lifeclef participants have hot click on a button before accessing the dataset. Clicking the button triggers the creation of an entry in the participants_clef_tasks db table with 'registered' as status_cd.
