### ISSUE TITLE
A dedicated "register for challenge" page

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#535]
The current strategy of measuring participation by downloads, etc is a bit tricky.

We have to have a "register for challenge" page, which can be simply have a "I agree to the rules of this challenge", etc.

But only registered participants get access to the datasets section, or get featured on the leaderboard (maybe for un registered participants, we display "Unregistered participant").

I would mark this as high priority as this has been pending for sometime, and will be highly critical when we launch a few major challenges over the next two months.

We do want to have a way to clearly figure out the actual participation in the challenge, but the number also has to be meaningful !

**Comment by scarroll32** [comment]
We have a 2 versions of this for clef challenges. I think the best option is to merge this functionality and to make it configurable at the challenge level. 

https://github.com/crowdAI/crowdai/issues/422

**Comment by scarroll32** [comment]
Needed for May / June

- [ ] Add a reg "register for challenge" button on the challenge landing page
- [ ] API + submission page : only allow registered participants to submit via page / data set

**Comment by scarroll32** [comment]
- add a registration button on the challenge header
- only if this button is pressed can the user download data, make submissions or comments
- participant count = number buttons

**Comment by scarroll32** [comment]
This is almost done. @XCaellaX @spMohanty do we want to send out an email to participants when it is released ?

Separately we could probably use a "latest news" banner message for this type of thing.

**Comment by scarroll32** [comment]
This is 75% done on this branch: https://github.com/crowdAI/crowdai/tree/issue_535

The missing parts are updating the API to reflect the registered users, converting existing data and tests.

A question to solve - which users in our current 'registered participants' list do we convert. Current they are counted if:

- downloaded a file
- made a submission
- hearted the challenge 
- followed the challenge
- authored a topic or comment

**Comment by scarroll32** [comment]
Postponed to August.

**Comment by scarroll32** [comment]
Implemented
