### ISSUE TITLE
Add google link tracking to social shares

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#540]
https://blog.kissmetrics.com/how-to-use-utm-parameters/

**Comment by spMohanty** [comment]
Related to https://github.com/crowdAI/crowdai/issues/324

**Comment by scarroll32** [comment]
http://kikolani.com/blog-post-promotion-ultimate-guide?utm_source=kikolani&utm_medium=320banner&utm_campaign=bpp

source = crowdai
medium = fb / twitter
campaign = challenge

**Comment by spMohanty** [comment]
https://ga-dev-tools.appspot.com/campaign-url-builder/

**Comment by scarroll32** [comment]
Implemented
