### ISSUE TITLE
CLEF eua tests not working

### ISSUE THREAD

**Issue by ieggel** [crowdAI/crowdai#547]
Tests for CLEF status (involving EUAs) are not working. You already uncommented the parts that do not work in spec/cells/participant_clef_task/cell_spec.rb.
It seems there is a problem when creating the clef_task object. When the eua_file attribute should be set to something non-empty, it is ignored and will still be empty. 
Example:
`let(:clef_task) { create :clef_task, :with_eua }`
=> `clef_task.eua_file` will be empty

**Comment by scarroll32** [comment]
fixed
