### ISSUE TITLE
Link every submission to detail page

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#548]
- [x] add link icon from submissions page for each submission
- [x] make meta hash available on detail 
- [ ] integrate front-end library provided by @spMohanty

**Comment by scarroll32** [comment]
Meta is available on data elements on a hidden div. 


<img width="728" alt="screen shot 2018-02-27 at 08 59 11" src="https://user-images.githubusercontent.com/11340230/36717017-b25c8db2-1b9c-11e8-8cb2-95072a692aa1.png">

<div id="meta" data-meta="{&quot;file_key&quot;:&quot;submissions/5b9e0772-6ad5-4727-8be1-9675d8c7ac6d&quot;}"></div>

**Comment by spMohanty** [comment]
This is a bit risky, as I might store some sensitive information in the meta key.

**Comment by scarroll32** [comment]
as an alternative the meta can be accessed from the (exisiting) submission info endpoint via ajax. Let me know & I'll back this code out. @spMohanty

**Comment by spMohanty** [comment]
or alternatively, if `meta` supports nested variables, we can have a structure like : 

```
{
"secret_param1":"val1",
"secret_param2":"val2",
"public":{
    "public_meta_param1":"public-val-1",
    "public_meta_param2":"public-val-2",
    }
}
```
Meaning, all the keys of `meta` are private by default.
But if there are any keys available in the "public" key, then they should be available.
A majority of the keys we will store will be private, and some we would want to be public. 

Does this make sense ?

**Comment by scarroll32** [comment]
OK, will consider only a "public" key and children.

**Comment by scarroll32** [comment]
Done
