### ISSUE TITLE
Highlight the top-3 participants on the leaderboard

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#563]
Somehow visually differentiate the top-3 participants on the leaderboard.
This can be motivating for the top-N participants to push for it, so that even if they are not #1, but they can still aim for being in this group of top users who are distinctly "special".

Can be simply by rendering their titles in bold, or maybe adding 🏆 icons next to their user names etc ?

the number "3" in top-3 should be configurable, as in some challenges we might be giving away prizes to the top-N participants. So the same visual differentiator will show that these participants will win the prize if they maintain this rank !

Pretty sure this will contribute positively to the game dynamics in the challeges

cc. @jsnrynlds  @seanfcarroll

**Comment by scarroll32** [comment]
good idea!

**Comment by scarroll32** [comment]
Implemented, but will leave this open. @jsnrynlds I added some code to do the highlighting, but perhaps you might have a better way to do this? https://github.com/crowdAI/crowdai/pull/643/commits/165d75f70e15c2ef914bcd8cd0e715144227f44c

The number of highlighted entries is configurable (Highlight rankings).

<img width="747" alt="screen shot 2018-03-27 at 13 05 35" src="https://user-images.githubusercontent.com/11340230/37963754-9228b5dc-31bf-11e8-8e54-99475c5b4538.png">


<img width="1084" alt="screen shot 2018-03-27 at 13 03 24" src="https://user-images.githubusercontent.com/11340230/37963658-42e3aac2-31bf-11e8-8379-98ef815e35c6.png">

**Comment by jsnrynlds** [comment]
@seanfcarroll due to the way this is built (i.e., no horizontal padding) I think we need to find another solution. Maybe we could just place `<strong>` tags around the top three usernames for now?

**Comment by spMohanty** [comment]
@jsnrynlds : I think the idea was to strongly differentiate these top-N participants as a different group. This will definitely play a huge role in the motivation.

I think Kaggle does this really well, and I have personally seen the effect of just this when participating in some of the kaggle challenges.

You can have a look at : https://www.kaggle.com/c/data-science-bowl-2018/leaderboard
to see what I roughly had in mind.

**Comment by spMohanty** [comment]
@seanfcarroll : @jsnrynlds got unassigned automatically probably because of the whole org membership thing. So please ignore the “jason got unassigned” message.

**Comment by scarroll32** [comment]
Implemented https://github.com/crowdAI/crowdai/commit/a648d7f8673c3b0fc3e5c9358ae7e74454faf366
