### ISSUE TITLE
File submissions via webpage

### ISSUE THREAD

**Issue by ieggel** [crowdAI/crowdai#565]
For the CLEF challenges it would be highly appreciated if there was a possibility to upload submission files via a web page in addition to the python client.

**Comment by scarroll32** [comment]
- [x] Submissions remaining
- [x] Registered users only for submissions
- [x] File upload duplication
- [x] Cancel button
- [x] Create submission button visible before starting date

**Comment by scarroll32** [comment]
Fixed
