### ISSUE TITLE
Changes to challenge description markdown is not rendered

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#566]
@sean: I was trying to post a note about extending the round-2 submission deadline for WWW Music challenge to 22nd March. I updated the content, but the rendered markdown doesnt reflect the changes :-?

**Comment by spMohanty** [comment]
Same for a post I just created. The content is not being rendered : https://www.crowdai.org/topics/round-2-submission-deadline-extended-to-march-22nd-2018/discussion

**Comment by scarroll32** [comment]
OK I'll look into it urgently.

**Comment by scarroll32** [comment]
Fixed
