### ISSUE TITLE
Dataset from old challenge links to a broken link

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#568]
I tried downloading the `Test Data` from the PlantVillage Challenge, and I got an error that the specified key doesnt exist.

https://www.crowdai.org/challenges/plantvillage-disease-classification-challenge/dataset_files

**Comment by scarroll32** [comment]
The test data and sample submission files for PV are not in AWS in the correct location. 

The keys are still attached to the Rails table but only crowdai_train.tar is correctly linked. I think this key is the PV crowdai_test.tar: https://s3.eu-central-1.amazonaws.com/crowdai-prd/dataset_files/2ab88525-0eff-4e3f-807f-345e2901eedb/crowdai_test.tar

If so, it can be reattached. 

Is there another copy of the sample submission file somewhere?

<img width="1011" alt="screen shot 2018-03-09 at 10 49 51" src="https://user-images.githubusercontent.com/11340230/37201371-ceecb658-2387-11e8-85e1-517b5e01186d.png">

**Comment by scarroll32** [comment]
Fixed
