### ISSUE TITLE
EPFL logo broken on page footer

### ISSUE THREAD

**Issue by marcelsalathe** [crowdAI/crowdai#57]
See bottom of https://www.crowdai.org/challenges/learning-how-to-walk

**Comment by scarroll32** [comment]
Caused by https://github.com/crowdAI/crowdai/issues/55

Will fix asap

**Comment by scarroll32** [comment]
Closed https://github.com/crowdAI/crowdai/commit/cb4cf31d709e79c2edcd82cd7bf1c3c4fc103c70
