### ISSUE TITLE
Updates to crowdAI landing page

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#571]
Urgent updates needed to crowdAI for communication.

> We need to be able to highlight cool news like this on the landing page. We need to be able to blog. And we need a better explainer what crowdAI is.
> And we need to be able to put logos of companies and universities who have worked with us on the main page VERY prominently!

- [x] Blog
- [x] News ticker
- [ ] Landing page explainer
- [x] Partner logos on landing page
- [ ] Learn more page

**Comment by jsnrynlds** [comment]
Hi @seanfcarroll – just making a start on this. When you get a chance could you let me know eight partners that you'll be including? Cheers

**Comment by jsnrynlds** [comment]
Also, I think it will look much tidier if we use grayscale logos – is that okay?

**Comment by jsnrynlds** [comment]
@marcelsalathe @seanfcarroll Here's an initial look at introducing some of these elements to the homepage. I've also added smaller, red headings in all-caps to increase contrast.

Questionmark over whether we use colour or grayscale logos – I guess this will partly depend on the logos we're showing. 

![crowdai_home_desktop_v2 2](https://user-images.githubusercontent.com/1162939/37349038-6b4e39ac-26cd-11e8-948a-5d52b5e1a345.png)

**Comment by scarroll32** [comment]
I like it Jason, I agree it would be tidier with grayscale logos, but perhaps with the mouse over to reveeal colour like in AMLD.

@marcelsalathe @spMohanty What are your thoughts?

**Comment by marcelsalathe** [comment]
I like the color version...

PARTNERS should probably say USED BY

Thanks for implementing this asap!

**Comment by jsnrynlds** [comment]
Here's an updated version with pagination added to the partners section...

![crowdai_home_desktop_v2 3](https://user-images.githubusercontent.com/1162939/37642525-4d53aa98-2c15-11e8-8da8-fe757cd23857.png)

**Comment by jsnrynlds** [comment]
Alternative layout for latest blog posts...

![crowdai_home_desktop_v2 4](https://user-images.githubusercontent.com/1162939/37642932-da359baa-2c16-11e8-9beb-e4c43bb70da5.png)

**Comment by Sylvain-Bernard** [comment]
Prefer the latter for blog posts. Blog posts present but keeps focus on featured challenges without pushing them too far at the bottom of the page.

**Comment by jsnrynlds** [comment]
Me too, @XCaellaX.

Here's a design for the blog index page. I don't think we want to give ourselves the headache of looking for images for each blog post but adding the avatars here definitely helps visually and adds a human touch. Could potentially do this on the homepage although it's obviously going to push the challenges further down the page.

![crowdai_blog_desktop_v1 3](https://user-images.githubusercontent.com/1162939/37645070-abd8b290-2c1d-11e8-873c-3fee48709ba6.png)

**Comment by marcelsalathe** [comment]
I like it better too!

**Comment by scarroll32** [comment]
I like the last 2 screenshots.

**Comment by jsnrynlds** [comment]
@marcelsalathe @seanfcarroll Shall I go ahead and build these?

**Comment by marcelsalathe** [comment]
Yes!

**Comment by jsnrynlds** [comment]
@marcelsalathe @seanfcarroll I've started to look at the 'Used by' logo section but it's a bit fiddly as we don't have a traditional grid system in place. I can't really add one because of the way the horizontal padding is set up. 

There are options, but I'm wondering if I could build this so we cut down the number of logos shown at lower resolutions (possibly down to 4 on mobile devices)? This would keep it tidy, also, with only 1 row of logos ever shown.

**Comment by marcelsalathe** [comment]
@jsnrynlds I think that's fine - but in the this case maybe we should have a seperate usedby page, in addition, where we can list all the organizations that use(d) crowdAI, and have some kind of "see more" link...

I just want to avoid that if we show X logos, and X is a small number, people having the impression that it's used ONLY by X organizations.

**Comment by jsnrynlds** [comment]
Thanks @marcelsalathe – okay, we can use the 'See all' button to link to another page. Maybe we could change the title as well to indicate that this is only a selection of organisations?

**Comment by marcelsalathe** [comment]
Good idea!

**Comment by jsnrynlds** [comment]
@seanfcarroll Update: added 'used by' logos and blog to homepage. (Badges to follow at some point.)

Also added Blog index page.

**Comment by spMohanty** [comment]
<img width="672" alt="screen shot 2018-04-29 at 00 22 34" src="https://user-images.githubusercontent.com/1581312/39401354-74b49b9a-4b43-11e8-96b1-e4c1306d0a42.png">

@jsnrynlds : The state markers (in green, yellow and red) that are present in the screenshot you shared, do not seem to be included in the https://github.com/salathegroup/crowdai-templates repository. Is that intentional ?

I [wanted to use those state markers also for the Submissions page](https://github.com/crowdAI/crowdai/issues/684) (https://www.crowdai.org/challenges/mapping-challenge/submissions), particularly the grading status columne.
(graded -> green, initiated -> yellow, failed->red)

**Comment by scarroll32** [comment]
Implemented except for the state markers as above. https://github.com/crowdAI/crowdai/commit/42cbc9ca059f9e3de8b5cda40c54dc80588d0ed7

**Comment by jsnrynlds** [comment]
Hi @seanfcarroll – I'll take a look at those this week.

**Comment by jsnrynlds** [comment]
Added coloured badges to `atoms.html`

**Comment by scarroll32** [comment]
As per the design on the challenges page we will have:

red = running
yellow = starting soon
green = completed

<img width="663" alt="screen shot 2018-06-26 at 10 57 56" src="https://user-images.githubusercontent.com/11340230/41900836-d8a78bfc-792f-11e8-99f1-7f2870f5eec9.png">

**Comment by spMohanty** [comment]
@jsnrynlds @seanfcarroll : shouldnt we have green = running, yellow = starting soon, and red = completed ?

**Comment by scarroll32** [comment]
OK we will go with:

green = running
yellow = starting soon, draft
red = completed

**Comment by scarroll32** [comment]
Implemented
