### ISSUE TITLE
Install & integrate with Gitlab

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#572]

**Comment by scarroll32** [comment]
Install notes

https://about.gitlab.com/aws/

https://www.fabian-keller.de/blog/migrating-a-gitlab-instance-to-another-server

https://docs.gitlab.com/ee/university/high-availability/aws/README.html

http://www.thegreatcodeadventure.com/building-a-custom-oauth-strategy-for-doorkeeper/

**Comment by scarroll32** [comment]
- [x] Single sign on
- [ ] Email config
- [ ] Branding
- [ ] Gitlab backups
- [ ] Test data migration (to local)

**Comment by spMohanty** [comment]
The Gitlab backups, and email config are pretty straight forward in`gitlab.rb`

The branding one will be tricky though without venturing into the actual code. It does have some config options for the default theme, but for some reason the theme doesnt seem to change when i change it (and also reconfigure it). 
For now, getting one of the default themes to work is good enough, especially if we can find one which goes with the rest of the sites design. A longer term solution would be to write a theme of our own, but it would be a luxury not a necessity. 

Looking forward to have this live !!

**Comment by scarroll32** [comment]
```
sudo gitlab-ctl reconfigure 
sudo gitlab-ctl restart
sudo gitlab-ctl status
```

**Comment by scarroll32** [comment]
Tailing logs on Gitlab
```
sudo gitlab-ctl tail
sudo gitlab-ctl tail gitlab-rails
sudo gitlab-ctl tail nginx/gitlab_error.log
```

**Comment by scarroll32** [comment]
![screen shot 2018-03-15 at 15 37 38](https://user-images.githubusercontent.com/11340230/37470014-dea75cd6-2866-11e8-8157-d4c749245a4d.png)

**Comment by scarroll32** [comment]
```
https://gitlab.crowdai.org/users/auth/oauth2_generic/omniauth_error?error=Email+can%27t+be+blank%2C+Notification+email+can%27t+be+blank%2C+and+Notification+email+is+invalid
```

**Comment by scarroll32** [comment]
Interesting ...

<img width="1031" alt="screen shot 2018-03-15 at 20 42 13" src="https://user-images.githubusercontent.com/11340230/37487298-68e24efe-2891-11e8-84fe-45577c9118a4.png">

https://github.com/doorkeeper-gem/doorkeeper/blob/master/app/controllers/doorkeeper/authorizations_controller.rb

**Comment by scarroll32** [comment]
https://docs.gitlab.com/ce/integration/oauth2_generic.html

**Comment by scarroll32** [comment]
Single sign on working

**Comment by scarroll32** [comment]
Other items moved into their own issues. Closed.
