### ISSUE TITLE
Update the Winners section for all the challenges 

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#575]
In the challenge edit page, there should be a "Winners" tab, where you can list the winners of the completed challenges, and a small section of the prizes they received etc

**Comment by Sylvain-Bernard** [comment]
Is there a list of previous winners for all the completed Challenges?

**Comment by spMohanty** [comment]
@XCaellaX : We usually just put up a post in the discussion forum announcing the winners. A good example for the content that should go in the Winners section is this : https://www.crowdai.org/topics/official-results-we-have-a-winner/discussion

But for other challenges we can just start with listing down the winner names (top-3) in most cases from the Leaderboard.

**Comment by scarroll32** [comment]
Winner's tab is turned on with a checkbox.

<img width="931" alt="screen shot 2018-03-13 at 14 24 44" src="https://user-images.githubusercontent.com/11340230/37344315-5671eb1c-26ca-11e8-9b10-082c01fc0edc.png">
