### ISSUE TITLE
Sort challenges by number of participants

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#576]
Right now on the home page, and also on the challenges page we show the active challenges, then I am not sure about the ordering of the rest of the challenges.
So some challenges like the WWW Music Genre recognition challenge, Criteo Challenge do not show up there even if they had a pretty decent amount of participation.

**Comment by scarroll32** [comment]
On the home page we sort by featured sequence for precise control. On the challenges page we sort by status and date:

```
  default_scope {
    order("featured_sequence DESC,
            CASE status_cd
              WHEN 'running' THEN 1
              WHEN 'starting_soon' THEN 2
              WHEN 'completed' THEN 3
              WHEN 'cancelled' THEN 4
              WHEN 'draft' THEN 5
              ELSE 6
            END, created_at DESC")
  }
```



<img width="806" alt="screen shot 2018-03-13 at 14 21 11" src="https://user-images.githubusercontent.com/11340230/37344146-d8167f30-26c9-11e8-8cc9-201c2badb3f3.png">

**Comment by scarroll32** [comment]
Can this be closed? @spMohanty

**Comment by scarroll32** [comment]
Implemented
