### ISSUE TITLE
Sticky footer

### ISSUE THREAD

**Issue by jsnrynlds** [crowdAI/crowdai#583]

**Comment by jsnrynlds** [comment]
Hi @seanfcarroll – I was wondering if we could make the footer sticky as it looks quite bad having whitespace underneath it on pages without much content (when viewed on screens with a higher res). Are you happy for me to look at this? As the body content already has a `.content` class applied to it, it shouldn't cause any problems.

I'm also going to decrease the size of the EPFL logo (https://github.com/crowdAI/crowdai/issues/609).

**Comment by scarroll32** [comment]
Hi @jsnrynlds no problem - please make any necessary changes and I'll integrate them.

**Comment by jsnrynlds** [comment]
Thanks @seanfcarroll – I've pushed to the templates repo. Also decreased the size of the EPFL logo.
