### ISSUE TITLE
404 - Documentation link - in crowdai github readme.md

### ISSUE THREAD

**Issue by Sylvain-Bernard** [crowdAI/crowdai#587]
![image](https://user-images.githubusercontent.com/15749650/37514137-593e4572-2907-11e8-9417-1623f16bb197.png)

don't know where it should link...

**Comment by scarroll32** [comment]
The docs will be migrated from the wiki into the README as linked files. Still a work in progress, so I have removed the link for now.

@spMohanty we also need to have a documentation sprint one of these days!
