### ISSUE TITLE
Raw ruby template missing error page giving out numerous internal platform specific stuff

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#59]
Ideally this link shouldnt throw such detailed errors in production mode : https://www.crowdai.org/challenges/learning-how-to-walk/leaderboards/video_modal?participant=yieldthought&score=875.386657&submission_id=171

**Comment by scarroll32** [comment]
Closed https://github.com/crowdAI/crowdai/commit/38aa9d3bf486672ea73ffd564bd61a98fba2127d
