### ISSUE TITLE
Weird text formatting on one discussion post

### ISSUE THREAD

**Issue by Sylvain-Bernard** [crowdAI/crowdai#591]
on https://www.crowdai.org/topics/we-have-a-winner-for-this-challenge/discussion, the **2000** is displayed as math/tex

![image](https://user-images.githubusercontent.com/15749650/37526317-4acde7e0-292f-11e8-8261-854f833fee5a.png)

**Comment by spMohanty** [comment]
Thats because the `$` signs confuse the renderer into thinking that the enclosed content is for MathJax.
I will investigate on how to escape it and fix it.

**Comment by spMohanty** [comment]
This needs a particular MathJax config, which I added (along with standardising the MathJax config) in this pull request : https://github.com/crowdAI/crowdai/pull/592

After this is live, we will be able to escape MathJax rendering for `$` by typing `\$` instead.

**Comment by scarroll32** [comment]
Implemented PR, but the issue is still there. Tried and edit & resave but no effect.

**Comment by spMohanty** [comment]
Thats weird. The relevant option for this was : `processEscapes`, and you can read about this here : http://docs.mathjax.org/en/latest/options/preprocessors/tex2jax.html#configure-tex2jax

Are you sure these configs are not being overridden by something else ?

**Comment by scarroll32** [comment]
Assigned to Florian @MasterScrat

**Comment by scarroll32** [comment]
Fixed

<img width="648" alt="screen shot 2018-06-28 at 16 38 31" src="https://user-images.githubusercontent.com/11340230/42041224-bb5f2578-7af1-11e8-9b5b-680c98f70586.png">
