### ISSUE TITLE
Replace Doorkeeper views with crowdAI styling

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#603]

**Comment by marcelsalathe** [comment]
And appropriate text ;-)

**Comment by scarroll32** [comment]
<img width="1083" alt="screen shot 2018-03-20 at 08 46 25" src="https://user-images.githubusercontent.com/11340230/37641764-424bd7f0-2c1b-11e8-907e-53064547af64.png">

**Comment by scarroll32** [comment]
Implemented 

<img width="1163" alt="screen shot 2018-06-14 at 12 32 25" src="https://user-images.githubusercontent.com/11340230/41407220-096ed836-6fcf-11e8-97d0-373c8164e63b.png">
