### ISSUE TITLE
Gitlab is using the EC2 root disk

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#605]
There attached storage but gitlab not using it

<img width="1040" alt="screen shot 2018-03-19 at 16 38 42" src="https://user-images.githubusercontent.com/11340230/37605743-22debfae-2b94-11e8-9628-47fd74fc57e2.png">

**Comment by scarroll32** [comment]
Actually the storage doesn't seem to be properly attached

```
NAME    FSTYPE SIZE MOUNTPOINT LABEL
xvda             8G
└─xvda1 ext4     8G /          cloudimg-rootfs
```

**Comment by spMohanty** [comment]
Have setup and configured it to use an external mounted volume.
Reference : https://docs.gitlab.com/omnibus/settings/configuration.html#storing-git-data-in-an-alternative-directory

**Comment by scarroll32** [comment]
Closed
