### ISSUE TITLE
Gitlab update needed

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#606]
Already! Let's at all configured and the backups working before doing any updates.

<img width="348" alt="screen shot 2018-03-19 at 16 42 23" src="https://user-images.githubusercontent.com/11340230/37605912-8e35b0e6-2b94-11e8-9385-fcb9427088b8.png">

**Comment by scarroll32** [comment]
It's now marked as "updated asap". We need to review / test the backup process before doing an upgrade.

<img width="349" alt="screen shot 2018-03-31 at 15 47 01" src="https://user-images.githubusercontent.com/11340230/38163844-dd7ac58c-34fa-11e8-9759-439c39248d6d.png">

**Comment by scarroll32** [comment]
Memory is also high 
<img width="678" alt="screen shot 2018-04-09 at 09 29 16" src="https://user-images.githubusercontent.com/11340230/38485087-f3454916-3bd8-11e8-86ab-5d58ec21b331.png">

**Comment by spMohanty** [comment]
Updated gitlab to `10.7-ce`.
