### ISSUE TITLE
Possibly decrease EPFL logo-size in footer

### ISSUE THREAD

**Issue by jsnrynlds** [crowdAI/crowdai#609]
@marcelsalathe Looking at this it feels a bit _too_ big to me. What do you think?

<img width="1240" alt="screen shot 2018-03-20 at 08 18 10" src="https://user-images.githubusercontent.com/1162939/37643112-642100e8-2c17-11e8-83c9-961347ddfa6d.png">

**Comment by marcelsalathe** [comment]
yes, I could be decreased a bit.
