### ISSUE TITLE
Enable `round_id` specification in external_grader_api

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#611]
The [external_grader_api](https://github.com/crowdAI/crowdai/blob/master/app/controllers/api/external_graders_controller.rb) currently "predicts" the round based on the [get_challenge_round](https://github.com/crowdAI/crowdai/blob/598abafe7edbf4a8b42a84a6240de48421d3faa8/app/controllers/api/external_graders_controller.rb#L32) function.

This does not allow the grader to submit scores for previous rounds.

During the course of a challenge, multiple datasets are released across multiple rounds, and each of them have a different `ground_truth`, hence their scores are not comparable. So ideally a submission made on the dataset of a particular round, should be presented on the leaderboard of that round.

If the grader can pass a `challenge_round_id` parameter, then during the "prediction" of the round_id [here](https://github.com/crowdAI/crowdai/blob/598abafe7edbf4a8b42a84a6240de48421d3faa8/app/controllers/api/external_graders_controller.rb#L32), 
a conditional checks if a `challenge_round_id` key is present in `:params`, 
if `True`,
then it is used.
else if `False`
then the `get_challenge_round_id` function takes over and does what it is already doing.

More concretely, I will just be passing `challenge_round_id` = `0` or `1` or `2` along with the other parameters in the payload [here](https://github.com/crowdAI/IEEEStockPredictionChallenge_job_factory/blob/master/helpers.py#L31)

The ability to specify `challenge_round_id` during the creation of a submission, will allow the grader to parallely grade submissions of different rounds at different points of time.
This will also enable us to have the graders for all the rounds live for all challenges in the past.

From the client side, it will **finally** look like : 
```python
import crowdai
API_KEY = '<your_crowdai_api_key_here>'
challenge = crowdai.Challenge('WWWMusicalGenreRecognitionChallenge', API_KEY)
response = challenge.submit('data/submission.csv', round=1)
print(response['message'])
```
but for now, we will keep it transparent to the users, and let the grader decide (based on the number of entries in `submission.csv`, which round it belongs to.

In terms of immediate needs, it will enable us to continue accepting solutions for the `round-1` of the WWW Music Classification Challenge, while actually on the challenge page `round-2` is in progress (which will be graded at the end of the round).

In future challenges, we will have different `job_factories` for different rounds of the challenges, and ensure that any user can submit a solution for any round of the challenge at any point of time. 
And that is how, we can entertain the possibility of the crowdAI leaderboards being a long-running benchmark for all these problems.

**Comment by scarroll32** [comment]
Turned out to be a bit trickier than expected. 

The challenge_round_id can be passed in the params hash now, and if present will be used to create the submission. The round_id is verified if it exists or is rejected.

The challenge_round_id is a database level id field, so must be first queried by the broker API to get the correct value. Two new endpoints have been created:

All challenges
```
/api/challenges 
```
Get the individual challenge along with a hash of all challenge_rounds; needs a valid challenge_id.
```
/api/challenges/:id
```

So query those endpoints to find the challenge_round_id, and pass it into the API. These endpoints are available only to the crowdAI master API key.

https://github.com/crowdAI/crowdai/pull/616

**Comment by scarroll32** [comment]
Implemented
