### ISSUE TITLE
Possibility to provide metadata via web page submission

### ISSUE THREAD

**Issue by ieggel** [crowdAI/crowdai#612]
When a participant uploads a submission file it is important that they can also provide additional information on the submission. In previous years we always had the following fields:

1. **Method description** (Text area)

2. **Retrieval type** (Dropdown) with following values:
  - Visual
  - Textual
  - Mixed (textual + visual)
  - Not applicable

3. **Run type** (Dropdown)
  - Automatic
  - Feedbacl or/and human assistance
  - Manual

4. **Primary run** (Chechbox) => values: true/false

5. Other information on run (Text area)

6. Additional resources used (Text area)

All points in bold are required tobe specified by the participants upon submission
Points that are not in bold can be left empty

**Comment by scarroll32** [comment]
Is this for all *clef challenges?

**Comment by ieggel** [comment]
Yes, we can use this for all *clef challenges.

**Comment by scarroll32** [comment]
Implemented
