### ISSUE TITLE
Download of all submission metadata and submission files

### ISSUE THREAD

**Issue by ieggel** [crowdAI/crowdai#614]
An organizer should be able to download all metadata of valid (graded) submissions for a given challenge. This should be implemented with an API. The response should also include an S3 URL for each submission. 

To do:
- Create API
-  Return json response including S3 URLs for submission files

Example:
`
{
  "challenge_name": "ImageCLEF Tuberculosis Severity Scoring",
  "submissions":
  [
     {
        "participant":"ivan.eggel@hevs.ch", 
        "submission_file_name":"submission1_ivan.csv", 
        "s3_submission_file_url": "https://s3.amazon.com/crowdai/submissions/abcdefg.csv"
         "meta":{
                     "method_description":"my method description abcdefg", 
                     "retrieval_type":"automatic", 
                     "run_type":"Automatic",
                     "primary_run":true,
                     "other_information":"my other information abcdefghijklmnop",
                     "additonal_resources_used":"wikipedia images"
          }
    },
    {"participant":"participant2@test.com, ... , ... ,"meta":{... , .., ...}},
    {....},
    {....}
  ]
}
`

**Comment by scarroll32** [comment]
Hi @ieggel we can do this, but in my opinion it would be better to provide json-structured data like this via an API endpoint. Is there any reason we cannot?

**Comment by ieggel** [comment]
@seanfcarroll
Yes, this would be possible as well.  Either way is OK for me.

**Comment by scarroll32** [comment]
Implemented
