### ISSUE TITLE
Secure access to leaderboard

### ISSUE THREAD

**Issue by ieggel** [crowdAI/crowdai#617]
Secure the access to the leaderboard. Currently if someone knows the URL he/she could still access the leaderboard.

The leaderboard  should only be accessible if:
- challenge.show_leaderboard is true
- OR current_user.organizer_id = challenge.organizer_id

Thank you Sean

**Comment by scarroll32** [comment]
Needs to be enforced at the policy level so the url cannot be directly accessed.

**Comment by scarroll32** [comment]
Fixed with a hack
