### ISSUE TITLE
Outdated browser

### ISSUE THREAD

**Issue by jsnrynlds** [crowdAI/crowdai#623]
@marcelsalathe @seanfcarroll as we're using flexbox (and other CSS3 rules that don't work in older browsers), I'm wondering if we should implement something like http://outdatedbrowser.com/en – thoughts?

**Comment by scarroll32** [comment]
I think we can go with modern browsers only @jsnrynlds, we have already started down that road. In any case we would expect our audience not to be running out of date browsers.

**Comment by jsnrynlds** [comment]
@seanfcarroll Okay, just a thought :)
