### ISSUE TITLE
Render `round_id` in the webinterface 

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#628]
When setting up a new challenge, it might be worthwhile to render the `round_id` for a particular round in the web interface itself. This can be used by whoever is setting up the job factories to add the relevant id to the configuration.

In contract to the series of API calls that you have to do now and manually inspect.

**Comment by scarroll32** [comment]
Will display for admins only. The API calls also give you other information about the rounds which should be used to determine which round the entry goes into.

**Comment by scarroll32** [comment]
<img width="741" alt="screen shot 2018-03-22 at 09 19 34" src="https://user-images.githubusercontent.com/11340230/37758898-2aff45f8-2db2-11e8-9136-c5335093c7ab.png">
