### ISSUE TITLE
can't see challenges in admin view

### ISSUE THREAD

**Issue by marcelsalathe** [crowdAI/crowdai#64]
Getting this error:

<img width="1052" alt="screen shot 2017-02-26 at 3 38 30 pm" src="https://cloud.githubusercontent.com/assets/215057/23340616/b42e0356-fc39-11e6-9079-927a927f3cbd.png">

**Comment by scarroll32** [comment]
Related https://github.com/crowdAI/crowdai/issues/63

ActiveAdmin is not fully configured. Will deal with it this week.

**Comment by scarroll32** [comment]
Closed https://github.com/crowdAI/crowdai/commit/c8055c5af88867556c7e9c9cfcfd7d48ec090c8a
