### ISSUE TITLE
Setup a unique DOI for every challenge ?

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#646]
Guess once a challenge is designed, we will have to manually put together all the content we prepare and create a new DOI on something like [Zenodo](https://zenodo.org/).

THen we can probably have a configurable parameter in the edit challenge interface, where we fill in the DOI.
And the relevant citation blocks etc are added to the Challenge Overview page.

**Comment by scarroll32** [comment]
Do you mean the challenge description would be developed on Zenodo and then copied to crowdAI when ready? I don't quite understand.

**Comment by spMohanty** [comment]
@seanfcarroll : no this will be a part of the challenge setup workflow. Where we ask organisers to setup a zenodo entry with everything they prepared for the challenge. And we just include the relevant doi in the challenge overview page. I dont think there will be any effort in terms of development here. We just have to formalise the guidelines for this process.

**Comment by scarroll32** [comment]
@XCaellaX let's discuss further, but I think you can be involved in driving this.

**Comment by scarroll32** [comment]
Closed as not work on the web app.
