### ISSUE TITLE
Draft challenges publicly visible

### ISSUE THREAD

**Issue by marcelsalathe** [crowdAI/crowdai#652]
I'm seeing this, not logged in, at https://www.crowdai.org/participants/spmohanty:

<img width="457" alt="screen shot 2018-03-31 at 08 27 08" src="https://user-images.githubusercontent.com/215057/38160409-89bedbfa-34bd-11e8-9ccb-27c075dfc0ea.png">

**Comment by scarroll32** [comment]
Fixed
