### ISSUE TITLE
AI generated music challenge evaluation page layout messed up 

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#655]
<img width="1609" alt="screen shot 2018-04-01 at 23 15 42" src="https://user-images.githubusercontent.com/1581312/38177480-b44ebb1a-3602-11e8-905d-6b499b419fcc.png">

@seanfcarroll : Were there any changes to the react component that is deployed ? or the way it is deployed ?

**Comment by scarroll32** [comment]
The component itself hasn't been modified, and I've been through the past 10 or so commits of crowdAI core and cannot see any changes to global styling which might affect this component. 

That is the most likely possibility of what happened though - this component is enclosed inside the main app (not an iFrame) and therefore would affected by global styles or parent html structure.

I did notice there is a style of **undefined** in the component - is that new? 

<img width="638" alt="screen shot 2018-04-02 at 09 49 32" src="https://user-images.githubusercontent.com/11340230/38188244-65df7f42-365b-11e8-9f54-344cdf5ab521.png">


If I click off the **display: flex** property on rct-grid-row that makes it look OK, although not as it was ( I think the keyboard was bigger).

@spMohanty as a quick fix, I suggest you change that in the component & I can do a new deploy. After the break we can ask Jason to look at all of the styles and how they might be interacting.

<img width="1156" alt="screen shot 2018-04-02 at 09 59 10" src="https://user-images.githubusercontent.com/11340230/38188510-8db96996-365c-11e8-8281-f44c3a2ef3e3.png">

**Comment by spMohanty** [comment]
okay, so for reference, this issue has been resolved by [this commit](https://github.com/crowdAI/crowdai-music-evaluation-interface/commit/e936eb64ab4d96bcb02fca3b7390eeb31eab5d50).
We temporarily added a new css rule to fix this. But this actual cause of the issue still needs to be investigated.

**Comment by scarroll32** [comment]
Deployed 0.1.0 of crowdai-music-evaluation-interface with a quick patch, thanks @spMohanty !

Needs further investigation as to what actually happened. Downgraded to a low.

**Comment by scarroll32** [comment]
Closing as no longer an issue.
