### ISSUE TITLE
Use tagging does not work properly in the discussion forum

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#656]
When we create a new topic in the discussion forum, here are a few observations.
- user tagging doesnt work inside the topic-body.
- it works great on subsequent comments.
- it does not work when editing a particular comment.

-Low Priority : The styling of the suggesstions is in blue, it would be great to change that color to the crowdai-red from the crowdai theme. :)

**Comment by spMohanty** [comment]
Related to https://github.com/crowdAI/crowdai/issues/683

**Comment by scarroll32** [comment]
Fixed
