### ISSUE TITLE
Ability for organisers to "edit" a submission

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#657]
We would need this for a proposed policy in the IEEE Investment Ranking Challenge (@seanfcarroll you ll be cc'ed in that email), and this is a request that we have been getting more and more. 

If implementing an interface is a problem, and its not a big issue to [implement GraphQL](https://github.com/crowdAI/crowdai/issues/621), then I can modify the crowdai python client to have an "Admin/Organisers" interface.  Where they can programmatically modify submissions using a few API calls.

**Comment by scarroll32** [comment]
Hi @spMohanty what does edit a submission mean?

**Comment by spMohanty** [comment]
@seanfcarroll : by edit I meant that organisers should be able to update the scores for a submission. This is critical in case where organisers might decide to penalise certain submissions, like in case of IEEE challenge

**Comment by scarroll32** [comment]
OK

**Comment by scarroll32** [comment]
score fields + description

**Comment by scarroll32** [comment]
Implemented https://github.com/crowdAI/crowdai/commit/a648d7f8673c3b0fc3e5c9358ae7e74454faf366
