### ISSUE TITLE
Ability to embed youtube videos in the leaderboard media column

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#658]
This will be required for the VizDoom 2018 challenge.

**Comment by scarroll32** [comment]
Are there any example videos available ? @spMohanty

**Comment by spMohanty** [comment]
@seanfcarroll  : https://www.youtube.com/watch?v=94EPSjQH38Y

**Comment by scarroll32** [comment]
Implemented

**Comment by spMohanty** [comment]
For future reference, the payload should have at least the following (along with other necessary fields like score, etc): 
```python
{
    "media_large" : "94EPSjQH38Y",
    "media_thumbnail" : "94EPSjQH38Y",
    "media_content_type" : "video/youtube"
}
```

**Comment by spMohanty** [comment]
So,
On my first request with `media_large` and `media_content_type` set, I got the following error : 
```
crowdai_api.exceptions.CrowdAIRemoteException: Either all or none of media_large, media_thumbnail and media_content_type must be provided.
```
and then when I added a dummy value to `media_thumbnail`, I get the error : 
```
crowdai_api.exceptions.CrowdAIRemoteException: The specified key does not exist.
```

**Comment by scarroll32** [comment]
Oh yes, that's because for other media types the grader was first uploading the file to S3, and the API checks if it is there. I'll add an exemption for "video/youtube"

**Comment by scarroll32** [comment]
Actually it should have been OK, I added a test against this and it is working on the POST. Are you sending a score & round?

```
  {
        challenge_client_name: challenge.challenge_client_name,
        api_key: participant.api_key,
        grading_status: 'graded',
        score: 0.9763,
        media_large: "94EPSjQH38Y",
        media_thumbnail: "94EPSjQH38Y",
        media_content_type: "video/youtube"
      }
```

**Comment by spMohanty** [comment]
@seanfcarroll : I was sending the score, and not the round.
I will try this now and get back to you.

**Comment by scarroll32** [comment]
Hang on - I found something else. 5 mins.

**Comment by scarroll32** [comment]
Implemented
