### ISSUE TITLE
Occasional CSS rendering issue

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#659]
On occasional refreshes, I get a screen like this : 
(Note the different styling of the links)
<img width="1348" alt="screen shot 2018-04-04 at 18 35 26" src="https://user-images.githubusercontent.com/1581312/38321238-4018d65e-3837-11e8-9c71-a19212ed3957.png">

Checking the console, I see this : 
<img width="1909" alt="screen shot 2018-04-04 at 18 36 09" src="https://user-images.githubusercontent.com/1581312/38321251-4aed1eaa-3837-11e8-932c-38ac8332734f.png">

**Comment by scarroll32** [comment]
Fixed https://github.com/crowdAI/crowdai/commit/42cbc9ca059f9e3de8b5cda40c54dc80588d0ed7
