### ISSUE TITLE
Challenges sorting

### ISSUE THREAD

**Issue by marcelsalathe** [crowdAI/crowdai#66]
Challenges should be sorted with the news on top (sort by start date) - at the moment the new challenges are at the bottom of the list:

<img width="703" alt="screen shot 2017-02-26 at 4 03 20 pm" src="https://cloud.githubusercontent.com/assets/215057/23340837/5743a2aa-fc3d-11e6-9d7f-1e6f3d790840.png">

**Comment by scarroll32** [comment]
Closed https://github.com/crowdAI/crowdai/commit/cb0f56ba547a74e509d3d5ec73869c5f015478ac
