### ISSUE TITLE
Homepage background image missing

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#669]
<img width="1592" alt="screen shot 2018-04-06 at 19 39 21" src="https://user-images.githubusercontent.com/1581312/38435562-44b6576c-39d2-11e8-9448-212505f1213c.png">

The grey dotted globe that we had on the homepage seems to be missing now.
Is it a bug ? or intentional ?
(I loved it 😢  )

**Comment by marcelsalathe** [comment]
Bug #573
