### ISSUE TITLE
CrowdAI Hall of Fame 

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#670]
A list of contributors, challenge winners to motivate participants to be involved in the community.

**Comment by scarroll32** [comment]
Jason to design, after group discussion of what it should look like. I think this is a great idea, especially if we consider both scores achieved as well as contributions made. This aspect is one which GitLab do very well. http://contributors.gitlab.com/

<img width="1198" alt="screen shot 2018-06-22 at 11 57 55" src="https://user-images.githubusercontent.com/11340230/41770806-87ccf1a0-7613-11e8-946e-289174a4b49e.png">

**Comment by scarroll32** [comment]
Let's close this, it will re-appear if necessary after the badges are implemented.
