### ISSUE TITLE
A customisable note which can go on top of the leaderboard

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#675]
In many cases during the challenge the organisers would want to add some note/clarification to the top of the leaderboard.
Making it a configurable message in the challenge edit page will be beneficial.

Ideally it should be rendered somewhere here : 

<img width="1270" alt="screen shot 2018-04-08 at 17 52 26" src="https://user-images.githubusercontent.com/1581312/38469474-a1ce1c80-3b55-11e8-80a8-a2ae8f8639ff.png">

**Comment by scarroll32** [comment]
A small panel with a closable 'x' would work.

**Comment by scarroll32** [comment]
Implemented

**Comment by spMohanty** [comment]
@seanfcarroll : I could not figure out how to add the note on top of the leaderboard ?

**Comment by scarroll32** [comment]
- [x] Markdown field at the challenge round level
- [x] If blank ignore 
- [x] Style as alert (info)
- [x] Place between pills and head of leaderboard

**Comment by scarroll32** [comment]
As discussed, this will now be at the challenge round level. Will eventually need some design work.

**Comment by scarroll32** [comment]
Implemented
