### ISSUE TITLE
An easy way to see all the unanswered questions on all the discussion forums

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#676]
Viewable in the admin and also for the organizers.

**Comment by spMohanty** [comment]
We have been consistently missing out on a lot of forum posts that have been made across many challenges.
Atleast until this feature is implemented, I would be happy if I get an email for every post/comment that is made anywhere on crowdai. (A link to the actual page would make life a bit more easy :D )

We recently found some posts which were made like weeks ago and were left unanswered, and this very much means that we are losing the interests of those participants.

**Comment by scarroll32** [comment]
An email has been instituted.
