### ISSUE TITLE
Submission metadata API missing fields

### ISSUE THREAD

**Issue by ieggel** [crowdAI/crowdai#677]
We should add the following to the response JSON:
- More participant information: Email, name, first_name, last_name, affiliation
- query param that defines the submission status and filters submissions accordingly

**Comment by spMohanty** [comment]
This would make our lives much easier : https://github.com/crowdAI/crowdai/issues/621

**Comment by ieggel** [comment]
@spMohanty 
For the time being I adapted the REST API. It does what we need right now, but yes, the GraphQL solution seems to be a better solution in such cases in general.
