### ISSUE TITLE
Create Submission button on non clef challenges creating confusion

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#678]
https://www.crowdai.org/topics/unable-to-submit/discussion

**Comment by scarroll32** [comment]
It's now a configuration setting "Submissions page visible", I just turned it off for IEEE.

<img width="848" alt="screen shot 2018-04-09 at 18 23 56" src="https://user-images.githubusercontent.com/11340230/38509812-49a3ad26-3c23-11e8-9e4d-b5c4c37f16c6.png">

**Comment by spMohanty** [comment]
Hey reopening it, 
as it needs a little bit more attention.

I manually turned off the submissions page for all the  (non-clef) challenges.
But this also took away the Submissions-tab, which is something I personally review almost everyday to check the activity in a challenge.

I think both should have two different options.
* Submissions Page Visible ?
* Create Submission Button Visible ?

**Comment by scarroll32** [comment]
Ok added a new config field called 'Online Submissions?'. The create submission button will only appear when the challenge is open (Clef and non-clef) and this checkbox is pressed.

For admins, the submit button will appear when the challenge has not started if the online submissions checkbox is pressed.

CC to @ieggel - I have already updated the checkbox for all Clef challenges.


<img width="789" alt="screen shot 2018-04-10 at 10 45 55" src="https://user-images.githubusercontent.com/11340230/38546237-670c1022-3cac-11e8-9be3-870105fa7567.png">
