### ISSUE TITLE
Configurable number of significant digits when ranking submissions on leaderboard

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#682]
Now say participantA makes a submission which has a score of : `0.123456`, and participantB makes a submission which has a score of : `0.123457`. Now the difference between both these submissions might not be significant enough. So when ranking , we should be able to consider a configurable number (the same one that is showed, say 3).
And when producing the actual rankings we use only the signifcant digits to come up with ranking
In this example, by replacing them with only the significant digits, the score will be : 
0.123 and 0.123, which are equal, so their rank will be decided by the secondary score.

And if the secondary scores (after considering the number of significant digits) is the same, then they will have the same score.

Implementational details : 
we retain the `score` and `score_secondary` fields, add try to add `attribute_methods` which will return the "render_safe and rank_safe" values when `score` or `score_secondary` values are accessed with a prefix/suffix. 

These render_safe and rank_safe values will respect the configurable number of significant digits for both the scores, and will be used by the leaderboard for rendering and ranking.

The default value for the number of significant digits for both the values should be `3`.

Relevant discussions : 
* https://www.crowdai.org/topics/which-metric-will-be-used-for-the-final-rankings/discussion
* https://www.crowdai.org/topics/how-does-the-ranking-work/discussion

**Comment by scarroll32** [comment]
Yep, it's coded but not properly tested. https://github.com/crowdAI/crowdai/compare/rankings?expand=1

**Comment by spMohanty** [comment]
<img width="1198" alt="screen shot 2018-04-11 at 19 51 10" src="https://user-images.githubusercontent.com/1581312/38634045-bad8bdf2-3dc1-11e8-852a-fa3487babd7c.png">

Then it would be great if we can test it and put it up on production.
In the screenshot above, we see a case where the participant who should have rank 1 has rank 2, just because of the absence of consideration for significant digits in the score.

Adding high priority to this, as I believe we will see more and more of this in the IEEE Investment ranking challenge.

**Comment by scarroll32** [comment]
Implemented https://github.com/crowdAI/crowdai/commit/a648d7f8673c3b0fc3e5c9358ae7e74454faf366
