### ISSUE TITLE
Color code submission entries on "submissions" page

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#684]
The submissions page currently looks something like this : 

<img width="1144" alt="screen shot 2018-04-11 at 01 21 33" src="https://user-images.githubusercontent.com/1581312/38588530-b6baeca4-3d26-11e8-8869-ba5fc6178c94.png">

It would be great to color code each of the submissions page based on the status.
The life cycle of a submission roughly follows the following states : 
"submitted" -> "initated" -> ["failed", "graded(successfully)"]

We could color code the submitted and initiated as orange/yellow, failed as red and graded as green.

**Comment by spMohanty** [comment]
https://github.com/crowdAI/crowdai/commit/e598d3ab9e5003ba7d96d5324c1da75d2eb419ce implements the color coding for the grading status.

The colors (red, green, yellow) are picked from this screenshot https://github.com/crowdAI/crowdai/issues/571#issuecomment-374510836 by @jsnrynlds .

Also linked the grading status message to the individual challenge page, as for all the challenges with the gitlab based grader, thats were the grader log feedback will be provided to the participants. So it has to be very obvious for them to find the page.
The X symbol at the end of the row also serves the same purpose, but is a bit less obvious in general, and hard to notice until you are told about it.

The final screenshot after this commit looks like : 
<img width="1302" alt="screen shot 2018-04-30 at 00 27 20" src="https://user-images.githubusercontent.com/1581312/39411592-4fa6f08a-4c0d-11e8-9528-aecfbd582c80.png">

**Comment by scarroll32** [comment]
Looks great!

**Comment by scarroll32** [comment]
Implemented
