### ISSUE TITLE
Include links in a "submission message"

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#685]
In the new gitlab based architecture, on submission of code, we will be building an image from their code, and then testing it on a small sample test case to ensure everything works.
A lot of things can go wrong, and hence its important to provide feedback to the participants in form of logs, so they can reiterate themselves without our intervention.

I can make the logs available on a separate link, and include a link to it in the submission message if we agree on a way in which I can safely pass links in the message field (if we are not already filtering out html tags from the message by default, then we are open to CSRF attacks)

It complements this issue https://github.com/crowdAI/crowdai/issues/684 issue implemented, to make the whole participation experience much better for participants.

**Comment by scarroll32** [comment]
Has been implemented, it seems to be broken.

**Comment by scarroll32** [comment]
As agreed, this is what we will do

- [ ] grader will send a new key **grader_logs** into the existing meta hash via the API, updating as frequently as necessary. No changes needed from the API.
- [ ] contents of meta will be extracted and wrapped in an instance of [Codemirror](https://codemirror.net/) on the detail page 
- [ ] logs will be viewable by all users, so sensitive data will be scrubbed before being sent 
- [ ] Users can do page refreshes to see updates, later we can do a push via ActionCable (Rails implementation of websockets)

**Comment by scarroll32** [comment]
Updated, due to limits on the POST size, we are now storing the logs in AWS. There is a new checkbox on the challenge configuration, "Grader Logs?". If this is checked, S3 will be checked for a key following the format below.

Logs should be stored as: 

```
crowdai-prd/grader_logs/[challenge_slug]/[grader_logs_submission_id].txt
```

<img width="990" alt="screen shot 2018-04-23 at 10 16 15" src="https://user-images.githubusercontent.com/11340230/39114546-70773d20-46df-11e8-8335-ee5a56511b7d.png">

**Comment by scarroll32** [comment]
Looking good!
<img width="926" alt="screen shot 2018-04-23 at 11 10 54" src="https://user-images.githubusercontent.com/11340230/39117362-102d2292-46e7-11e8-82c8-c076e5ec6524.png">

**Comment by spMohanty** [comment]
Looking great indeed !
Will send some real data later today.

**Comment by scarroll32** [comment]
Note the changes in spec - the page will look for a specific key based on the challenge slug and submission id, and not use the meta as previously discussed.

```
crowdai-prd/grader_logs/[challenge_slug]/grader_logs_submission_[submission_id].txt
```

Should be live soon.

**Comment by scarroll32** [comment]
Implemented.
