### ISSUE TITLE
API endpoint to get participant API key from participant user name

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#686]
The gitlab based grader will receive the participant username when we get a submission.
The rest of the crowdAI API's require the participant API key to add scores etc.

While the GraphQL (https://github.com/crowdAI/crowdai/issues/621) based approach is the best approach IMO, but for now, we will need an endpoint which can return the API key of the participant if the grader provides the username.

**Comment by scarroll32** [comment]
Isn't that a security risk? The API key is essentially the password.

**Comment by spMohanty** [comment]
It will ofcourse be authenticated by the crowdAI grader key.
If someone has to bypass the authentication. They will need the grader api key, and if they have it, then we have a bigger problem than the leak of a participants API key

**Comment by scarroll32** [comment]
Implemented https://github.com/crowdAI/crowdai/pull/705/commits/a9b28afe5e0933311fabcc9bd95cd832a92d684a

/api/participants/[name] with the crowdAI master API key.
