### ISSUE TITLE
Implement a python package for all crowdAI API calls

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#687]
Implement a separate python package which wraps all the API calls to crowdAI from grader related services. This will let us also easily test the API from the graders end, and during subsequent developments.

Also related to https://github.com/crowdAI/crowdai/issues/686 https://github.com/crowdAI/crowdai/issues/562

**Comment by scarroll32** [comment]
Is this closed? @spMohanty

**Comment by spMohanty** [comment]
Yeah I have one version released. https://pypi.org/project/crowdai-api/0.1.1.dev1/

But I would keep this issue open until there is a stable release out with all the basic features we need, and documentation sorted out (now the documentation is in markdown which pypi doesnt really like as you can see if you follow the link above)

**Comment by scarroll32** [comment]
downgraded

**Comment by scarroll32** [comment]
The documentation rendering looks pretty bad, I think this should be fixed soon.

<img width="862" alt="screen shot 2018-06-22 at 11 00 11" src="https://user-images.githubusercontent.com/11340230/41768044-7fe2731e-760b-11e8-841c-99dbbbce7dc7.png">

**Comment by scarroll32** [comment]
bump @spMohanty

**Comment by scarroll32** [comment]
Closed
