### ISSUE TITLE
Discussion forum notifications

### ISSUE THREAD

**Issue by ieggel** [crowdAI/crowdai#688]
It would be nice if challenge organizers get an e-mail notfication if somebody posts on their discussion forum.

**Comment by spMohanty** [comment]
I am marking this as high priority, as this has been on the wishlist for ages, and now with a lot of things going on I personally start noticing that we dont have something like this already.

**Comment by scarroll32** [comment]
If the organizer follows the challenge they will receive these emails.

**Comment by scarroll32** [comment]
Closed as already possible
