### ISSUE TITLE
Leaderboard grouped entries 404

### ISSUE THREAD

**Issue by ieggel** [crowdAI/crowdai#690]
I've noticed that sporidically the own grouped entries (Entries column)  in the leaderboard cannot get populated.
Here the screenshot of the challenge in question, but i also noticed it in other clef challenges:
![image](https://user-images.githubusercontent.com/9192090/38625749-777c3c98-3dab-11e8-8ed6-b56ca4aebabf.png)

There is a 404 error when clicking on the entries:
![image](https://user-images.githubusercontent.com/9192090/38625916-cafb8270-3dab-11e8-9b0d-5fd245416a53.png)

This seems to happen sporadically. Sometimes after another submissions it seems to work again.

**Comment by scarroll32** [comment]
Thanks, I'll look into it. Have done another major refactor of the leaderboard, so I'll include this issue before pushing to production.

**Comment by scarroll32** [comment]
Fixed https://github.com/crowdAI/crowdai/commit/a648d7f8673c3b0fc3e5c9358ae7e74454faf366
