### ISSUE TITLE
Multiple links for the same challenge

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#693]
@seanfcarroll : It seems link there are multiple URIs for the same challenge.

For example : 
* https://www.crowdai.org/organizers/bethgelab/challenges/nips-2018-adversarial-vision-challenge
* https://www.crowdai.org/challenges/nips-2018-adversarial-vision-challenge
for the adversarial vision challenge.

Also, do we have URL re-routes when we change the name of a challenge ?
Because, I just changed the name of the challenge from `adversarial-vision-challenge` to `nips-2018-adversarial-vision-challenge`. If not, we should clearly communicate that to the organizers to avoid confusion.

**Comment by scarroll32** [comment]
This issue will go away when the multiple organizers are properly implemented. 

Regarding re-routing of challenge slugs - it is something that could be supported. I'll add it.

**Comment by scarroll32** [comment]
Fixed
