### ISSUE TITLE
Redesign the contact section

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#694]
So the contact section of every challenge holds most information about how to communicate with the rest of the participants and the organisers.
For now it looks like this for most challenges : 
<img width="815" alt="screen shot 2018-04-13 at 04 36 17" src="https://user-images.githubusercontent.com/1581312/38713990-58cbb164-3ed4-11e8-9cb9-597e9b4b2860.png">

Should we think about redesigning it to make the same information more digestible and easily noticable ?
We always have the link to : 
* a gitter channel
* a discussion forum
* contact emails of come of the core organisers

**Comment by scarroll32** [comment]
All of this is possible with Markdown
