### ISSUE TITLE
Error 500 for leaderboards of ended challenges

### ISSUE THREAD

**Issue by ieggel** [crowdAI/crowdai#699]
Hi @seanfcarroll 
It seems that navigating to a leaderboard of an eded challenge (e.g. NIPS) results in a 500 Error.

**Comment by scarroll32** [comment]
Hi Ivan, thanks for the error report. It's not happening for me - either loged in or not.

Are you logged in when this happens? Can you paste the url here.

**Comment by ieggel** [comment]
Only happens when logged in. Here the URL:
https://www.crowdai.org/challenges/nips-2017-learning-to-run/leaderboards

Probably has something to do with being an organiser. This did not happen a few days ago.

**Comment by spMohanty** [comment]
Many others seem to be having this issue : 
https://www.crowdai.org/topics/why-can-t-leaderboard-open/discussion

marking this as high priority.

**Comment by marcelsalathe** [comment]
I confirm - you have to be both non-admin, and logged in, to get the crash.

**Comment by englhardt** [comment]
Same here. It get an 500 error when accessing any leader board when logged in with an organizer account  as well as with one that is not. It also fails for running challenges and not only completed ones.

**Comment by scarroll32** [comment]
Patch to allow the leaderboards to work, will temporarily remove submission management access for Clef organizers https://github.com/crowdAI/crowdai/pull/702/commits/4777e7f1d651687263646d34e198ae2e58bc91ad

Full solution coming soon.

**Comment by scarroll32** [comment]
Full solution here: https://github.com/crowdAI/crowdai/commit/dc1532fd458f198c448b60e3c3bcbf6efabc2ef7

This will change again when we apply https://github.com/crowdAI/crowdai/issues/574
