### ISSUE TITLE
mp4 video of animated gif cannot be opened in some browsers

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#70]

**Comment by scarroll32** [comment]
You may need to use -pix_fmt yuv420p for your output to work in QuickTime and most other players. These players only supports the YUV planar color space with 4:2:0 chroma subsampling for H.264 video. Otherwise, depending on your source, ffmpeg may output to a pixel format that may be incompatible with these players.

https://superuser.com/questions/820134/why-cant-quicktime-play-a-movie-file-encoded-by-ffmpeg

**Comment by scarroll32** [comment]
Closed https://github.com/crowdAI/crowdai/commit/db99c0ea918c9a4d74fae0721a316f953323fd4f

**Comment by spMohanty** [comment]
@seanfcarroll : I could not open the videos on my Android phone. So changing the title of the issue, and reopening it.

**Comment by scarroll32** [comment]
but this is no longer being transcoded in Rails...

**Comment by spMohanty** [comment]
Yeah, so we can close this. 
I will deal with the transcoding in the grader.
