### ISSUE TITLE
Clef Refactor and full testing

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#703]
We need to re-think the Clef data model, and also merge the parallel objects. In theory, we should be able to abtract Clef via configuration settings instead of hard coding.

Full end-to-end testing of both scenarios is needed.

~ 1 week of work

**Comment by scarroll32** [comment]
@ieggel When will the next round of Clef challenges start? We would want the code completely refactored by then.

**Comment by ieggel** [comment]
Hi @seanfcarroll 

I think the registrations will start at the end of october.

Cheers,
-Ivan

**Comment by scarroll32** [comment]
Thanks Ivan.

**Comment by scarroll32** [comment]
Unlikely we will have capacity for this. Closing.
