### ISSUE TITLE
Winner's tab broken

### ISSUE THREAD

**Issue by Sylvain-Bernard** [crowdAI/crowdai#709]
**Input:**

![image](https://user-images.githubusercontent.com/15749650/39050287-1d6c1e66-44a5-11e8-8e7e-fd995f091b47.png)

**Expected (working in preview):**

![image](https://user-images.githubusercontent.com/15749650/39050296-2bb96d8e-44a5-11e8-89d3-6ccb6ec079e5.png)

**Result on page**

![image](https://user-images.githubusercontent.com/15749650/39050314-3c5c31f8-44a5-11e8-878c-ddf55d69c3dc.png)

**Comment by spMohanty** [comment]
This issue was happening because table, tr and td tags were stripped off by the `sanititzer`.
Header tags (h1, h2, h3, h5, etc) are still not allowed, so the rendering still looks a bit ugly.
and will probably have to be explicitly allowed.

**Comment by scarroll32** [comment]
Implemented

**Comment by Sylvain-Bernard** [comment]
Still not working...

![image](https://user-images.githubusercontent.com/15749650/39748407-4b34aec6-52b0-11e8-936c-e6fa4dd6768d.png)

**Comment by scarroll32** [comment]
Fixed
