### ISSUE TITLE
Rendering of Quoted text not working properly

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#711]
<img width="922" alt="screen shot 2018-04-21 at 14 10 38" src="https://user-images.githubusercontent.com/1581312/39083958-df550f7e-456d-11e8-9b28-e96628ded81f.png">

https://www.crowdai.org/topics/why-can-t-leaderboard-open/comments/new

In the message above, the block :
```@spMohanty: btw I could solve the issue with submitting by sending not encoded api string in interface (I have python 3.6). I just removed “if sys.version_info[0] == 3” condition and now it works```

is a quoted text, but the way it is rendered is confusing to get the context properly.

**Comment by scarroll32** [comment]
Fixed
