### ISSUE TITLE
Use challenge slug instead of id on AWS

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#712]
On AWS we currently use challenge id as the folder within each category, eg:

```
crowdai-prd/dataset_files/challenge_34/
```

It would be easier to work with S3 directly if we migrate to challenge slugs, ie:

```
crowdai-prd/dataset_files/test-challenge-ignore/
```

This would require both changing the code and renaming the folders. Some cleanup of S3 is also needed as we seem to have various orphan files and directories there, we are currently on 300GB for S3.

**Comment by spMohanty** [comment]
@seanfcarroll : But that opens up the risk that when someone changes the name of the challenge, then the challenge slug changes automatically, and we will have to move around all the relevant files on AWS to the new right location.

**Comment by scarroll32** [comment]
Agreed & closed
