### ISSUE TITLE
Render static notebooks in knowledge base

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#713]
Render these notebooks as Knowledge Base articles

- https://github.com/lindafarczadi/Selecting-data-in-pandas
- https://github.com/lindafarczadi/Slice-operator

Can be added to the repo as static text and rendered client-side using https://github.com/jsvine/notebookjs

**Comment by spMohanty** [comment]
@seanfcarroll : we can also use [nbpreview](https://github.com/jsvine/nbpreview) which has a lot more features. Or the official : https://github.com/jupyter/nbviewer

And for the first implementation, I think we should simply focus on client side rendering. Given an ipython notebook which is uploaded by the user, we simply render it using nbpreview or nbviewer or anything else like that.

With nbviewer, we can host our own nbviewer service, and point them to repositories on our custom gitlab instance.

**Comment by marcelsalathe** [comment]
Would very much want @jsnrynlds design input on that. We're going to rename the knowledge base into Dojo, and I think we need three levels of difficulty: beginner, intermediate, and advanced.

**Comment by scarroll32** [comment]
> With nbviewer, we can host our own nbviewer service, and point them to repositories on our custom gitlab instance.

Renga have developed an implementation of this, integrated with Gitlab and React code already written, they demo'd it last week. I think it would be good to use this as an integration point with the SDSC.

**Comment by scarroll32** [comment]
As discussed the 3 static notebooks will be added as hard-coded pages, into the Knowledge base with the authors indicated. Live notebooks will be implemented separately (and these existing ones migrated). Tracking of live notebooks is here https://github.com/crowdAI/crowdai/issues/715

**Comment by scarroll32** [comment]
https://github.com/lindafarczadi/Selecting-data-in-pandas

https://github.com/lindafarczadi/Slice-operator

https://mybinder.org/v2/gh/pacm/encoding-cat-vars-in-practice/master?urlpath=lab/tree/encoding-categorical-variables-in-practice.ipynb

**Comment by scarroll32** [comment]
Notebooks moved to Gitlab

* https://gitlab.crowdai.org/crowdai-dojo/Slice-operator
* https://gitlab.crowdai.org/crowdai-dojo/Selecting-data-in-pandas
* https://gitlab.crowdai.org/crowdai-dojo/encoding-cat-vars-in-practice

**Comment by scarroll32** [comment]
Implemented with nbviewer but there seem to be issues. Will leave open for discussion.

**Comment by spMohanty** [comment]
This does not work for me in firefox.
<img width="1913" alt="screen shot 2018-04-27 at 14 35 22" src="https://user-images.githubusercontent.com/1581312/39362856-3ea7103a-4a28-11e8-8af2-949fe077c2bb.png">

**Comment by scarroll32** [comment]
Closed as will be handled by SDSC integration
