### ISSUE TITLE
Add essential meta tags to all the pages

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#714]
When we share links to different pages right now, because of the lack of relevant meta tags, they dont render properly.
For example : 
<img width="896" alt="screen shot 2018-04-24 at 00 17 02" src="https://user-images.githubusercontent.com/1581312/39156112-11c9e28e-4755-11e8-9925-1593519e6e42.png">

More details about relevant meta tags : https://css-tricks.com/essential-meta-tags-social-media/
Some rails gems seem to deal with most of the heavylifting : 
* https://github.com/kpumuk/meta-tags
* https://github.com/lassebunk/metamagic

**Comment by spMohanty** [comment]
Related to : https://github.com/crowdAI/crowdai/issues/645

**Comment by scarroll32** [comment]
Added the https://github.com/kpumuk/meta-tags gem but it seems to have created only a title tag. Anyway it can be configured easily so let me know which tags are needed.

**Comment by spMohanty** [comment]
@seanfcarroll : Leaving this issue open, as the configuration has to be carefully thought through, and we will definitely forget about it if we close it.
I think the `image_src`  one is something we will need for sure. And it might be page specific. For example the crowdAI logo on most pages. Challenge logo on challenge leaderboard, submission page, discussion forum, etc. 
Submission page could have the image from the media field (if present), else the crowdAI or Challenge logo. Etc Etc.

Maybe @XCaellaX can give this one some thought ?

**Comment by scarroll32** [comment]
https://2017doneright.com/comprehensive-guide-on-seo-in-rails-8b124ca81d37

**Comment by scarroll32** [comment]
- https://css-tricks.com/essential-meta-tags-social-media/
- https://www.lewagon.com/blog/setup-meta-tags-rails

**Comment by scarroll32** [comment]
Working on Facebook

<img width="601" alt="screen shot 2018-08-27 at 12 57 26" src="https://user-images.githubusercontent.com/11340230/44656356-d5473f80-a9f8-11e8-941d-5ee0e635b74e.png">

**Comment by scarroll32** [comment]
Implemented
