### ISSUE TITLE
Padding in leaderboard entries

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#721]
<img width="1116" alt="screen shot 2018-04-26 at 07 27 08" src="https://user-images.githubusercontent.com/1581312/39287287-4a2d58ac-4923-11e8-83db-9ad358a927c6.png">

I think there should be some padding on the left and right side of the leaderboard entries.
The list item markers, and the expand submission icons are right at the edge, and they look weird.

**Comment by scarroll32** [comment]
Patched
