### ISSUE TITLE
Links to old knowledge base articles broken 

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#725]
Mostly because of the new notebook integration. 

Ex : https://www.crowdai.org/articles/plantvillage-image-classification-tutorial

**Comment by spMohanty** [comment]
<img width="972" alt="screen shot 2018-04-27 at 14 31 30" src="https://user-images.githubusercontent.com/1581312/39362716-b70e7208-4a27-11e8-9c09-5ba09255c167.png">

**Comment by scarroll32** [comment]
Fixed
