### ISSUE TITLE
CrowdAI emails not ending up in Primary inbox on Gmail 

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#73]
In my case, they end up in the "Promotions" section, while I do get a lot of emails which are actually promotions but they still end up in my Primary Inbox.
Would be a pity if people dont even get to notice our newletters, especially when its so low volume.

The submission made emails, and the forum notifications do end up in my primary inbox though.

**Comment by scarroll32** [comment]
These emails are coming directly from a Mailchimp campaign, where as the others are sent as transactional emails via Mandrill. Will look into it.

**Comment by scarroll32** [comment]
http://www.boldandzesty.com/how-to-avoid-promotions-tab-in-gmail/

Things that get us landed in promotions tab

- external links
- unsubscribe link
- images
- not calling the person by name 

The email newsletter *is* actually a promotion...
