### ISSUE TITLE
API create endpoint was silently ignoring the values inside `meta` key

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#737]
Can be confirmed here : https://www.crowdai.org/admin/challenges/ieee-investment-ranking-challenge/submissions/5394

While the calls were sending an object like : 
```
{
file_key : "s3_file_key"
}
```

The `params` object in the controller was getting `pararms[:meta]` as just `file_key`.
Hence we have lost the file_id mapping for many of the submissions in the recent challenges.

**Comment by spMohanty** [comment]
Modified all job_factories to serialize the `meta` key before sending it across.

**Comment by scarroll32** [comment]
Implemented
