### ISSUE TITLE
Submission page rows not vertically aligned

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#739]
<img width="1186" alt="screen shot 2018-04-29 at 22 53 51" src="https://user-images.githubusercontent.com/1581312/39411052-aa92305a-4c02-11e8-86de-9a020babfd0e.png">

while, we would want something more symmetrical. Along the lines of : 

<img width="1197" alt="screen shot 2018-04-29 at 23 14 21" src="https://user-images.githubusercontent.com/1581312/39411072-15799afc-4c03-11e8-91b5-dc4a66f6e7c9.png">

**Comment by spMohanty** [comment]
the reason was`vertical-align` for td was set to `top` instead of `middle`. 
(@jsnrynlds 's css uses vertical-align middle instead of top consistently)

And I removed the `pull-right` class which was doing a `float:right` [which messes up with `vertical-align`](https://stackoverflow.com/questions/11718134/css-vertical-align-does-not-work-with-float).

**Comment by scarroll32** [comment]
Implemented
