### ISSUE TITLE
Submission page (with comment ) broken

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#742]
If we add a comment to the individual submission page, then it throws a 500.

For example in this link : https://www.crowdai.org/challenges/25/submissions/5433

**Comment by scarroll32** [comment]
Fixed - that link won't work but go back to the leaderboard and it will now provide the right id

**Comment by spMohanty** [comment]
@seanfcarroll : the links on the submission page still use the numeric ids and not the slugs : https://www.crowdai.org/challenges/mapping-challenge/submissions
