### ISSUE TITLE
Add more information to the individual submission page 

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#744]
<img width="1284" alt="screen shot 2018-04-30 at 00 50 02" src="https://user-images.githubusercontent.com/1581312/39411731-721cbc28-4c10-11e8-94c8-a36421bdcc4b.png">

Currently its a bit confusing if someone lands up here.
Ideally we want to show the following information here : 
- Author
- Grading Status : submitted, initiated, graded, failed
- Score (with proper Score title)
- Score Secondary (with proper Score Secondary title)
- Any available Media (images, gifs, youtube videos? : if available )
- Share buttons + Copy Link buttons
- Grader_Logs (if available) (accessible only to the admins + author of submission + organizer of challenge)
- Comments 

- Link back to the actual challenge page
- the usual crowdAI header is also missing 😉 

These are the ones we need immediately for the VizDoom challenge launch this week. 
So making this a high priority.

This could use a little of of redesign by @jsnrynlds  after we implement a draft version, and have some data populated.

Ideas for later versions : 
- List of submissions by the same user in the same challenge (and their corresponding build states)
- OR, List of submissions by all the users in the same challenge (and their corresponding build states)
in a travis like format. https://travis-ci.org/crowdAI/crowdai

**Comment by scarroll32** [comment]
Probably best for now to hide the page when there is no video to display.

**Comment by spMohanty** [comment]
@seanfcarroll : If it's a question of rendering information, I think we should just do it in the same go. 
Plus the same information that we show on the leaderboard can be shown here in cases where there is no media or grader logs. But atleast there is some consistency in the interface, and participants are not confused why there is the individual submission page in some cases and in some cases it's not.

**Comment by scarroll32** [comment]
<img width="904" alt="screen shot 2018-05-01 at 14 09 04" src="https://user-images.githubusercontent.com/11340230/39472414-6bab775a-4d49-11e8-9a7c-e9f9246074c4.png">

Most of it was already there, and the crowdAI logo was not on the original design.

It can definitely use some of Jason's love...

**Comment by scarroll32** [comment]
Implemented
