### ISSUE TITLE
Markdown not being rendered corrrectly on challenge overview pages

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#748]
Link : https://www.crowdai.org/challenges/mapping-challenge

<img width="1018" alt="screen shot 2018-04-30 at 18 46 08" src="https://user-images.githubusercontent.com/1581312/39439134-d8cb7590-4ca6-11e8-8bc1-ede7c2cb95de.png">

while editing the challenge page shows we have the correct markdown : 

<img width="945" alt="screen shot 2018-04-30 at 18 47 17" src="https://user-images.githubusercontent.com/1581312/39439163-f56b993c-4ca6-11e8-948b-72b8444e45fd.png">

**Comment by spMohanty** [comment]
This is happening because of this : https://github.com/crowdAI/crowdai/blob/master/config/application.rb#L28

which replaces the allowed tags by [table, tr and td]

But this was from the rails docs here https://apidock.com/rails/v4.0.2/ActionView/Helpers/SanitizeHelper/sanitize

which say it actually appends to the list and not replaces it.

**Comment by scarroll32** [comment]
I'll reverse that config

**Comment by spMohanty** [comment]
I think we can add a fixed list of allowed tags based on https://github.com/rails/rails-html-sanitizer/commit/297161e29a3e11186ce4c02bf7defc088bf544d4 and our custom additions.

this will give us more fine grained control over this in the future.

I can send a pull request with tests.

**Comment by scarroll32** [comment]
OK the markdown is now working again in prod. There are several issues around markdown, @ mentions etc. I'd like to look at them all together.

This change was to add tables to markdown?

**Comment by spMohanty** [comment]
Okay.
And yeah, the markdown renderer was rendering table, td, tr tags, but the html sanitizer was removing them.

**Comment by scarroll32** [comment]
Closed
