### ISSUE TITLE
Changes to email preferences

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#75]
Verify emails are correctly being sent to the users as per email preferences.

**Comment by scarroll32** [comment]
Post Notification and Leaderboard mailers suspended while investigating.

**Comment by scarroll32** [comment]
"A post is made to a topic to which I am participating" is actually sending an email to every participant, not just those participating to the challenge.

<img width="562" alt="screen shot 2017-03-06 at 19 33 15" src="https://cloud.githubusercontent.com/assets/11340230/23623875/f7dd4498-02a3-11e7-817a-e6cc316a3f9a.png">

This can be fixed but we are still sending many emails out. For example https://www.crowdai.org/topics/observation-vector/posts/new has had 12 posts with 7 in a in a single day. Each post triggered an email to every participant (except those already opted out).

**Comment by scarroll32** [comment]
Suggested changes to settings:

- remove "Any discussion post is made"
- remove "In any challenge / A new entry is made on the leaderboard"

All emails are logged before sending to Mandrill. I will add a view to more easily visualise how many emails are going out in response to which events.

<img width="505" alt="screen shot 2017-03-06 at 19 38 47" src="https://cloud.githubusercontent.com/assets/11340230/23624040/91a90c88-02a4-11e7-8e87-1c6662e8bb8b.png">


@marcelsalathe your thoughts?

**Comment by scarroll32** [comment]
40,081 emails have been sent from crowdAI since tracking started (I think around October 2016). We have 687 participants.

**Comment by marcelsalathe** [comment]
> "A post is made to a topic to which I am participating" is actually sending an email to every participant, not just those participating to the challenge.

This obviously needs fixing.

I agree to remove "in any challenge, a new entry is made on the leaderboard"

Also, "general" is not clear -> if I click crowdAI newsletter, will I get it? This is incoherent. 

I think we need to discuss these in person in the next few days.

**Comment by scarroll32** [comment]
Ok let's discuss.

The post and leaderboard emails are disabled at the moment.

**Comment by scarroll32** [comment]
Proposed changes to email preferences:

- Leaderboard entry and any posts made in discussions will be sent for challenges which the user is following
- When a user starts participating in a challenge, they are automatically following that challenge
- A user may opt out of following the challenge on the challenge page

The check boxes on the Email Preferences change to:

- Receive the crowdAI Newsletter
- Receive emails for challenges which I am following

Add a email frequency section:

### Email Frequency

- Receive every email 
- Receive a daily digest of emails
- Receive a weekly digest of emails

It may be useful to have a tab on the user profile listing challenges which they are following.

**Comment by marcelsalathe** [comment]
I think this is a very good way. What should also be possible is to be able to follow a challenge, without participating. So this would need a new user interface element.

**Comment by scarroll32** [comment]
@marcel I agree. We could either use the proposed "heart" for a challenge as both a like and a follow indicator, or have a separate "follow" or "watch" indicator. GitHub uses "watch" and I think this makes sense for us also.

**Comment by scarroll32** [comment]
Partially implemented. Will hold for new designs for remainder.

https://github.com/crowdAI/crowdai/commit/8266e52cc9c44274c41b132c622b6b9c1b7de898

**Comment by scarroll32** [comment]
Needs to include integration with Mailchimp's API for the newsletter.

**Comment by scarroll32** [comment]
First part of changes applied: https://github.com/crowdAI/crowdai/commit/c8055c5af88867556c7e9c9cfcfd7d48ec090c8a

**Comment by scarroll32** [comment]
Send emails only on create and not update, in case the author edits the post

**Comment by scarroll32** [comment]
Send only on create https://github.com/crowdAI/crowdai/commit/ae6be2d8b397ddc2e665105d8d328f1cfd114de0

**Comment by scarroll32** [comment]
### Summary of discussion 

- Heart buttons remain in place and have no effect on emails
- Follow button is added to challenge
- Mentions functionality to be added

#### Email Settings 

These do not change, and the default settings are marked below. The crowdAI newsletter needs to be integrated with the Mailchimp list.

- Receive the crowdAI Newsletter (ON)
- Receive email for challenges which I am following (ON)
- Receive emails when someone mentions me in a comment/post (ON)
- Receive every email (OFF)
- Receive a daily digest email (ON)
- Receive a weekly digest email (OFF)

#### Challenge Participants 

- Automatically follow a challenge, can deselect the follow button 

#### Email Text

You have received this email because you are following one or more challenges on crowdAI.
```
The frequency for emails is set as daily digest | weekly digest 
OR
You will receive an email for every discussion post.

You can change your email settings [here]
```
@jsnrynlds What should the **on** state for the Follow button be?

**Comment by jsnrynlds** [comment]
Hi @seanfcarroll – I would simply change the text to "Following".

**Comment by marcelsalathe** [comment]
@jsnrynlds Is there any issue that the shape of the button will increase / decrease depending on the text?

**Comment by jsnrynlds** [comment]
@marcelsalathe @seanfcarroll Yes, it maybe best to create a separate modifier that can be applied to this button to maintain a min. width:
```
btn-min-width {
	min-width: 110px;
}
```

**Comment by scarroll32** [comment]
I think the expanding button looks fine. Please review @marcelsalathe

**Comment by jsnrynlds** [comment]
I'd say in this scenario it would be better to apply a `min-width` so the button doesn't expand. Not a massive deal either way though.

**Comment by scarroll32** [comment]
Implemented https://github.com/crowdAI/crowdai/commit/21eeb4ae999225dbc3c1f91cab1705f5da12f02b

**Comment by scarroll32** [comment]
Closed
