### ISSUE TITLE
Admin/Organizer view on hidden leaderboard and submissions

### ISSUE THREAD

**Issue by englhardt** [crowdAI/crowdai#752]
As an admin/organizer I would like to monitor the current leaderboard and submissions even if the page is hidden for normal participants.

A starting point to implement this would be [here](https://github.com/crowdAI/crowdai/blob/master/app/controllers/leaderboards_controller.rb#L17-L19) by changing it to:
```
if @challenge.show_leaderboard == false && !(current_participant.admin? || @challenge.organizer_id == current_participant.organizer_id)
  redirect_to '/'
end
```
Maybe this feature also requires a change in the menu display code.

Unfortunately, I don't have a local instance to test this and submit a PR.

**Comment by scarroll32** [comment]
Hi @englhardt it's a fair and useful request. If we can walk you through the setup, would you have time to do a PR?

**Comment by englhardt** [comment]
Hey @seanfcarroll, yes I have. I didn't find any starting point to setup a local instance (I guess the doc is still under construction). Where should I start?
You can also send me the instructions via e-mail.

**Comment by scarroll32** [comment]
Implemented
