### ISSUE TITLE
long_description field support in the submission api

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#753]
Its also is not handled by the `PATCH` endpoint : https://github.com/crowdAI/crowdai/blob/master/app/controllers/api/external_graders_controller.rb#L75

**Comment by spMohanty** [comment]
This is what I get right now from a sample response : 
```
{
    "challenge_id": 30,
    "challenge_name": "Visual Doom AI Competition 2018",
    "challenge_round_id": 32,
    "clef_additional": null,
    "clef_method_description": null,
    "clef_other_info": null,
    "clef_primary_run": false,
    "clef_retrieval_type": null,
    "clef_run_type": null,
    "created_at": "2018-05-02T00:33:49.356Z",
    "grading_status_cd": "graded",
    "id": 5602,
    "meta": {
        "gitlab_issue_id": "49",
        "gitlab_issue_url": "https://gitlab.crowdai.org/spMohanty/test-project/issues/49",
        "gitlab_project_id": "30",
        "gitlab_webhook_payload": "repository"
    },
    "participant_affiliation": "EPFL",
    "participant_email": "spmohanty91@gmail.com",
    "participant_firstname": "Sharada",
    "participant_id": <REDACTED>,
    "participant_lastname": "Mohanty",
    "participant_name": "spMohanty",
    "score": null,
    "score_secondary": null,
    "submission_files": []
}
```

**Comment by scarroll32** [comment]
Added this - untested so please try it out.

The description field must not be updated directly, instead the description_markdown field should be updated which will then render the markdown into the **description** field. For some reason lost to me, this passed as [comment in the API params.](https://github.com/crowdAI/crowdai/blob/master/app/controllers/api/external_graders_controller.rb#L48)

It would be best to refactor this to **description_markdown**, unless there is some reason not to do so.

**Comment by spMohanty** [comment]
@seanfcarroll : This will be the first time we will be using this field.
So we can change it without breaking anything else.

Let me know if you do, and I will update the `crowdai_api` python package accordingly.

Also I think, we should start include tests as we develop, even for small issues like this.
Else the whole codebase will go bonkers sooner or later !

**Comment by spMohanty** [comment]
@seanfcarroll : Also, not creating a separate issue, as this is very related.

The "comment" param is only present at the `create` endpoint and not in the `update` endpoint.
Hence PACTHES on the data do not work.

Lets refactor to use `long_description` consistently across both create and update ?

**Comment by scarroll32** [comment]
If we are going to refactor, please use **description_markdown**, then it matches with the Rails name.

**Comment by spMohanty** [comment]
Sure.
`description_markdown`.
Please confirm when the production server supports this.

**Comment by scarroll32** [comment]
Confirmed
