### ISSUE TITLE
Configuration parameter to hide score_secondary

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#754]
Some challenges donot really need `score_secondary`.
So we have been filling it up with a placeholder value.
Would be good to have an option to not render score_secondary on the leaderboard or at other places.

**Comment by scarroll32** [comment]
Just select "not_used"

<img width="378" alt="screen shot 2018-05-03 at 10 41 38" src="https://user-images.githubusercontent.com/11340230/39567232-982ad336-4ebe-11e8-81f9-dd31dd575c70.png">
