### ISSUE TITLE
"Submissions Instruction" section not rendering

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#755]

**Comment by scarroll32** [comment]
Where should it be rendering? This was previously used for the manual submissions upload page (currently working only for CLEF challenges).

**Comment by spMohanty** [comment]
One of the organisers of the VizdoomChallenge was confused by it.
In that case, lets only have edit boxes for only sectoions that we render.
And hide this section, and any other section which are not rendered ?

**Comment by scarroll32** [comment]
OK I'll move that section back onto it's own config page about manual submissions.

**Comment by scarroll32** [comment]
Refactored to it's own tab
