### ISSUE TITLE
Leaderboard showing deleted entries

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#756]
I deleted some entries from the VizDoom challenge. And the leaderboard continues to show it for a user "who has technically not made a submission".

Submissions Tab : 
<img width="1178" alt="screen shot 2018-05-02 at 21 23 50" src="https://user-images.githubusercontent.com/1581312/39544721-3b537204-4e4f-11e8-9b1a-f22d69df8aca.png">

Leaderboard : 
<img width="1141" alt="screen shot 2018-05-02 at 21 23 54" src="https://user-images.githubusercontent.com/1581312/39544725-40a556d2-4e4f-11e8-9213-74c0f36f98f9.png">

**Comment by scarroll32** [comment]
The new leaderboard process was not designed to handle deletes, although it is a simple matter to add a post delete hook.

Are these deletes performed from the Admin page?

**Comment by spMohanty** [comment]
@seanfcarroll : Yeah from the admin page. But we will have to support the ability to delete submissions. But its not a high priority request really, and can wait.

**Comment by scarroll32** [comment]
Implemented
