### ISSUE TITLE
Show the latest submission in case of multiple submissions with the same score ?

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#76]

**Comment by scarroll32** [comment]
Would be simple enough to do https://github.com/crowdAI/crowdai/blob/master/db/views/leaderboards_v02.sql

Add an order by date desc, but is it likely to happen?

**Comment by scarroll32** [comment]
Closed https://github.com/crowdAI/crowdai/commit/c2a44132db913a97ae7cf4d494cf8e0e050a89b9
