### ISSUE TITLE
Submissions API Server error

### ISSUE THREAD

**Issue by ieggel** [crowdAI/crowdai#763]
HI @seanfcarroll 

The submissions API is not working anymore, i get a "server error" each time i try to call the API.
E.g.:https://www.crowdai.org/api/challenges/16/submissions

This still worked yesterday.

It's quite urgent since i have to use this API quite often.
Thanks for having a look ASAP.

**Comment by scarroll32** [comment]
Hi Ivan, there was a lot of refactoring yesterday. Can you provide the details of the call made and any error message if possible.

**Comment by scarroll32** [comment]
The tests are passing ... https://github.com/crowdAI/crowdai/blob/master/spec/requests/api/submissions_controller_spec.rb

**Comment by ieggel** [comment]
Hi Sean, 

I'm getting the following response "server error". I remember having coded it in that way that when a 500 Error occurs it just returns "server error" in order not to expose too much to the caller.

This happens independently for all challenges. The only way i don't get the 500 error is when using a wrong organizer key. In that case i receive a 401 Unauthorized error with the message "HTTP Token: Access denied.", which is normal behavior. The error seems to happen when the SQL call is made or the json response is produced.

I'm sending you an e-mail with a screenshot from postman. Don't want to put it here because it would reveal the organizer key.

**Comment by scarroll32** [comment]
Fixed
