### ISSUE TITLE
GUI: + 'Challenge round' too close to 'update challenge' button

### ISSUE THREAD

**Issue by mihahauke** [crowdAI/crowdai#769]
Just an annoying gui thing, the '+challenge round' is too close to the 'update challenge' button

**Comment by spMohanty** [comment]
<img width="893" alt="screen shot 2018-05-05 at 17 56 52" src="https://user-images.githubusercontent.com/1581312/39665049-beaceca8-508d-11e8-9816-b8470cb8ecac.png">

**Comment by englhardt** [comment]
A similar issue in the Overview tab:
![screenshot_2018-05-07_09-21-16](https://user-images.githubusercontent.com/7440669/39689761-2e790c9c-51d8-11e8-951a-94f76c57b21d.png)

**Comment by mihahauke** [comment]
Same for other stuff in the edition mode ...
![screenshot from 2018-05-09 03-47-22](https://user-images.githubusercontent.com/2771069/39791731-8b04fa96-533d-11e8-8990-be950538808b.png)
