### ISSUE TITLE
Error 500 when not logged-in

### ISSUE THREAD

**Issue by Sylvain-Bernard** [crowdAI/crowdai#772]
Some challenge pages return an 500 error when not logged-in.

E.g.:

https://www.crowdai.org/challenges/nips-2018-adversarial-vision-challenge
https://www.crowdai.org/challenges/nips-2018-ai-for-prosthetics-challenge
https://www.crowdai.org/challenges/nips-2017-learning-to-run
https://www.crowdai.org/challenges/dark-skies-classification-of-nighttime-images

**Comment by scarroll32** [comment]
This is patched now.
