### ISSUE TITLE
New challenge from admin panel not working

### ISSUE THREAD

**Issue by farnir** [crowdAI/crowdai#779]
When trying to create a challenge from Admin Panel, some errors appeared:
- Grading_factor not defined
- Grader not defined

It seems to come from the form in admin/challenge.rb that contains outdated input according to Challenge Model.

**Comment by englhardt** [comment]
I can confirm this. After removing the two lines [here](https://github.com/crowdAI/crowdai/blob/master/app/admin/challenge.rb#L54-L55), I am able to create new challenges.

**Comment by scarroll32** [comment]
This is based on an older model, and will be removed. In fact a challenge should be created from the organizer's page. In time, the development environment will be configured with seed data with organizers etc.

<img width="1183" alt="screen shot 2018-05-14 at 16 44 37" src="https://user-images.githubusercontent.com/11340230/40004553-3a5b9fc0-5796-11e8-96e4-2647dbbcdded.png">

**Comment by scarroll32** [comment]
Ability to create or update a challenge from the admin panel has been removed - all changes should be done via the challenge configuration page.

**Comment by scarroll32** [comment]
Implemented

**Comment by farnir** [comment]
It seems that from a Participant (with organizer set) view you don't have any link to the organizer page.
So if they are no challenges, there is no access to the button "Create Challenge" even for an Admin.
You have to known and enter manually the URL : "/organizers/[name]".
The solution may be the creation of a link in the profile page of participant (with organizer set) redirecting on his organizer page.
