### ISSUE TITLE
Create New Submission (for any user) via admin interface

### ISSUE THREAD

**Issue by Sylvain-Bernard** [crowdAI/crowdai#781]
Part of the feature seems to be in place, but not fully functional...

Missing:
- [x] Possibility to specify user (who will be linked to the submission)
- [x] Grading status cd as drop down list (or radio)
- [x] Documentation (eg Challenge round ID, not 1 or 2)
- [ ] Possibility to create new submissions in batch (upload xls)

![image](https://user-images.githubusercontent.com/15749650/39812068-6fbbff16-538b-11e8-99ba-ee9e7747387c.png)

**Comment by scarroll32** [comment]
We won't add a batch upload from xls ... instead this can be done via the API.

**Comment by scarroll32** [comment]
Implemented
