### ISSUE TITLE
Allow post-challenge submission via webpage

### ISSUE THREAD

**Issue by ieggel** [crowdAI/crowdai#785]
Currently it is not possible to enable post-challenge submissions for challenges that make use web page submissions. The "Create submission" button does not show up after the challenge is completed.
It would be nice if there was an option on the edit-challenge page to enable those post-challenge submissions.

**Comment by scarroll32** [comment]
For the challenges which accept submissions via the python client, this is handled by shutting down the grader when challenges will no longer be accepted.

For the CLEF and other challenges which accept challenges via the online page, an additional checkbox will be added: "Post challenge submissions?". This will allow the submission page will be visible and accept submissions after the end of the challenge. The existing grader / API code will control if the submissions are marked 'post challenge'.

Note the submissions page will always be visible to admins / organizers if the "Online submissions permitted?" checkbox is checked.

This will be refactored at some point when the Clef challenges are refactored properly into the main code branch.

@ieggel Does this work for you?




<img width="768" alt="screen shot 2018-05-14 at 10 11 48" src="https://user-images.githubusercontent.com/11340230/39985623-68984cee-575f-11e8-93b6-4e4567b0ab25.png">


<img width="502" alt="screen shot 2018-05-14 at 10 14 17" src="https://user-images.githubusercontent.com/11340230/39985668-95755ffe-575f-11e8-91ad-7a38f8280215.png">

**Comment by ieggel** [comment]
This sounds good and makes sense. Thank you.

**Comment by scarroll32** [comment]
Implemented
