### ISSUE TITLE
No gaps permitted between challenge rounds

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#786]
Currently it is possible to set up challenge rounds with gaps between them. This proposal is to instead set the challenge start / end times to be with a minute's precision, and no gaps permitted between challenge rounds.

Eg:
**Round 1**
Starts 01 Jan, 09:00 UTC
Finished 15 Mar 17:00 UTC

**Round 2**
Starts 15 Mar, 17:01 UTC
Finished 30 Mar 17:00 UTC

Normally, any submission will be assessed by timestamp to determine which round it is in. If the submission is made after the end of the last round, it will automatically be marked 'post challenge' for the last round.

There is an override possible via the Python client which allows post-challenge submissions for earlier rounds. 

Sticking to this rule will significantly simplify the currently problematic code around challenge rounds.

Does this work for you @spMohanty @ieggel ?

### Future feature
A future feature would allow for:

- a "gap" round, where the challenge is between rounds and can perhaps accept post-challenge submissions
- ability to specify which round the submission is for when making post-challenge 
- specify at the challenge round level if post challenge submissions are accepted

A challenge with a gap round would look like

**Round 1**
Starts 01 Jan, 09:00 UTC
Finished 15 Mar 17:00 UTC

**Gap Round**
Starts 15 Mar, 17:01 UTC
Finished 01 Apr 08:59 UTC

**Round 2**
Starts 01 Apr, 09:00 UTC
Finished 30 Apr 17:00 UTC

We can also look at some more interactive calendar / timeline component for challenge rounds in a future feature. If we want something like this it can be opened on it's own ticket.

**Comment by ieggel** [comment]
OK for me. Would be nice if the gap round was automatically created if
consecutive rounds' end- and start times are not continuous (in other words
have a gap).
