### ISSUE TITLE
Better Analytics 

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#787]
For instance, right now its hard for us to estimate the total number of files downloaded, or the total volume of data transferred from file downloads, which is an important thing we should have access to when making policy decisions.
around 3TB of data was downloaded through crowdAI last month, and we have no clue what was downloaded, where, and how can we limit a single user abusing the system, etc. 

This is an open ended issue, and we should try to have much more detailed analytics to better understand how our users interact with crowdAI.

**Comment by scarroll32** [comment]
Theres a few issues along these lines ... it would be useful to have a spec of what should be tracked along with a rough mock-up of layout. We can give it to Jason to design and then implement. 

To do this we would need:

- what data needs to be tracked
- what analytics will be displayed and how they can be interacted with
- where they will be displayed on the platform

https://github.com/crowdAI/crowdai/issues/523

https://github.com/crowdAI/crowdai/issues/520

https://github.com/crowdAI/crowdai/issues/262

**Comment by scarroll32** [comment]
Closed as this can now be done with the Grafana console
