### ISSUE TITLE
Leaderboard and submissions tab page empty

### ISSUE THREAD

**Issue by ieggel** [crowdAI/crowdai#790]
Logged in as an ordinary participant, i was not able to view any leaderboard or submissions tab page of any challenge. The leaderboard shows as empty table:
![image](https://user-images.githubusercontent.com/9192090/40102685-6f8eeaca-58eb-11e8-9e88-73797a3547ba.png)
The submissions tab page shows as empty table as well:
![image](https://user-images.githubusercontent.com/9192090/40102735-950837c0-58eb-11e8-8b44-349ab99a8f88.png)

This happens independently of the 'allow post-challenge submissions' being able or not.

Edit: Maybe i should mention that this ordinary participant is at the same time a lifeclef organizer? What i meant was: not an organizer of the challenges where the leaderboard is empty.

**Comment by scarroll32** [comment]
Can you provide the participant you are logged in under and the challenge you are accessing @ieggel ?

**Comment by ieggel** [comment]
HI @seanfcarroll 

- Logged in as ivan.eggel@gmail.com (LifeCLef organizer)
- Can see everything as expected on all LifeCLEF challenges
- Can see everything empty (see Screenshot from first post) on all other challenges

I also did the same for my ImageClef organizer account and there also i can see empty an leaderboard and an empty submissions tab's table for all challenges except the ImageCLEF challenges.

**Comment by scarroll32** [comment]
The problem was cause by using an organizer account against a challenge they are not an organizer for. It is now fixed. https://github.com/crowdAI/crowdai/commit/9a43ce3774b2f14f08b63398363f29a2c8814755
