### ISSUE TITLE
Webpage post-challenge submissions not working

### ISSUE THREAD

**Issue by ieggel** [crowdAI/crowdai#791]
Webpage submissions do not work post-challenge:
- No error on submissions, however:
- No entry in submissions tab

It only seems to upload the submission file to amazon, but nothing elese happens.

**Comment by scarroll32** [comment]
Hi @ieggel can you give me details of which challenge and which participant you submitted under?

**Comment by ieggel** [comment]
Hi @seanfcarroll 

I've just tried again and did the following:
- Logged in as ivan.eggel@gmail.com (LifeClefOrganizer in case it matters)
- Went to **ImageCLEF 2018 Tuberculosis - Severity scoring** challenge
- Hit "Create Submission" button
- Filled in all necessary information on the submission page
- Chose File to upload
- File was uploaded and form submitted
- Was redirect to submissions tab, however this is empty (due to the other bug #790)
- Logged in as an ImageCLEF organizer to view the submissions tab
- The submission i've just created does not show up at all (no entry for that submission in table, other submission show as expected)

Then i've also tried to submit with the ImageCLEF organizer account, however the result is exactly the same: no entry for the previously created submission in the submissions tab's table.

**Comment by scarroll32** [comment]
perfect, thank you @ieggel

**Comment by scarroll32** [comment]
OK it seems to be an edge-case : the participant IS an organizer but not for this challenge. Will apply a patch shortly but it will not affect most participants.

**Comment by scarroll32** [comment]
Implemented https://github.com/crowdAI/crowdai/commit/9a43ce3774b2f14f08b63398363f29a2c8814755

**Comment by ieggel** [comment]
Hi @seanfcarroll , 
Thanks. Tried to create a submission but as before it does not seem to be processed by a grader. The submissions tab 's table now, however my submission is not there at all.

**Comment by ieggel** [comment]
Re-opened the issue since it is not solved

**Comment by scarroll32** [comment]
Working now, this uncovered a series of other issues. Note [this related issue](https://github.com/crowdAI/crowdai/issues/799)

Also that the 'post submissions' switch must be turned on (as in the screen shot).

<img width="1178" alt="screen shot 2018-05-22 at 16 55 18" src="https://user-images.githubusercontent.com/11340230/40370685-14bd61a8-5de1-11e8-829c-2a5690540729.png">
