### ISSUE TITLE
Online Post-challenge submission shouldn't be allowed if participant not registered

### ISSUE THREAD

**Issue by ieggel** [crowdAI/crowdai#794]
I've seen that post-challenge submissions are allowed even if participants are not registered for the clef task. E.g. a participant that has not signed the EUA can create post-challenge submissions.

@seanfcarroll this bug was introduced with the following line you wrote:
`
if @record.completed? && @record.post_challenge_submissions
  return true
`
I will provide a PR with a fix

**Comment by scarroll32** [comment]
Implemented
