### ISSUE TITLE
Submissions tab cannot display multiple challenge rounds

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#799]
Currently the submissions tab and the leaderboard are out of sync from a requirements perspective. The We have a different leaderboard for each challenge round, and can further split out the in-round and post-round submissions.

For the submissions, we look at the current active round only, and don't consider post-round submissions. How to display this will need some thought, perhaps we can follow the model of the leaderboard with pills at the top of the list. The list also needs search / filter.

As an immediate solution to https://github.com/crowdAI/crowdai/issues/791, the leaderboard will be modified to display **all** submissions the current participant is eligible to see, with no distinction about round. 

This issue will track the full implementation which covers multi-round and post-challenge data.

**Comment by scarroll32** [comment]
FYI @ieggel

**Comment by ieggel** [comment]
Thanks @seanfcarroll , 

I agree with your immediate solution, as otherwise participants would have zero feedback when something goes wrong.

**Comment by scarroll32** [comment]
- add tabs as per leaderboard

**Comment by scarroll32** [comment]
Implemented.
