### ISSUE TITLE
Teams

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#80]
Teams have been suggested by participant **Zxc_596**, and were also discussed previously within the crowdAI team. I've opened this issue as a place to discuss this potential feature. 

Things to consider

- How would a team be formed? Should participants be able to directly message each other?
- Can a team be formed after the challenge has already started?
- Can a participant submit outside of the team if they are a team member?
- How can team members share code?

**Comment by spMohanty** [comment]
@seanfcarroll : Any reason in particular why this issue was closed ? :-?
