### ISSUE TITLE
Bad redirection on image removal (Challenge)

### ISSUE THREAD

**Issue by farnir** [crowdAI/crowdai#808]
It seems that deleting an image in Challenge Edit is wrongly redirect.
It caused by challenge_controller.rb, line 107: 
`redirect_to edit_challenge_path(@challenge), notice: 'Image removed.'`
Solution:
`redirect_to edit_organizer_challenge_path(@challenge.organizer, @challenge), notice: 'Image removed.'`

**Comment by scarroll32** [comment]
Fixed
