### ISSUE TITLE
Fix styling issues

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#815]
![screen shot 2018-05-28 at 15 37 03](https://user-images.githubusercontent.com/11340230/40616944-02a02eb4-628d-11e8-89ce-2ee061d76a6e.png)

**Comment by scarroll32** [comment]
https://github.com/crowdAI/crowdai/blob/master/app/assets/stylesheets/_layout-molecules.scss#L44-L61

**Comment by jsnrynlds** [comment]
@seanfcarroll @marcelsalathe maybe the best solution here would be to remove the names of the organisers and display them using a tooltip on hover?

![crowdai_multiple_organisers_example_1](https://user-images.githubusercontent.com/1162939/41719599-6a57f504-7558-11e8-8173-4f5a650449a6.png)

**Comment by scarroll32** [comment]
Changed to tooltip on hover.
