### ISSUE TITLE
Add submissions remaining detail somewhere on the challenge

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#816]

**Comment by scarroll32** [comment]
@spMohanty : this is public, right?

**Comment by spMohanty** [comment]
@seanfcarroll : Public in the sense ?
Every participant will only see their own submissions remaining detail.
(It goes somewhere on the challenge page {maybe, my submissions tab) right ?)

**Comment by scarroll32** [comment]
OK, actually I think we said there would be a "my submissions" filter button, which would also expand a section above the submissions to show submission remaining details. I'll do a quick implementation which can be later designed by a professional (ie: Jason). I'll open a separate ticket of design items.

**Comment by scarroll32** [comment]
Implemented.
