### ISSUE TITLE
Is there any reason why we need to log IPs?

### ISSUE THREAD

**Issue by marcelsalathe** [crowdAI/crowdai#820]
Security concerns re people trying to game the system? @spMohanty?

If not, let's delete those fields in the database.

**Comment by spMohanty** [comment]
@marcel.salathe: while the exact IP is not important, its still is very useful to know that a unique IP was used to access a service say 10000 times. 
I would propose simply storing an encrypted version of the IP; and we choose a one way encryption to ensure that we can never decrypt it.
That way we do not have the actual ip of the user, but we still have a unique identifier for all points that were used to access any of the services.

**Comment by scarroll32** [comment]
They have already been deleted from the Rails app to support GDPR.

I see you point Mohanty but I don't think we currently have the need for this, and there are *plenty* of other priorities right now.

**Comment by scarroll32** [comment]
Closing
