### ISSUE TITLE
complete "Download your data" feature

### ISSUE THREAD

**Issue by marcelsalathe** [crowdAI/crowdai#821]
Don't we have more data on participants, than what the Download your data currently returns?

I.e. all the submissions
All the forum posts
All the leaderboard positions
etc.

**Comment by scarroll32** [comment]
Replied on Slack

**Comment by scarroll32** [comment]
As per discussion on Slack:

## Deletions

- posts, topics and comments can be deleted, but their place in the thread will be retained. If there is a deletion the post content will be updated to "This [post|comment|topic description] has been deleted by the author."

- submission information cannot be deleted, as submissions and leaderboard information is effectively research data and will be retained for up to 10 years. The TOS will be updated to reflect this. If a user deletes their account, the username will transform to "<redacted>" (already implemented).

## Downloads

The personal data download will be updated to include (not optionally):

- all posts, comments and topics made by the user
- all submissions 
- leaderboard positions at the time of the download (the leaderboard will change on the next submission by any user)

We need to discuss download of submitted code. Some of these are quite large.

One option would be to build a page where the users can access expiring links for all content in S3. This would be a fairly complex feature.

@marcelsalathe @spMohanty what are your thoughts on the downloadable content. Is it actually considered to be personal information.

**Comment by scarroll32** [comment]
Implemented
