### ISSUE TITLE
Privacy Policy

### ISSUE THREAD

**Issue by marcelsalathe** [crowdAI/crowdai#822]
Is our privacy policy up to date? Are we specific enough to explain:

- what data we collect, and why?
- what third party services we use?

see https://www.extensionschool.ch/privacy as an example.

**Comment by scarroll32** [comment]
Replied on Slack

**Comment by scarroll32** [comment]
To be updated to detail:

- which personal data we collect
- which personal data is needed for CLEF challenges only
- which external services we use
- submission data is retained for up to 10 years for research purposes

**Comment by scarroll32** [comment]
Implemented
