### ISSUE TITLE
Rename winner tab as "Winners"

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#836]
In most of the case, the winners tab will point to the top-N participants, so it makes sense to name it as "Winners" instead of "Winner"

<img width="808" alt="screen shot 2018-06-05 at 17 01 09" src="https://user-images.githubusercontent.com/1581312/40984386-1356ad54-68e2-11e8-89a0-d0b6e883ec59.png">

**Comment by scarroll32** [comment]
Done, will go in with the next build.

**Comment by scarroll32** [comment]
Done
