### ISSUE TITLE
Syntax highlighting for python has possible CSS conflicts

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#837]
Something seems off here : 
<img width="1001" alt="screen shot 2018-06-06 at 02 41 04" src="https://user-images.githubusercontent.com/1581312/41009746-2463a524-6933-11e8-8369-c2fbf6e96f10.png">
Note that the lines seem to have an extra background around them.

This is present at : https://www.crowdai.org/topics/sharing-some-tips-to-increase-the-accuracy-and-report-error-of-rcnn/discussion

Also does Rouge + Kramdown support code highlighting in a dark mode. Something like : 
![](https://packagecontrol.io/readmes/img/4523742e597b59520238ba2001b7f893f0f885e6.png)

I personally prefer this dark styling for better readability of the code. But this is open to discussion

**Comment by spMohanty** [comment]
It seems Rouge does support the solarized theme : https://github.com/poole/lanyon/issues/100

**Comment by scarroll32** [comment]
I prefer the dark styling also.

**Comment by scarroll32** [comment]
Patched ... but also https://github.com/crowdAI/crowdai/issues/874
