### ISSUE TITLE
"Show leaderboard" option doesnt work on challenges which are complete

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#838]
<img width="1313" alt="screen shot 2018-06-06 at 10 59 05" src="https://user-images.githubusercontent.com/1581312/41028043-d695509a-6978-11e8-95c8-86d665f4242b.png">

I wanted to make the ieee investment ranking challenge leaderboard visible to everyone.

**Comment by scarroll32** [comment]
Leaderboard visible, issue tracked here: https://github.com/crowdAI/crowdai/issues/840
