### ISSUE TITLE
Blog authorship on landing page

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#839]
<img width="1143" alt="screen shot 2018-06-06 at 11 12 03" src="https://user-images.githubusercontent.com/1581312/41028853-95e751e0-697a-11e8-97a9-d195493ccc2d.png">

@jsnrynlds design also had the authorship information (a small profile picture etc) in the block on the landing page for blog posts. 

Was it excluded intentionally ? or is it a bug ?

**Comment by scarroll32** [comment]
They are not in the design in the landing page, only on the blog index page.

<img width="1062" alt="screen shot 2018-06-14 at 09 15 22" src="https://user-images.githubusercontent.com/11340230/41397144-8794eb04-6fb3-11e8-9a7c-146720a3586c.png">

<img width="1050" alt="screen shot 2018-06-14 at 09 21 06" src="https://user-images.githubusercontent.com/11340230/41397366-4c0bb2ec-6fb4-11e8-96ab-16e77494b86b.png">
