### ISSUE TITLE
422 on challenge updates

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#840]
Updating some of the checkboxes in the challenge configuration is leading to a 422. 

<img width="803" alt="screen shot 2018-06-07 at 08 52 02" src="https://user-images.githubusercontent.com/11340230/41083899-c1a651ba-6a32-11e8-8c1c-30b36404f6e4.png">

Running in dev

<img width="1038" alt="screen shot 2018-06-07 at 09 11 44" src="https://user-images.githubusercontent.com/11340230/41083916-db23c28a-6a32-11e8-96be-d9e94557462f.png">

Seems to be a 5.2 upgrade issue

https://github.com/rails/rails/commit/ec4a836919c021c0a5cf9ebeebb4db5e02104a55

**Comment by scarroll32** [comment]
Temporary workaround https://github.com/crowdAI/crowdai/commit/9fec8d66efe4cae469ff93abeff0022ca4ef1238

From https://stackoverflow.com/a/48762137/993592

**Comment by spMohanty** [comment]
@seanfcarroll : Did you look at this : https://github.com/rails/rails/issues/22965#issuecomment-336190639

**Comment by scarroll32** [comment]
Thanks for the tip @spMohanty, I thought that could be the issue, esp with https://github.com/crowdAI/crowdai/issues/747

But the issue also occurs locally where there is no CDN. After much investigation, the issue is somehow tied to Turbolinks + 5.2. There may be some gem dependency causing the issue, but I haven't tracked it down.
Disabled turbolinks on forms for now, more investigation to come when time permits.

**Comment by scarroll32** [comment]
Possibly related https://github.com/rails/rails/issues/24257
