### ISSUE TITLE
Cannot view the leaderboard video for Ai-for-prosthetics challenge

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#845]
https://www.crowdai.org/challenges/nips-2018-ai-for-prosthetics-challenge/leaderboards

On clicking the video, I get an "You are not authorised to access this page" error.

**Comment by scarroll32** [comment]
The **Submission Details Visible?** setting needs to be turned on. It's set now & is working.

> The visibility for this page is controlled via the **Submissions Details Visible?** configuration setting. If set to OFF, the page is completely inaccessible, even to admins.

https://github.com/crowdAI/crowdai/blob/master/doc/leaderboard_submissions_visibility.md
