### ISSUE TITLE
Videos on leaderboard

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#846]
On Firefox,

The videos on the leaderboard (https://www.crowdai.org/challenges/nips-2018-ai-for-prosthetics-challenge/leaderboards) do not run on page load, and it could be confused for a static image.

When I click on the image, it takes me to the submission detail page where it doesnt play either.

Expected behaviour : 
* Videos on the leaderboard play automatically, and loop forever
    * This has to be done efficiently so that the page doesnt consume too much resources. 
    * An immediate implementation can simply enable it for all the videos, but later we can look at conditionally enabling and disabling it (by only considering video elements within the page view, and disabling the rest; or anything else which worrks for us)

* On the submission page view, it should also play automatically and loop forever, but we will have `showControls` enabled.

Note show controls are not enabled on the leaderboard as the thumbs are pretty small already, and adding the controls doesnt provide any benefit.

**Comment by scarroll32** [comment]
Assigned to @MasterScrat - this is a pure js issue. Existing (currently broken) code is [here](https://github.com/crowdAI/crowdai/blob/master/app/assets/javascripts/controllers/leaderboards_controller.js)

**Comment by spMohanty** [comment]
@seanfcarroll : We will probably need this before @MasterScrat  starts.
It would be good to `showControls` on the individual submissions page : [https://www.crowdai.org/challenges/nips-2018-ai-for-prosthetics-challenge/submissions/7846](https://www.crowdai.org/challenges/nips-2018-ai-for-prosthetics-challenge/submissions/7846) 

and also, play the video by default on page load.
(the performance issues shouldnt come up if theres just a single video)

**Comment by scarroll32** [comment]
<img width="899" alt="screen shot 2018-06-22 at 17 45 27" src="https://user-images.githubusercontent.com/11340230/41785896-3e636ec8-7644-11e8-8c3d-4617a1955efc.png">


Done
