### ISSUE TITLE
“Accept Cookie” rendered weird on mobile

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#851]
![b1e4a9f5-ddf3-473c-98e9-83d02499d9f0](https://user-images.githubusercontent.com/1581312/41480653-60f32890-70cf-11e8-97a4-4cfc341406d5.png)

**Comment by marcelsalathe** [comment]
Can confirm, on all pages. Should fix this asap, thx

**Comment by bkDJ** [comment]
While waiting for design input, there are a few ways to fix this as a stop-gap measure.

1) If the cookie notification should be at the bottom of the screen, line 33 can be removed here:
https://github.com/crowdAI/crowdai/blob/21cc5041cd8e08ee5516ddc470c80061a234bfe8/app/assets/stylesheets/_cookies.scss#L29-L34

2) If the cookie notification should be at the top of the screen, in such a way that it obscures page content, then the same line should be changed to `position: relative;` or `position: sticky;`

3) If the cookie notification should be at the top of the screen and push page content down, the problem has to do with fixed-height headers, which is tricker to solve correctly.

**Comment by scarroll32** [comment]
Patched but leaving this open to be fixed properly by Jason.

**Comment by scarroll32** [comment]
Having the closing button in the right corner would work, and would work equally well on desktop and mobile. Below is the StackOverflow solution:

<img width="1095" alt="screen shot 2018-08-18 at 13 50 57" src="https://user-images.githubusercontent.com/11340230/44299003-f4a1e680-a2ed-11e8-9dd0-201c4e85afe7.png">

**Comment by jsnrynlds** [comment]
@seanfcarroll I've tidied this up a bit. (Pushed to the templates repo.)

**Comment by scarroll32** [comment]
Fixed
