### ISSUE TITLE
Upgrade dependencies for crowdAI music evaluation interface

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#857]
Is locked to an older version of node - incompatible with Heroku CLI

<img width="880" alt="screen shot 2018-06-21 at 13 04 53" src="https://user-images.githubusercontent.com/11340230/41715430-b7289398-7553-11e8-856d-03f7d8a3d651.png">

https://github.com/crowdAI/crowdai-music-evaluation-interface

**Comment by scarroll32** [comment]
Hi @MasterScrat I wonder if this would be a good self-contained first issue  to start on: it is in a separate repo.

**Comment by scarroll32** [comment]
@spMohanty could you assist Florian on this one?

**Comment by scarroll32** [comment]
Related issue https://github.com/crowdAI/crowdai/issues/655

**Comment by spMohanty** [comment]
Closing this, as this is not relevant anymore.
