### ISSUE TITLE
Organizers should not be able to change challenge status

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#862]
Organizer accounts should be able to modify all aspects of a challenge while in **draft**, except the challenge status. Only crowdAI admins should be able to move a challenge into running mode or otherwise change the status.

We need to consider what aspects of a challenge an organizer can change once a challenge is running, and implement this through role-based security.

Related issues [roles](https://github.com/crowdAI/crowdai/issues/554) and [multiple organisers](https://github.com/crowdAI/crowdai/issues/574).

Marking as high as we now have many organizer users capable of modifying all aspects of their challenges.

**Comment by scarroll32** [comment]
Implemented as read only for organizers. Only crowdAI admins can change challenge status.

![screen shot 2018-08-09 at 13 56 57](https://user-images.githubusercontent.com/11340230/43897427-3a97f71a-9bdc-11e8-9679-14117c009fb9.png)

**Comment by spMohanty** [comment]
I would also cordon off "Featured Sequence" value for admin only rights.

**Comment by antoinexp** [comment]
Organizers are not able to edit the challenge status:

<img width="848" alt="screenshot 2018-11-23 at 17 41 30" src="https://user-images.githubusercontent.com/2098699/48953797-530ede80-ef47-11e8-91a1-dbb89646c2cf.png">
