### ISSUE TITLE
Is Grader Identifier still used?

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#866]
On the challenge we have a **Grader Identifier** field. @spMohanty is this still needed?

<img width="743" alt="screen shot 2018-06-22 at 15 21 52" src="https://user-images.githubusercontent.com/11340230/41778789-1b25acc8-7630-11e8-854e-519f0abcb941.png">

**Comment by spMohanty** [comment]
Hi Sean,

Yes it is being used quite a lot actually now.
For all future challenges using the broker, we will need the grader
identifier.

Mohanty

**Comment by scarroll32** [comment]
Thanks
