### ISSUE TITLE
Dataset message/announcements

### ISSUE THREAD

**Issue by Sylvain-Bernard** [crowdAI/crowdai#883]
Would be nice to be able to display a message when challenge doesn't have a Dataset to redirect participants to GitHub repos for example.

Something like #783 would be perfect!

**Comment by spMohanty** [comment]
In the meantime, should we simply upload a single page PDF with a link to the respective starter kits ?

**Comment by scarroll32** [comment]
Added, to be released.

<img width="1191" alt="screen shot 2018-08-28 at 11 19 05" src="https://user-images.githubusercontent.com/11340230/44713846-439d0800-aab4-11e8-8e22-a0bdc19c9540.png">

**Comment by scarroll32** [comment]
Implemented
