### ISSUE TITLE
Submission share links broken

### ISSUE THREAD

**Issue by Sylvain-Bernard** [crowdAI/crowdai#886]
Link generated when **copy url** or on **Facebook** or **Twitter** bottons are not the rights ones.
Issue generalized on every challenges.

![image](https://user-images.githubusercontent.com/15749650/42991380-9637ea76-8c05-11e8-91d7-7ed8ce325db2.png)

**Comment by scarroll32** [comment]
Underlying issue

![screen shot 2018-08-09 at 12 50 15](https://user-images.githubusercontent.com/11340230/43894575-cec04de8-9bd2-11e8-9d83-3dcead226bbf.png)

**Comment by scarroll32** [comment]
Fixed
