### ISSUE TITLE
Log full payload of inbound API calls

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#906]

**Comment by scarroll32** [comment]
Actually this should be already happening ... @MasterScrat what is missing that you need?

**Comment by MasterScrat** [comment]
I only see the URLs of the requests:

`2018-08-03T17:04:30.738Z 35 TID-grz6gwz7b INFO: Started POST "/api/external_graders?challenge_client_name=test_challenge&api_key=39d009e38c373283c92367ff38423dd1&grading_status=submitted" for 172.18.0.9 at 2018-08-03 17:04:30 +0000`

For debugging purposes it would be good to get the full POST payload.

But it's potentially going to be a *lot* of data so it should be easy to turn it on/off (is there already a mechanism to adjust logging level?)

**Comment by scarroll32** [comment]
OK, I'll add the body to logging ... it will be a separate call so I'll repeat some info. To turn it off requires a code push / reboot, and we might be running multiple background processing servers. It would be possible to do something programmatically but it will be tricky and a bit hacky.

I think it will be OK to log it all, the logs are not retained now anyway and just get cycled. We should have a log aggregator though.

How much is a lot?

**Comment by scarroll32** [comment]
Implemented.
