### ISSUE TITLE
Use Standart Time format

### ISSUE THREAD

**Issue by Sylvain-Bernard** [crowdAI/crowdai#911]
We should use Standart Time format consistently everywhere on the platform, not US format. This can confuse participants and admins ;-)

One place where it is used. -> we should check if there are other places
![image](https://user-images.githubusercontent.com/15749650/43850946-9b00e07e-9b39-11e8-99b2-b67a0943d6f8.png)

**Comment by scarroll32** [comment]
Do you mean 24 hour time?

**Comment by Sylvain-Bernard** [comment]
Yes!

**Comment by scarroll32** [comment]
Wait, do you mean you want to change to US format?

**Comment by Sylvain-Bernard** [comment]
NO ! Time selection should be 24h, not US with AM and PM

**Comment by scarroll32** [comment]
Implemented https://github.com/crowdAI/crowdai/commit/1efc5c3a1f4f4bd8b208f9005faf292ba8266ba9
