### ISSUE TITLE
[edit challenge] Message "Challenge updated." when CANCEL

### ISSUE THREAD

**Issue by Sylvain-Bernard** [crowdAI/crowdai#915]
When clicking on "CANCEL" while editing a challenge, the message "Challenge updated." is displayed.
Message should be "Challenge edition cancelled." or something like this.

However "CANCEL" button is working as expected.

![image](https://user-images.githubusercontent.com/15749650/43893482-6f0e12ca-9bcf-11e8-9f70-54c0db69425a.png)

**Comment by scarroll32** [comment]
Fixed
