### ISSUE TITLE
Develop "Host a challenge" text

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#93]

**Comment by scarroll32** [comment]
@marcelsalathe What are your thoughts on this for V2?

What should the "Get Started" button do?
<img width="1169" alt="screen shot 2017-05-26 at 15 52 19" src="https://cloud.githubusercontent.com/assets/11340230/26497313/5ccbfa72-422b-11e7-94c2-e27562ac4ed8.png">

**Comment by scarroll32** [comment]
I'm happy to draft something if preferred.

**Comment by scarroll32** [comment]
changes here: https://github.com/crowdAI/crowdai/commit/8fcedebbdd53d5e1c7f32b3ccf067e8731b6de08

@jsnrynlds I used some br's to get the spacing, not ideal. When you have time could you look into a better formatting?

@marcel let me know if you want the text changed: https://crowdai-stg.herokuapp.com/landing_page/host

I think this page could also benefit from a background or mid-page image.

**Comment by jsnrynlds** [comment]
@seanfcarroll @marcelsalathe I wonder if for the time being, we could make this more like the homepage? So, remove the grey header, increase the size of the main heading, and add the background-image?

Also, maybe change the heading to 'Interested in hosting a challenge?'.

@seanfcarroll Not sure if you noticed, but if you look at template-host-a-challenge.html and press the 'Get started' button it should bring up a modal where you can enter more details.

<img width="635" alt="screen shot 2017-06-08 at 09 54 03" src="https://user-images.githubusercontent.com/1162939/26920292-743d18c6-4c30-11e7-8fbb-3501a48c4e35.png">

**Comment by jsnrynlds** [comment]
If we did change the main heading _and_ use the modal then we should probably change the modal heading.

**Comment by marcelsalathe** [comment]
I think this is a great idea (i.e. make it look more like the homepage, and then get info via the modal).

**Comment by scarroll32** [comment]
OK ... consider it done :-)

**Comment by scarroll32** [comment]
Implemented.
