### ISSUE TITLE
Create submission file download for organizers

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#940]
In the challenge "Admin" section, a check box can be set to determine if challenge organizers can download submission files. The files are then accessed via the edit score page.

<img width="829" alt="screen shot 2018-08-20 at 10 33 16" src="https://user-images.githubusercontent.com/11340230/44329346-829fdd80-a464-11e8-8c6a-d75143396ba2.png">

<img width="696" alt="screen shot 2018-08-20 at 10 29 35" src="https://user-images.githubusercontent.com/11340230/44329362-8df30900-a464-11e8-9780-606d01ac5fae.png">

**Comment by jordiju** [comment]
@seanfcarroll : Thanks a lot, this is _very_ useful.

**Comment by scarroll32** [comment]
Implemented
