### ISSUE TITLE
UN logo on homepage

### ISSUE THREAD

**Issue by jsnrynlds** [crowdAI/crowdai#942]
Hi @seanfcarroll – I think we should replace the UN logo on the homepage with a blue one on a transparent background. Attached a SVG if that's cool with you.

[UN_emblem_blue.zip](https://github.com/crowdAI/crowdai/files/2301901/UN_emblem_blue.zip)

**Comment by scarroll32** [comment]
Changed. Thanks Jason

**Comment by jsnrynlds** [comment]
ツ
