### ISSUE TITLE
Create Submission page broken

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#946]
<img width="1919" alt="screen shot 2018-08-23 at 00 08 39" src="https://user-images.githubusercontent.com/1581312/44493565-c06d5380-a668-11e8-9413-2c6900bce548.png">

The create submission page seems to be broken at the moment.

https://www.crowdai.org/challenges/league-of-nations-archives-digitization-challenge/submissions/new

**Comment by scarroll32** [comment]
Patched, uploading issues to be fixed properly today or tomorrow.
