### ISSUE TITLE
Automatic emails: [ADMIN:crowdAI] Challenge Call response wrong url

### ISSUE THREAD

**Issue by Sylvain-Bernard** [crowdAI/crowdai#947]
Full Description linking to wrong url: **https/www**.crowdai.org/admin/challenge_calls/crowdai/challenge_call_responses/XX

**Comment by scarroll32** [comment]
where?

**Comment by Sylvain-Bernard** [comment]
![image](https://user-images.githubusercontent.com/15749650/44510781-e10fca80-a6b5-11e8-8d0a-cc7a11216335.png)

**Comment by scarroll32** [comment]
Fixed
