### ISSUE TITLE
Maintenance mode shows a blank page

### ISSUE THREAD

**Issue by spMohanty** [crowdAI/crowdai#970]
When we recently moved crowdai to maintenance mode; a blank page was showed. And it was pretty confusing

**Comment by scarroll32** [comment]
I think the last time this was used was before it was launched :-)

**Comment by spMohanty** [comment]
This should be a simple issue, but I would prioritize it, so we are ready for any other emergency in the future ;)

**Comment by scarroll32** [comment]
<img width="1248" alt="screen shot 2018-09-28 at 16 10 35" src="https://user-images.githubusercontent.com/11340230/46213543-18b70580-c339-11e8-98f1-72a35924fcc6.png">

**Comment by scarroll32** [comment]
It is now required to serve the maintenance page via https. Fixed and tested.
