### ISSUE TITLE
Problem logging in to gitlab.crowdai : 422 Email has already been taken

### ISSUE THREAD

**Issue by DavidRuhe** [crowdAI/crowdai#973]
Hi,

When I try to login to the gitlab part of crowdAI it consistently tells me that the e-mail is already in use. Even though I already have registered and am just trying to login. See screenshots. I tried resetting my password, using private sessions and deleting my Google Chrome history.

I'm perfectly logged in at crowdai.org:
![](https://i.imgur.com/UYHo1KI.png)

Then I click on sign in with OAuth:
![](https://i.imgur.com/naDmoUT.png)

Result:
![](https://i.imgur.com/A68Bn7D.png)

Thanks,
David

**Comment by scarroll32** [comment]
Thank you David, we will look into it right away.

**Comment by DavidRuhe** [comment]
Hi Sean, thanks! I just tried logging in on another machine and after logging in at crowdai.org (not the gitlab part) I was prompted to authorise CrowdAI about something. Unfortunately, I just woke up and didn't read carefully and clicked 'authorise' after it showed me some error message. Then I was redirected to the OAuth sign-in page. Now the behaviour is as described in the op again.

Sorry, this is really vague but I forgot to take screenshots. :) Perhaps it can help you.

**Comment by scarroll32** [comment]
Issue resolved
