### ISSUE TITLE
Movies should not autoplay

### ISSUE THREAD

**Issue by marcelsalathe** [crowdAI/crowdai#98]
Instant CPU hog (> 200 % on my MacBook Pro)

**Comment by scarroll32** [comment]
Needs discussion. They are autoplaying at present for effect but also because otherwise they will need a UX control to start them. Currently clicking on the video opens the modal with a larger video.

If the problem is only CPU then we can look into alternatives formats or try and cache the videos.

**Comment by spMohanty** [comment]
I think the CPU hog is because of multiple videos playing all at once, and not coz of unoptimized video.

We could go with thumbnail images on the leaderboaed, which play the video in a modal when clicked ?

**Comment by scarroll32** [comment]
I would agree with that approach:

- Leaderboard contains a thumbnail image with a still from the video (non-animated).
- Click on image to open modal with the large video autoplaying

Related issue: https://github.com/crowdAI/crowdai/issues/108

@marcel are you OK with this approach?

**Comment by scarroll32** [comment]
Decision made in 8/5 meeting: the videos will not autoplay when they are outside the viewport.

http://stackoverflow.com/questions/21163756/html5-and-javascript-to-play-videos-only-when-visible

**Comment by scarroll32** [comment]
Closed
