### ISSUE TITLE
Link submissions to their Gitlab repo

### ISSUE THREAD

**Issue by MasterScrat** [crowdAI/crowdai#983]
For challenges that use the Sourcerer, it is cumbersome to find from which repository each submission originated from.

The URL of that repo is saved as part of the `meta` information of each submission.

**We should display a link from the submissions (in the Leaderboard and Submission pages) pointing to the repository the submission came from.**

The link could even point directly to the relevant tag.

**Comment by scarroll32** [comment]
In the meta there are a couple of repo related fields 

```
{"repo_url":"https://gitlab.crowdai.org/xxxxxx/nips18-avc-model-template","repo_ref":"refs/tags/f67ac758-xxxa-11e8-8xxb-yyyyyyyy","gitlab_project_id":"289","gitlab_issue_iid":"99"}
```

So is this the requirement?

- if the meta "repo_url" key exists, display it on the submissions detail page as a clickable link
- visible only by the participant or an organizer

I'm not sure how to handle submission deletions.

What's the urgency? Unless it's a high it won't get worked for a while.

**Comment by scarroll32** [comment]
Thinking more about this, both the repo and the ref could be displayed on the edit submission page. Only organizers have access to this page. 

<img width="1170" alt="screen shot 2018-09-13 at 08 50 01" src="https://user-images.githubusercontent.com/11340230/45471680-22821b80-b732-11e8-96aa-4451b9c09520.png">

**Comment by scarroll32** [comment]
It seems like this information is already being passed via the submission message.

<img width="1168" alt="screen shot 2018-09-14 at 11 11 52" src="https://user-images.githubusercontent.com/11340230/45541319-15872a00-b80f-11e8-86f7-d30d343079da.png">

**Comment by scarroll32** [comment]
Implemented 

<img width="740" alt="screen shot 2018-09-14 at 11 25 40" src="https://user-images.githubusercontent.com/11340230/45542055-03a68680-b811-11e8-91e7-469ece93e502.png">
