### ISSUE TITLE
Repeating rows in submissions

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#984]
Some rows are repeated in the submissions page, and the load more button is not working.

<img width="650" alt="screen shot 2018-09-14 at 08 46 46" src="https://user-images.githubusercontent.com/11340230/45534227-c0d9b400-b7fa-11e8-8f5a-2f4cba8c15ea.png">

**Comment by jordiju** [comment]
By 'weird' I mean that 
- the submissions 14268 to 15178 are repeated 4 or five times on the submissions page. 
- The "Load More" Button does not work
- I cannot find for example submission 14710 by BerMar (it appears in the screenshot above, but now I cannot see it on the page)

**Comment by jordiju** [comment]
https://www.crowdai.org/challenges/train-schedule-optimisation-challenge/submissions

**Comment by scarroll32** [comment]
Thanks @jordiju, looking into it now.

**Comment by scarroll32** [comment]
Fixed
