### ISSUE TITLE
Submission export as JSON limited to 30 results

### ISSUE THREAD

**Issue by MasterScrat** [crowdAI/crowdai#993]
On the admin page of a challenge listing all the submissions, eg:
https://www.crowdai.org/admin/challenges/<challenge-name>/submissions

There are two links to export the list of submissions: "Download: CSV JSON"

The CSV link exports all of the submissions as CSV, but the JSON link only exports the 30 latest submissions. 

Expected behavior: the JSON link should also export all of the submissions.

**Comment by scarroll32** [comment]
Implemented.

**Comment by scarroll32** [comment]
Reopened 

<img width="693" alt="screen shot 2018-09-27 at 08 21 16" src="https://user-images.githubusercontent.com/11340230/46126641-567b3780-c22e-11e8-8b23-75e8b7f0a90b.png">

**Comment by scarroll32** [comment]
Built on staging but waiting for @MasterScrat 's green light before any prod deploys

**Comment by scarroll32** [comment]
https://travis-ci.org/crowdAI/crowdai/builds/434043435?utm_source=github_status&utm_medium=notification

**Comment by scarroll32** [comment]
JSON done, CSV needs investigation.

**Comment by scarroll32** [comment]
Migrated

**Comment by scarroll32** [comment]
Fixed
