### ISSUE TITLE
hard-coded mandrillapp.com as mailer

### ISSUE THREAD

**Issue by heroxbd** [crowdAI/crowdai#999]
Hi,

In `crowdai/app/mailers` all the `.rb` files are calling mandrillapp.com as mail server.  crowdai should provide a way to configure alternative mail services, or just simply calling `/sbin/sendmail` on the host.

Any hints?

Benda

**Comment by scarroll32** [comment]
Hi @heroxbd thanks for your issue. We use Mandrill for crowdAI production, as we use Mandrill templates for the emails (stored in Mandrill). 

However, it could be generalised to a simple text-based email if you are running crowdAI and wish to use another service. I'd be happy to give you some direction, but we don't plan to move off Mandrill.

If you want to have an alternative service, pull requests are welcome.

**Comment by heroxbd** [comment]
Hi Sean,

> Hi @heroxbd thanks for your issue. We use Mandrill for crowdAI production, as we use Mandrill templates for the emails (stored in Mandrill).

Thanks for clarifying this.
 
> However, it could be generalised to a simple text-based email if you are running crowdAI and wish to use another service. I'd be happy to give you some direction, but we don't plan to move off Mandrill.
 
Would you please give me the direction to use another service, preferably a simple SMTP server without addition API calls. 

> If you want to have an alternative service, pull requests are welcome.

I will when I have one.

Yours,
Benda

**Comment by heroxbd** [comment]
For archiving and document purpose, the way to email delivery from mandrill API to local `sendmail` command is as followed.

```
commit 78400420a8908026c5efb14171c42d2400c5197d
Author: Benda Xu <heroxbd@g.o>
Date:   Wed Oct 3 16:40:24 2018 +0800

    configure to use `sendmail` command on the host to send emails.

diff --git a/config/environments/development.rb b/config/environments/development.rb
index d266d9d9..69893c93 100644
--- a/config/environments/development.rb
+++ b/config/environments/development.rb
@@ -20,6 +20,8 @@ Rails.application.configure do
   end
   config.action_mailer.raise_delivery_errors = false
   config.action_mailer.perform_caching = false
+  config.action_mailer.delivery_method = :sendmail
+  config.action_mailer.default_options = {from: 'xxx@m.n.o'}
   config.active_support.deprecation = :log
   config.active_record.migration_error = :page_load
   config.assets.debug = true
diff --git a/config/initializers/devise.rb b/config/initializers/devise.rb
index 5fa6d045..d077960e 100644
--- a/config/initializers/devise.rb
+++ b/config/initializers/devise.rb
@@ -12,11 +12,10 @@ Devise.setup do |config|
   # Configure the e-mail address which will be shown in Devise::CrowdaiMailer,
   # note that it will be overwritten if you use your own mailer class
   # with default "from" parameter.
-  config.mailer_sender = 'info@crowdai.org'
+  config.mailer_sender = 'xxx@m.n.o'

   # Configure the class responsible to send e-mails.
   #config.mailer = 'Devise::CrowdaiMailer'   # devise erb templates
-  config.mailer = 'DeviseMandrillMailer'  # Mailchimp templates

   # ==> ORM configuration
   # Load and configure the ORM. Supports :active_record (default) and
```
